// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.api;
import com.urbanlogiq.ulsdk.ApiKeyContext;
import com.urbanlogiq.ulsdk.Environment;
import com.urbanlogiq.ulsdk.Region;
import java.util.UUID;
import org.junitpioneer.jupiter.RetryingTest;
import com.urbanlogiq.ulsdk.api.keys.CreateKey;
import com.urbanlogiq.ulsdk.api.keys.GetKeys;
import com.urbanlogiq.ulsdk.api.keys.Key;
import com.urbanlogiq.ulsdk.api.keys.UpdateKey;

public final class TestApiKeys {
    @RetryingTest(maxAttempts = 5, suspendForMs = 200)
    public void testGetKeys() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");

        if (caUser == null || caAccessKey == null || caSecretKey == null) {
            throw new RuntimeException("user / key not present, cannot run tests");
        }

        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
        com.urbanlogiq.ulsdk.TestContext ctx = new com.urbanlogiq.ulsdk.TestContext(new ApiKeyContext(key, Environment.Stage));
        com.urbanlogiq.ulsdk.api.keys.GetKeys expected = new com.urbanlogiq.ulsdk.api.keys.GetKeys();
        byte[] expectedBytes = new org.json.JSONObject(expected.toMap()).toString().getBytes();
        ctx.setResponse(expectedBytes);
        com.urbanlogiq.ulsdk.api.keys.GetKeys result = com.urbanlogiq.ulsdk.api.keys.Keys.getKeys(
            ctx
        );
        org.junit.jupiter.api.Assertions.assertTrue(result.equals(expected));
    }

    @RetryingTest(maxAttempts = 5, suspendForMs = 1000)
    public void testGetKeys1() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");
        String usUser = System.getenv("US_USER");
        String usAccessKey = System.getenv("US_ACCESS_KEY");
        String usSecretKey = System.getenv("US_SECRET_KEY");

        if (caUser != null && caAccessKey != null && caSecretKey != null) {
        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
            ApiKeyContext ctx = new ApiKeyContext(key, Environment.Prod);
            com.urbanlogiq.ulsdk.api.keys.Keys.getKeys(
                ctx
            );
        }

        if (usUser != null && usAccessKey != null && usSecretKey != null) {
        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(usUser), Region.US, usAccessKey, usSecretKey);
            ApiKeyContext ctx = new ApiKeyContext(key, Environment.Prod);
            com.urbanlogiq.ulsdk.api.keys.Keys.getKeys(
                ctx
            );
        }
    }

    @RetryingTest(maxAttempts = 5, suspendForMs = 200)
    public void testCreateKey() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");

        if (caUser == null || caAccessKey == null || caSecretKey == null) {
            throw new RuntimeException("user / key not present, cannot run tests");
        }

        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
        com.urbanlogiq.ulsdk.TestContext ctx = new com.urbanlogiq.ulsdk.TestContext(new ApiKeyContext(key, Environment.Stage));
        com.urbanlogiq.ulsdk.api.keys.CreateKey expected = new com.urbanlogiq.ulsdk.api.keys.CreateKey();
        byte[] expectedBytes = new org.json.JSONObject(expected.toMap()).toString().getBytes();
        ctx.setResponse(expectedBytes);
        com.urbanlogiq.ulsdk.api.keys.CreateKey result = com.urbanlogiq.ulsdk.api.keys.Keys.createKey(
            ctx
        );
        org.junit.jupiter.api.Assertions.assertTrue(result.equals(expected));
    }

    @RetryingTest(maxAttempts = 5, suspendForMs = 200)
    public void testUpdateKey() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");

        if (caUser == null || caAccessKey == null || caSecretKey == null) {
            throw new RuntimeException("user / key not present, cannot run tests");
        }

        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
        com.urbanlogiq.ulsdk.TestContext ctx = new com.urbanlogiq.ulsdk.TestContext(new ApiKeyContext(key, Environment.Stage));
        String p0 = "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
        com.urbanlogiq.ulsdk.api.keys.UpdateKey body = new com.urbanlogiq.ulsdk.api.keys.UpdateKey();
        com.urbanlogiq.ulsdk.api.keys.Keys.updateKey(
            ctx,
            p0,
            body
        );
    }

    @RetryingTest(maxAttempts = 5, suspendForMs = 200)
    public void testGetKey() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");

        if (caUser == null || caAccessKey == null || caSecretKey == null) {
            throw new RuntimeException("user / key not present, cannot run tests");
        }

        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
        com.urbanlogiq.ulsdk.TestContext ctx = new com.urbanlogiq.ulsdk.TestContext(new ApiKeyContext(key, Environment.Stage));
        String p0 = "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
        com.urbanlogiq.ulsdk.api.keys.Key expected = new com.urbanlogiq.ulsdk.api.keys.Key();
        byte[] expectedBytes = new org.json.JSONObject(expected.toMap()).toString().getBytes();
        ctx.setResponse(expectedBytes);
        com.urbanlogiq.ulsdk.api.keys.Key result = com.urbanlogiq.ulsdk.api.keys.Keys.getKey(
            ctx,
            p0
        );
        org.junit.jupiter.api.Assertions.assertTrue(result.equals(expected));
    }

    @RetryingTest(maxAttempts = 5, suspendForMs = 200)
    public void testDeleteKey() throws java.net.URISyntaxException, java.io.IOException, java.lang.InterruptedException {
        String caUser = System.getenv("CA_USER");
        String caAccessKey = System.getenv("CA_ACCESS_KEY");
        String caSecretKey = System.getenv("CA_SECRET_KEY");

        if (caUser == null || caAccessKey == null || caSecretKey == null) {
            throw new RuntimeException("user / key not present, cannot run tests");
        }

        com.urbanlogiq.ulsdk.Key key = new com.urbanlogiq.ulsdk.Key(UUID.fromString(caUser), Region.CA, caAccessKey, caSecretKey);
        com.urbanlogiq.ulsdk.TestContext ctx = new com.urbanlogiq.ulsdk.TestContext(new ApiKeyContext(key, Environment.Stage));
        String p0 = "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
        com.urbanlogiq.ulsdk.api.keys.Keys.deleteKey(
            ctx,
            p0
        );
    }
}