# Copyright (c), CommunityLogiq Software
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT

import os
from ..api_key_context import ApiKeyContext
from ..keys import Region, Key as SigningKey, Environment
from ..api.schematic_evaluator import *

def test_create_job():
    p0 = RunSpec.make_default()

    if False:
        create_job(
            ctx,
            p0,
        )

def test_get_job():
    p0 = UUID("00000000-0000-0000-0000-000000000000")
    p1 = None

    if False:
        get_job(
            ctx,
            p0,
            p1,
        )

def test_get_task():
    p0 = UUID("00000000-0000-0000-0000-000000000000")

    if False:
        get_task(
            ctx,
            p0,
        )
