# Copyright (c), CommunityLogiq Software
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT

from ..types.source_note import *

def test_source_note():
    _t0 = SourceNote.make_default()
    _b = _t0.to_bytes()
    _t1 = SourceNote.from_bytes(_b)
    assert _t0 == _t1
