# Copyright (c), CommunityLogiq Software
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT

from ..types.ontology_declaration import *

def test_ontology_declaration():
    _t0 = OntologyDeclaration.make_default()
    _b = _t0.to_bytes()
    _t1 = OntologyDeclaration.from_bytes(_b)
    assert _t0 == _t1
