// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types.tests;
import org.junit.jupiter.api.Test;

public final class TestDatasetSource {
    @Test
    public void testDefault() {
        new com.urbanlogiq.ulsdk.types.DatasetSource();
    }

    @Test
    public void testSerde() {
        var instance = new com.urbanlogiq.ulsdk.types.DatasetSource();
        byte[] serialized = instance.toBytes();
        var reconstituted = new com.urbanlogiq.ulsdk.types.DatasetSource(serialized);
    }
}