// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types.tests;
import org.junit.Test;

public final class TestUserSettings {
    @Test
    public void testDefault() {
        new com.urbanlogiq.ulsdk.types.UserSettings();
    }

    @Test
    public void testSerde() {
        var instance = new com.urbanlogiq.ulsdk.types.UserSettings();
        byte[] serialized = instance.toBytes();
        var reconstituted = new com.urbanlogiq.ulsdk.types.UserSettings(serialized);
    }
}