// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types.tests;
import org.junit.jupiter.api.Test;

public final class TestInterval {
    @Test
    public void testDefault() {
        new com.urbanlogiq.ulsdk.types.Interval();
    }

    @Test
    public void testSerde() {
        var instance = new com.urbanlogiq.ulsdk.types.Interval();
        byte[] serialized = instance.toBytes();
        var reconstituted = new com.urbanlogiq.ulsdk.types.Interval(serialized);
    }
}