// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types.tests;
import org.junit.Test;

public final class TestContactInfo {
    @Test
    public void testDefault() {
        new com.urbanlogiq.ulsdk.types.ContactInfo();
    }

    @Test
    public void testSerde() {
        var instance = new com.urbanlogiq.ulsdk.types.ContactInfo();
        byte[] serialized = instance.toBytes();
        var reconstituted = new com.urbanlogiq.ulsdk.types.ContactInfo(serialized);
    }
}