// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]
#![allow(mismatched_lifetime_syntaxes)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::useless_conversion)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::enum_clike_unportable_variant)]

use bitflags::bitflags;
use core::ops::Deref;
use flatbuffers::{UnionWIPOffset, WIPOffset};

use crate::types::generated::attr_generated::Attr as FbsAttr;
use crate::types::generated::value_generated::{
    Point2D as FbsPoint2D, Tri2D as FbsTri2D, VArray as FbsVArray, VBool as FbsVBool,
    VBytes as FbsVBytes, VChar as FbsVChar, VF32 as FbsVF32, VF64 as FbsVF64,
    VFixedSizeBytes as FbsVFixedSizeBytes, VI8 as FbsVI8, VI16 as FbsVI16, VI32 as FbsVI32,
    VI64 as FbsVI64, VIsize as FbsVIsize, VNull as FbsVNull, VPlaceholder as FbsVPlaceholder,
    VStr as FbsVStr, VTimestampMs as FbsVTimestampMs, VTimestampMsUtc as FbsVTimestampMsUtc,
    VTimestampNs as FbsVTimestampNs, VTimestampNsUtc as FbsVTimestampNsUtc, VTri2D as FbsVTri2D,
    VU8 as FbsVU8, VU16 as FbsVU16, VU32 as FbsVU32, VU64 as FbsVU64, VUnit as FbsVUnit,
    VUsize as FbsVUsize, Value as FbsValue, ValueInstance as FbsValueInstance,
    ValueTy as FbsValueTy,
};
use crate::types::value::{
    Point2D, Tri2D, VArray, VBool, VBytes, VChar, VF32, VF64, VFixedSizeBytes, VI8, VI16, VI32,
    VI64, VIsize, VNull, VPlaceholder, VStr, VTimestampMs, VTimestampMsUtc, VTimestampNs,
    VTimestampNsUtc, VTri2D, VU8, VU16, VU32, VU64, VUnit, VUsize, Value, ValueInstance, ValueTy,
};

#[derive(Default, PartialEq, Debug, Clone)]
pub struct Attr {
    pub key: String,
    pub v: Value,
}

impl Attr {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsAttr<'a>> {
        use crate::types::generated::attr_generated::AttrBuilder as FbsAttrBuilder;

        let key_offset = builder.create_string(&self.key);
        let (v_offset, v_ty) = self.v.serialize_to(builder);

        let mut bldr = FbsAttrBuilder::new(builder);
        bldr.add_key(key_offset);
        bldr.add_v(v_offset);
        bldr.add_v_type(v_ty);
        bldr.finish()
    }
}

impl From<FbsAttr<'_>> for Attr {
    fn from(fbs: FbsAttr<'_>) -> Self {
        let key = fbs.key().to_owned();
        let v = match fbs.v_type() {
            FbsValue::VBool => Value::VBool(VBool::from(fbs.v_as_vbool().unwrap())),
            FbsValue::VUnit => Value::VUnit(VUnit::from(fbs.v_as_vunit().unwrap())),
            FbsValue::VChar => Value::VChar(VChar::from(fbs.v_as_vchar().unwrap())),
            FbsValue::VNull => Value::VNull(VNull::from(fbs.v_as_vnull().unwrap())),
            FbsValue::VI8 => Value::VI8(VI8::from(fbs.v_as_vi8().unwrap())),
            FbsValue::VU8 => Value::VU8(VU8::from(fbs.v_as_vu8().unwrap())),
            FbsValue::VI16 => Value::VI16(VI16::from(fbs.v_as_vi16().unwrap())),
            FbsValue::VU16 => Value::VU16(VU16::from(fbs.v_as_vu16().unwrap())),
            FbsValue::VI32 => Value::VI32(VI32::from(fbs.v_as_vi32().unwrap())),
            FbsValue::VU32 => Value::VU32(VU32::from(fbs.v_as_vu32().unwrap())),
            FbsValue::VF32 => Value::VF32(VF32::from(fbs.v_as_vf32().unwrap())),
            FbsValue::VIsize => Value::VIsize(VIsize::from(fbs.v_as_visize().unwrap())),
            FbsValue::VUsize => Value::VUsize(VUsize::from(fbs.v_as_vusize().unwrap())),
            FbsValue::VI64 => Value::VI64(VI64::from(fbs.v_as_vi64().unwrap())),
            FbsValue::VU64 => Value::VU64(VU64::from(fbs.v_as_vu64().unwrap())),
            FbsValue::VF64 => Value::VF64(VF64::from(fbs.v_as_vf64().unwrap())),
            FbsValue::VStr => Value::VStr(VStr::from(fbs.v_as_vstr().unwrap())),
            FbsValue::VBytes => Value::VBytes(VBytes::from(fbs.v_as_vbytes().unwrap())),
            FbsValue::VArray => Value::VArray(VArray::from(fbs.v_as_varray().unwrap())),
            FbsValue::VTri2D => Value::VTri2D(VTri2D::from(fbs.v_as_vtri_2_d().unwrap())),
            FbsValue::VFixedSizeBytes => {
                Value::VFixedSizeBytes(VFixedSizeBytes::from(fbs.v_as_vfixed_size_bytes().unwrap()))
            }
            FbsValue::VTimestampMsUtc => {
                Value::VTimestampMsUtc(VTimestampMsUtc::from(fbs.v_as_vtimestamp_ms_utc().unwrap()))
            }
            FbsValue::VTimestampMs => {
                Value::VTimestampMs(VTimestampMs::from(fbs.v_as_vtimestamp_ms().unwrap()))
            }
            FbsValue::VTimestampNsUtc => {
                Value::VTimestampNsUtc(VTimestampNsUtc::from(fbs.v_as_vtimestamp_ns_utc().unwrap()))
            }
            FbsValue::VTimestampNs => {
                Value::VTimestampNs(VTimestampNs::from(fbs.v_as_vtimestamp_ns().unwrap()))
            }
            FbsValue::VPlaceholder => {
                Value::VPlaceholder(VPlaceholder::from(fbs.v_as_vplaceholder().unwrap()))
            }
            _ => unreachable!(),
        };

        Self { key, v }
    }
}

impl Attr {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let fbs = flatbuffers::size_prefixed_root::<FbsAttr>(bytes)?;
        Ok(Self::from(fbs))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_attr() {
        let t0 = Attr::default();
        let buf = t0.to_fbs_bytes();
        let t1 = Attr::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }
}
