// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]
#![allow(mismatched_lifetime_syntaxes)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::useless_conversion)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::enum_clike_unportable_variant)]

use bitflags::bitflags;
use core::ops::Deref;
use flatbuffers::{UnionWIPOffset, WIPOffset};
use ordered_float::OrderedFloat;
use strum_macros::FromRepr;

use crate::types::Schema::{
    Binary, BinaryView, Bool, Buffer, Date, DateUnit, Decimal, DictionaryEncoding, DictionaryKind,
    Duration, Endianness, Feature, Field, FixedSizeBinary, FixedSizeList, FloatingPoint, Int,
    Interval, IntervalUnit, KeyValue, LargeBinary, LargeList, LargeListView, LargeUtf8, List,
    ListView, Map, MetadataVersion, Null, Precision, RunEndEncoded, Schema, Struct_, Time,
    TimeUnit, Timestamp, Type, Union, UnionMode, Utf8, Utf8View,
};
use crate::types::generated::Schema_generated::{
    Binary as FbsBinary, BinaryView as FbsBinaryView, Bool as FbsBool, Buffer as FbsBuffer,
    Date as FbsDate, DateUnit as FbsDateUnit, Decimal as FbsDecimal,
    DictionaryEncoding as FbsDictionaryEncoding, DictionaryKind as FbsDictionaryKind,
    Duration as FbsDuration, Endianness as FbsEndianness, Feature as FbsFeature, Field as FbsField,
    FixedSizeBinary as FbsFixedSizeBinary, FixedSizeList as FbsFixedSizeList,
    FloatingPoint as FbsFloatingPoint, Int as FbsInt, Interval as FbsInterval,
    IntervalUnit as FbsIntervalUnit, KeyValue as FbsKeyValue, LargeBinary as FbsLargeBinary,
    LargeList as FbsLargeList, LargeListView as FbsLargeListView, LargeUtf8 as FbsLargeUtf8,
    List as FbsList, ListView as FbsListView, Map as FbsMap, MetadataVersion as FbsMetadataVersion,
    Null as FbsNull, Precision as FbsPrecision, RunEndEncoded as FbsRunEndEncoded,
    Schema as FbsSchema, Struct_ as FbsStruct_, Time as FbsTime, TimeUnit as FbsTimeUnit,
    Timestamp as FbsTimestamp, Type as FbsType, Union as FbsUnion, UnionMode as FbsUnionMode,
    Utf8 as FbsUtf8, Utf8View as FbsUtf8View,
};
use crate::types::generated::data_generated::{
    AttributePair as FbsAttributePair, BinaryYesNo as FbsBinaryYesNo, DayOfWeek as FbsDayOfWeek,
    DirectionAndRoadName as FbsDirectionAndRoadName,
    DirectionAndRoadNames as FbsDirectionAndRoadNames, DirectionTy as FbsDirectionTy,
    NamedParameter as FbsNamedParameter, NamedParameterFlags as FbsNamedParameterFlags,
    RoadUserTy as FbsRoadUserTy, Source as FbsSource, StatisticTy as FbsStatisticTy,
    TimeGranularity as FbsTimeGranularity, TurnTy as FbsTurnTy,
};
use crate::types::generated::id_generated::{
    B2cId as FbsB2cId, ColumnGroupId as FbsColumnGroupId, ContentId as FbsContentId,
    DataStateId as FbsDataStateId, GenericId as FbsGenericId, GraphNodeId as FbsGraphNodeId,
    ObjectId as FbsObjectId, ObjectNamespace as FbsObjectNamespace, StreamId as FbsStreamId,
};
use crate::types::id::{
    B2cId, ColumnGroupId, ContentId, DataStateId, GenericId, GraphNodeId, ObjectId,
    ObjectNamespace, StreamId,
};

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(u8)]
pub enum BinaryYesNo {
    #[default]
    NO = 0,
    YES = 1,
}

impl TryFrom<u8> for BinaryYesNo {
    type Error = crate::error::Error;
    fn try_from(v: u8) -> Result<Self, crate::error::Error> {
        BinaryYesNo::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl BinaryYesNo {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::NO => Some("NO"),
            Self::YES => Some("YES"),
            _ => None,
        }
    }
}

impl From<BinaryYesNo> for FbsBinaryYesNo {
    fn from(val: BinaryYesNo) -> Self {
        match val {
            BinaryYesNo::NO => FbsBinaryYesNo::NO,
            BinaryYesNo::YES => FbsBinaryYesNo::YES,
        }
    }
}

impl From<FbsBinaryYesNo> for BinaryYesNo {
    fn from(fbs: FbsBinaryYesNo) -> Self {
        match fbs.0 {
            0 => Self::NO,
            1 => Self::YES,
            _ => panic!("Invalid value {} when constructing BinaryYesNo", fbs.0),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(u8)]
pub enum DayOfWeek {
    #[default]
    MONDAY = 0,
    TUESDAY = 1,
    WEDNESDAY = 2,
    THURSDAY = 3,
    FRIDAY = 4,
    SATURDAY = 5,
    SUNDAY = 6,
}

impl TryFrom<u8> for DayOfWeek {
    type Error = crate::error::Error;
    fn try_from(v: u8) -> Result<Self, crate::error::Error> {
        DayOfWeek::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl DayOfWeek {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::MONDAY => Some("MONDAY"),
            Self::TUESDAY => Some("TUESDAY"),
            Self::WEDNESDAY => Some("WEDNESDAY"),
            Self::THURSDAY => Some("THURSDAY"),
            Self::FRIDAY => Some("FRIDAY"),
            Self::SATURDAY => Some("SATURDAY"),
            Self::SUNDAY => Some("SUNDAY"),
            _ => None,
        }
    }
}

impl From<DayOfWeek> for FbsDayOfWeek {
    fn from(val: DayOfWeek) -> Self {
        match val {
            DayOfWeek::MONDAY => FbsDayOfWeek::MONDAY,
            DayOfWeek::TUESDAY => FbsDayOfWeek::TUESDAY,
            DayOfWeek::WEDNESDAY => FbsDayOfWeek::WEDNESDAY,
            DayOfWeek::THURSDAY => FbsDayOfWeek::THURSDAY,
            DayOfWeek::FRIDAY => FbsDayOfWeek::FRIDAY,
            DayOfWeek::SATURDAY => FbsDayOfWeek::SATURDAY,
            DayOfWeek::SUNDAY => FbsDayOfWeek::SUNDAY,
        }
    }
}

impl From<FbsDayOfWeek> for DayOfWeek {
    fn from(fbs: FbsDayOfWeek) -> Self {
        match fbs.0 {
            0 => Self::MONDAY,
            1 => Self::TUESDAY,
            2 => Self::WEDNESDAY,
            3 => Self::THURSDAY,
            4 => Self::FRIDAY,
            5 => Self::SATURDAY,
            6 => Self::SUNDAY,
            _ => panic!("Invalid value {} when constructing DayOfWeek", fbs.0),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(i32)]
pub enum DirectionTy {
    #[default]
    NB = 0,
    WB = 1,
    SB = 2,
    EB = 3,
    NWB = 4,
    NEB = 5,
    SWB = 6,
    SEB = 7,
    MINUS_MP = 8,
    PLUS_MP = 9,
    IN = 10,
    OUT = 11,
    TOTAL = 12,
    N = 13,
    W = 14,
    E = 15,
    S = 16,
    NW = 17,
    NE = 18,
    SW = 19,
    SE = 20,
}

impl TryFrom<i32> for DirectionTy {
    type Error = crate::error::Error;
    fn try_from(v: i32) -> Result<Self, crate::error::Error> {
        DirectionTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl DirectionTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::NB => Some("NB"),
            Self::WB => Some("WB"),
            Self::SB => Some("SB"),
            Self::EB => Some("EB"),
            Self::NWB => Some("NWB"),
            Self::NEB => Some("NEB"),
            Self::SWB => Some("SWB"),
            Self::SEB => Some("SEB"),
            Self::MINUS_MP => Some("MINUS_MP"),
            Self::PLUS_MP => Some("PLUS_MP"),
            Self::IN => Some("IN"),
            Self::OUT => Some("OUT"),
            Self::TOTAL => Some("TOTAL"),
            Self::N => Some("N"),
            Self::W => Some("W"),
            Self::E => Some("E"),
            Self::S => Some("S"),
            Self::NW => Some("NW"),
            Self::NE => Some("NE"),
            Self::SW => Some("SW"),
            Self::SE => Some("SE"),
            _ => None,
        }
    }
}

impl From<DirectionTy> for FbsDirectionTy {
    fn from(val: DirectionTy) -> Self {
        match val {
            DirectionTy::NB => FbsDirectionTy::NB,
            DirectionTy::WB => FbsDirectionTy::WB,
            DirectionTy::SB => FbsDirectionTy::SB,
            DirectionTy::EB => FbsDirectionTy::EB,
            DirectionTy::NWB => FbsDirectionTy::NWB,
            DirectionTy::NEB => FbsDirectionTy::NEB,
            DirectionTy::SWB => FbsDirectionTy::SWB,
            DirectionTy::SEB => FbsDirectionTy::SEB,
            DirectionTy::MINUS_MP => FbsDirectionTy::MINUS_MP,
            DirectionTy::PLUS_MP => FbsDirectionTy::PLUS_MP,
            DirectionTy::IN => FbsDirectionTy::IN,
            DirectionTy::OUT => FbsDirectionTy::OUT,
            DirectionTy::TOTAL => FbsDirectionTy::TOTAL,
            DirectionTy::N => FbsDirectionTy::N,
            DirectionTy::W => FbsDirectionTy::W,
            DirectionTy::E => FbsDirectionTy::E,
            DirectionTy::S => FbsDirectionTy::S,
            DirectionTy::NW => FbsDirectionTy::NW,
            DirectionTy::NE => FbsDirectionTy::NE,
            DirectionTy::SW => FbsDirectionTy::SW,
            DirectionTy::SE => FbsDirectionTy::SE,
        }
    }
}

impl From<FbsDirectionTy> for DirectionTy {
    fn from(fbs: FbsDirectionTy) -> Self {
        match fbs.0 {
            0 => Self::NB,
            1 => Self::WB,
            2 => Self::SB,
            3 => Self::EB,
            4 => Self::NWB,
            5 => Self::NEB,
            6 => Self::SWB,
            7 => Self::SEB,
            8 => Self::MINUS_MP,
            9 => Self::PLUS_MP,
            10 => Self::IN,
            11 => Self::OUT,
            12 => Self::TOTAL,
            13 => Self::N,
            14 => Self::W,
            15 => Self::E,
            16 => Self::S,
            17 => Self::NW,
            18 => Self::NE,
            19 => Self::SW,
            20 => Self::SE,
            _ => panic!("Invalid value {} when constructing DirectionTy", fbs.0),
        }
    }
}

/// If no flags are set, this indicates the associated NamedParameter is required.
bitflags! {
    #[derive(Default)]
    pub struct NamedParameterFlags: u32 {
        /// This variant indicates the parameter is a Value type (see the TaskParameter definition)
        const VALUE = 1;
        /// This variant indicates the parameter does not need to be specified
        const OPTIONAL = 2;
    }
}

impl From<NamedParameterFlags> for FbsNamedParameterFlags {
    fn from(val: NamedParameterFlags) -> Self {
        Self::from_bits_truncate(val.bits())
    }
}

impl From<FbsNamedParameterFlags> for NamedParameterFlags {
    fn from(fbs: FbsNamedParameterFlags) -> Self {
        Self::from_bits_truncate(fbs.bits())
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(i32)]
pub enum RoadUserTy {
    #[default]
    BIKES = 0,
    BUSES = 1,
    CARS = 2,
    ARTICULATED_TRUCKS = 3,
    CARS_AND_LIGHT_GOODS_VEHICLES = 4,
    LIGHT_GOODS_VEHICLES = 5,
    SINGLE_UNIT_TRUCKS = 6,
    HEAVY_VEHICLES = 7,
    MOTORCYCLES = 8,
    ALL_VEHICLES = 9,
    TRUCKS = 10,
    REGULAR_VEHICLES = 11,
    MEDIUM_TRUCKS = 12,
    HEAVY_TRUCKS = 13,
    LIGHT_TRUCKS = 14,
    LIGHT_VEHICLES = 15,
    MEDIUM_VEHICLES = 16,
    MULTI_UNIT_TRUCKS = 17,
    TRUCKS_AND_BUSES = 18,
    TRANSIT_BUSES = 19,
    SCHOOL_BUSES = 20,
    E_SCOOTERS = 21,
    MOTORIZED_VEHICLES = 22,
    CARS_AND_OTHERS = 23,
    PEDS = 24,
    ADULT_PEDS = 25,
    CHILD_PEDS = 26,
    SENIOR_PEDS = 27,
    DISABLED_PEDS = 28,
    BICYCLES_ON_CROSSWALK = 29,
    PEDS_AND_BIKES = 30,
    PHYSICALLY_CHALLENGED_PEDS = 31,
    CROSSWALKS = 32,
    TRAMS = 33,
    TAXIS = 34,
}

impl TryFrom<i32> for RoadUserTy {
    type Error = crate::error::Error;
    fn try_from(v: i32) -> Result<Self, crate::error::Error> {
        RoadUserTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl RoadUserTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::BIKES => Some("BIKES"),
            Self::BUSES => Some("BUSES"),
            Self::CARS => Some("CARS"),
            Self::ARTICULATED_TRUCKS => Some("ARTICULATED_TRUCKS"),
            Self::CARS_AND_LIGHT_GOODS_VEHICLES => Some("CARS_AND_LIGHT_GOODS_VEHICLES"),
            Self::LIGHT_GOODS_VEHICLES => Some("LIGHT_GOODS_VEHICLES"),
            Self::SINGLE_UNIT_TRUCKS => Some("SINGLE_UNIT_TRUCKS"),
            Self::HEAVY_VEHICLES => Some("HEAVY_VEHICLES"),
            Self::MOTORCYCLES => Some("MOTORCYCLES"),
            Self::ALL_VEHICLES => Some("ALL_VEHICLES"),
            Self::TRUCKS => Some("TRUCKS"),
            Self::REGULAR_VEHICLES => Some("REGULAR_VEHICLES"),
            Self::MEDIUM_TRUCKS => Some("MEDIUM_TRUCKS"),
            Self::HEAVY_TRUCKS => Some("HEAVY_TRUCKS"),
            Self::LIGHT_TRUCKS => Some("LIGHT_TRUCKS"),
            Self::LIGHT_VEHICLES => Some("LIGHT_VEHICLES"),
            Self::MEDIUM_VEHICLES => Some("MEDIUM_VEHICLES"),
            Self::MULTI_UNIT_TRUCKS => Some("MULTI_UNIT_TRUCKS"),
            Self::TRUCKS_AND_BUSES => Some("TRUCKS_AND_BUSES"),
            Self::TRANSIT_BUSES => Some("TRANSIT_BUSES"),
            Self::SCHOOL_BUSES => Some("SCHOOL_BUSES"),
            Self::E_SCOOTERS => Some("E_SCOOTERS"),
            Self::MOTORIZED_VEHICLES => Some("MOTORIZED_VEHICLES"),
            Self::CARS_AND_OTHERS => Some("CARS_AND_OTHERS"),
            Self::PEDS => Some("PEDS"),
            Self::ADULT_PEDS => Some("ADULT_PEDS"),
            Self::CHILD_PEDS => Some("CHILD_PEDS"),
            Self::SENIOR_PEDS => Some("SENIOR_PEDS"),
            Self::DISABLED_PEDS => Some("DISABLED_PEDS"),
            Self::BICYCLES_ON_CROSSWALK => Some("BICYCLES_ON_CROSSWALK"),
            Self::PEDS_AND_BIKES => Some("PEDS_AND_BIKES"),
            Self::PHYSICALLY_CHALLENGED_PEDS => Some("PHYSICALLY_CHALLENGED_PEDS"),
            Self::CROSSWALKS => Some("CROSSWALKS"),
            Self::TRAMS => Some("TRAMS"),
            Self::TAXIS => Some("TAXIS"),
            _ => None,
        }
    }
}

impl From<RoadUserTy> for FbsRoadUserTy {
    fn from(val: RoadUserTy) -> Self {
        match val {
            RoadUserTy::BIKES => FbsRoadUserTy::BIKES,
            RoadUserTy::BUSES => FbsRoadUserTy::BUSES,
            RoadUserTy::CARS => FbsRoadUserTy::CARS,
            RoadUserTy::ARTICULATED_TRUCKS => FbsRoadUserTy::ARTICULATED_TRUCKS,
            RoadUserTy::CARS_AND_LIGHT_GOODS_VEHICLES => {
                FbsRoadUserTy::CARS_AND_LIGHT_GOODS_VEHICLES
            }
            RoadUserTy::LIGHT_GOODS_VEHICLES => FbsRoadUserTy::LIGHT_GOODS_VEHICLES,
            RoadUserTy::SINGLE_UNIT_TRUCKS => FbsRoadUserTy::SINGLE_UNIT_TRUCKS,
            RoadUserTy::HEAVY_VEHICLES => FbsRoadUserTy::HEAVY_VEHICLES,
            RoadUserTy::MOTORCYCLES => FbsRoadUserTy::MOTORCYCLES,
            RoadUserTy::ALL_VEHICLES => FbsRoadUserTy::ALL_VEHICLES,
            RoadUserTy::TRUCKS => FbsRoadUserTy::TRUCKS,
            RoadUserTy::REGULAR_VEHICLES => FbsRoadUserTy::REGULAR_VEHICLES,
            RoadUserTy::MEDIUM_TRUCKS => FbsRoadUserTy::MEDIUM_TRUCKS,
            RoadUserTy::HEAVY_TRUCKS => FbsRoadUserTy::HEAVY_TRUCKS,
            RoadUserTy::LIGHT_TRUCKS => FbsRoadUserTy::LIGHT_TRUCKS,
            RoadUserTy::LIGHT_VEHICLES => FbsRoadUserTy::LIGHT_VEHICLES,
            RoadUserTy::MEDIUM_VEHICLES => FbsRoadUserTy::MEDIUM_VEHICLES,
            RoadUserTy::MULTI_UNIT_TRUCKS => FbsRoadUserTy::MULTI_UNIT_TRUCKS,
            RoadUserTy::TRUCKS_AND_BUSES => FbsRoadUserTy::TRUCKS_AND_BUSES,
            RoadUserTy::TRANSIT_BUSES => FbsRoadUserTy::TRANSIT_BUSES,
            RoadUserTy::SCHOOL_BUSES => FbsRoadUserTy::SCHOOL_BUSES,
            RoadUserTy::E_SCOOTERS => FbsRoadUserTy::E_SCOOTERS,
            RoadUserTy::MOTORIZED_VEHICLES => FbsRoadUserTy::MOTORIZED_VEHICLES,
            RoadUserTy::CARS_AND_OTHERS => FbsRoadUserTy::CARS_AND_OTHERS,
            RoadUserTy::PEDS => FbsRoadUserTy::PEDS,
            RoadUserTy::ADULT_PEDS => FbsRoadUserTy::ADULT_PEDS,
            RoadUserTy::CHILD_PEDS => FbsRoadUserTy::CHILD_PEDS,
            RoadUserTy::SENIOR_PEDS => FbsRoadUserTy::SENIOR_PEDS,
            RoadUserTy::DISABLED_PEDS => FbsRoadUserTy::DISABLED_PEDS,
            RoadUserTy::BICYCLES_ON_CROSSWALK => FbsRoadUserTy::BICYCLES_ON_CROSSWALK,
            RoadUserTy::PEDS_AND_BIKES => FbsRoadUserTy::PEDS_AND_BIKES,
            RoadUserTy::PHYSICALLY_CHALLENGED_PEDS => FbsRoadUserTy::PHYSICALLY_CHALLENGED_PEDS,
            RoadUserTy::CROSSWALKS => FbsRoadUserTy::CROSSWALKS,
            RoadUserTy::TRAMS => FbsRoadUserTy::TRAMS,
            RoadUserTy::TAXIS => FbsRoadUserTy::TAXIS,
        }
    }
}

impl From<FbsRoadUserTy> for RoadUserTy {
    fn from(fbs: FbsRoadUserTy) -> Self {
        match fbs.0 {
            0 => Self::BIKES,
            1 => Self::BUSES,
            2 => Self::CARS,
            3 => Self::ARTICULATED_TRUCKS,
            4 => Self::CARS_AND_LIGHT_GOODS_VEHICLES,
            5 => Self::LIGHT_GOODS_VEHICLES,
            6 => Self::SINGLE_UNIT_TRUCKS,
            7 => Self::HEAVY_VEHICLES,
            8 => Self::MOTORCYCLES,
            9 => Self::ALL_VEHICLES,
            10 => Self::TRUCKS,
            11 => Self::REGULAR_VEHICLES,
            12 => Self::MEDIUM_TRUCKS,
            13 => Self::HEAVY_TRUCKS,
            14 => Self::LIGHT_TRUCKS,
            15 => Self::LIGHT_VEHICLES,
            16 => Self::MEDIUM_VEHICLES,
            17 => Self::MULTI_UNIT_TRUCKS,
            18 => Self::TRUCKS_AND_BUSES,
            19 => Self::TRANSIT_BUSES,
            20 => Self::SCHOOL_BUSES,
            21 => Self::E_SCOOTERS,
            22 => Self::MOTORIZED_VEHICLES,
            23 => Self::CARS_AND_OTHERS,
            24 => Self::PEDS,
            25 => Self::ADULT_PEDS,
            26 => Self::CHILD_PEDS,
            27 => Self::SENIOR_PEDS,
            28 => Self::DISABLED_PEDS,
            29 => Self::BICYCLES_ON_CROSSWALK,
            30 => Self::PEDS_AND_BIKES,
            31 => Self::PHYSICALLY_CHALLENGED_PEDS,
            32 => Self::CROSSWALKS,
            33 => Self::TRAMS,
            34 => Self::TAXIS,
            _ => panic!("Invalid value {} when constructing RoadUserTy", fbs.0),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(i32)]
pub enum StatisticTy {
    #[default]
    PERCENTILE_15 = 15,
    PERCENTILE_20 = 20,
    PERCENTILE_30 = 30,
    PERCENTILE_40 = 40,
    PERCENTILE_50 = 50,
    PERCENTILE_85 = 85,
    PERCENTILE_95 = 95,
    PERCENTILE_100 = 100,
    MEDIAN = 101,
    MEAN = 102,
    MODE = 103,
    SPEED_LIMIT = 104,
    STAT_MAX = 105,
    STAT_MIN = 106,
    MEAN_EXCEEDING = 107,
    STANDARD_DEVIATION = 108,
    NUMBER_OF_VEHICLES_EXCEEDING = 109,
}

impl TryFrom<i32> for StatisticTy {
    type Error = crate::error::Error;
    fn try_from(v: i32) -> Result<Self, crate::error::Error> {
        StatisticTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl StatisticTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::PERCENTILE_15 => Some("PERCENTILE_15"),
            Self::PERCENTILE_20 => Some("PERCENTILE_20"),
            Self::PERCENTILE_30 => Some("PERCENTILE_30"),
            Self::PERCENTILE_40 => Some("PERCENTILE_40"),
            Self::PERCENTILE_50 => Some("PERCENTILE_50"),
            Self::PERCENTILE_85 => Some("PERCENTILE_85"),
            Self::PERCENTILE_95 => Some("PERCENTILE_95"),
            Self::PERCENTILE_100 => Some("PERCENTILE_100"),
            Self::MEDIAN => Some("MEDIAN"),
            Self::MEAN => Some("MEAN"),
            Self::MODE => Some("MODE"),
            Self::SPEED_LIMIT => Some("SPEED_LIMIT"),
            Self::STAT_MAX => Some("STAT_MAX"),
            Self::STAT_MIN => Some("STAT_MIN"),
            Self::MEAN_EXCEEDING => Some("MEAN_EXCEEDING"),
            Self::STANDARD_DEVIATION => Some("STANDARD_DEVIATION"),
            Self::NUMBER_OF_VEHICLES_EXCEEDING => Some("NUMBER_OF_VEHICLES_EXCEEDING"),
            _ => None,
        }
    }
}

impl From<StatisticTy> for FbsStatisticTy {
    fn from(val: StatisticTy) -> Self {
        match val {
            StatisticTy::PERCENTILE_15 => FbsStatisticTy::PERCENTILE_15,
            StatisticTy::PERCENTILE_20 => FbsStatisticTy::PERCENTILE_20,
            StatisticTy::PERCENTILE_30 => FbsStatisticTy::PERCENTILE_30,
            StatisticTy::PERCENTILE_40 => FbsStatisticTy::PERCENTILE_40,
            StatisticTy::PERCENTILE_50 => FbsStatisticTy::PERCENTILE_50,
            StatisticTy::PERCENTILE_85 => FbsStatisticTy::PERCENTILE_85,
            StatisticTy::PERCENTILE_95 => FbsStatisticTy::PERCENTILE_95,
            StatisticTy::PERCENTILE_100 => FbsStatisticTy::PERCENTILE_100,
            StatisticTy::MEDIAN => FbsStatisticTy::MEDIAN,
            StatisticTy::MEAN => FbsStatisticTy::MEAN,
            StatisticTy::MODE => FbsStatisticTy::MODE,
            StatisticTy::SPEED_LIMIT => FbsStatisticTy::SPEED_LIMIT,
            StatisticTy::STAT_MAX => FbsStatisticTy::STAT_MAX,
            StatisticTy::STAT_MIN => FbsStatisticTy::STAT_MIN,
            StatisticTy::MEAN_EXCEEDING => FbsStatisticTy::MEAN_EXCEEDING,
            StatisticTy::STANDARD_DEVIATION => FbsStatisticTy::STANDARD_DEVIATION,
            StatisticTy::NUMBER_OF_VEHICLES_EXCEEDING => {
                FbsStatisticTy::NUMBER_OF_VEHICLES_EXCEEDING
            }
        }
    }
}

impl From<FbsStatisticTy> for StatisticTy {
    fn from(fbs: FbsStatisticTy) -> Self {
        match fbs.0 {
            15 => Self::PERCENTILE_15,
            20 => Self::PERCENTILE_20,
            30 => Self::PERCENTILE_30,
            40 => Self::PERCENTILE_40,
            50 => Self::PERCENTILE_50,
            85 => Self::PERCENTILE_85,
            95 => Self::PERCENTILE_95,
            100 => Self::PERCENTILE_100,
            101 => Self::MEDIAN,
            102 => Self::MEAN,
            103 => Self::MODE,
            104 => Self::SPEED_LIMIT,
            105 => Self::STAT_MAX,
            106 => Self::STAT_MIN,
            107 => Self::MEAN_EXCEEDING,
            108 => Self::STANDARD_DEVIATION,
            109 => Self::NUMBER_OF_VEHICLES_EXCEEDING,
            _ => panic!("Invalid value {} when constructing StatisticTy", fbs.0),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(i32)]
pub enum TimeGranularity {
    #[default]
    NONE = 0,
    Daily = 1,
}

impl TryFrom<i32> for TimeGranularity {
    type Error = crate::error::Error;
    fn try_from(v: i32) -> Result<Self, crate::error::Error> {
        TimeGranularity::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl TimeGranularity {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::NONE => Some("NONE"),
            Self::Daily => Some("Daily"),
            _ => None,
        }
    }
}

impl From<TimeGranularity> for FbsTimeGranularity {
    fn from(val: TimeGranularity) -> Self {
        match val {
            TimeGranularity::NONE => FbsTimeGranularity::NONE,
            TimeGranularity::Daily => FbsTimeGranularity::Daily,
        }
    }
}

impl From<FbsTimeGranularity> for TimeGranularity {
    fn from(fbs: FbsTimeGranularity) -> Self {
        match fbs.0 {
            0 => Self::NONE,
            1 => Self::Daily,
            _ => panic!("Invalid value {} when constructing TimeGranularity", fbs.0),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(i32)]
pub enum TurnTy {
    #[default]
    CW = 0,
    CCW = 1,
    NONE = 2,
    LEFT = 3,
    RIGHT = 4,
    THRU = 5,
    U_TURN = 6,
    BEAR_RIGHT = 7,
    BEAR_LEFT = 8,
    HARD_RIGHT = 9,
    HARD_LEFT = 10,
    RIGHT_TURNING_ON_RED = 11,
    BEAR_RIGHT_ON_RED = 12,
}

impl TryFrom<i32> for TurnTy {
    type Error = crate::error::Error;
    fn try_from(v: i32) -> Result<Self, crate::error::Error> {
        TurnTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl TurnTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::CW => Some("CW"),
            Self::CCW => Some("CCW"),
            Self::NONE => Some("NONE"),
            Self::LEFT => Some("LEFT"),
            Self::RIGHT => Some("RIGHT"),
            Self::THRU => Some("THRU"),
            Self::U_TURN => Some("U_TURN"),
            Self::BEAR_RIGHT => Some("BEAR_RIGHT"),
            Self::BEAR_LEFT => Some("BEAR_LEFT"),
            Self::HARD_RIGHT => Some("HARD_RIGHT"),
            Self::HARD_LEFT => Some("HARD_LEFT"),
            Self::RIGHT_TURNING_ON_RED => Some("RIGHT_TURNING_ON_RED"),
            Self::BEAR_RIGHT_ON_RED => Some("BEAR_RIGHT_ON_RED"),
            _ => None,
        }
    }
}

impl From<TurnTy> for FbsTurnTy {
    fn from(val: TurnTy) -> Self {
        match val {
            TurnTy::CW => FbsTurnTy::CW,
            TurnTy::CCW => FbsTurnTy::CCW,
            TurnTy::NONE => FbsTurnTy::NONE,
            TurnTy::LEFT => FbsTurnTy::LEFT,
            TurnTy::RIGHT => FbsTurnTy::RIGHT,
            TurnTy::THRU => FbsTurnTy::THRU,
            TurnTy::U_TURN => FbsTurnTy::U_TURN,
            TurnTy::BEAR_RIGHT => FbsTurnTy::BEAR_RIGHT,
            TurnTy::BEAR_LEFT => FbsTurnTy::BEAR_LEFT,
            TurnTy::HARD_RIGHT => FbsTurnTy::HARD_RIGHT,
            TurnTy::HARD_LEFT => FbsTurnTy::HARD_LEFT,
            TurnTy::RIGHT_TURNING_ON_RED => FbsTurnTy::RIGHT_TURNING_ON_RED,
            TurnTy::BEAR_RIGHT_ON_RED => FbsTurnTy::BEAR_RIGHT_ON_RED,
        }
    }
}

impl From<FbsTurnTy> for TurnTy {
    fn from(fbs: FbsTurnTy) -> Self {
        match fbs.0 {
            0 => Self::CW,
            1 => Self::CCW,
            2 => Self::NONE,
            3 => Self::LEFT,
            4 => Self::RIGHT,
            5 => Self::THRU,
            6 => Self::U_TURN,
            7 => Self::BEAR_RIGHT,
            8 => Self::BEAR_LEFT,
            9 => Self::HARD_RIGHT,
            10 => Self::HARD_LEFT,
            11 => Self::RIGHT_TURNING_ON_RED,
            12 => Self::BEAR_RIGHT_ON_RED,
            _ => panic!("Invalid value {} when constructing TurnTy", fbs.0),
        }
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct AttributePair {
    pub key: Option<String>,
    pub value: Option<String>,
}

impl AttributePair {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsAttributePair<'a>> {
        use crate::types::generated::data_generated::AttributePairBuilder as FbsAttributePairBuilder;

        let key_offset = self.key.as_ref().map(|s| builder.create_string(s));
        let value_offset = self.value.as_ref().map(|s| builder.create_string(s));

        let mut bldr = FbsAttributePairBuilder::new(builder);
        if let Some(offset) = key_offset {
            bldr.add_key(offset);
        }
        if let Some(offset) = value_offset {
            bldr.add_value(offset);
        }
        bldr.finish()
    }
}

impl From<FbsAttributePair<'_>> for AttributePair {
    fn from(fbs: FbsAttributePair<'_>) -> Self {
        let key = fbs.key().map(ToOwned::to_owned);
        let value = fbs.value().map(ToOwned::to_owned);
        Self { key, value }
    }
}

impl AttributePair {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsAttributePair>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct DirectionAndRoadName {
    pub direction: String,
    pub road_name: String,
}

impl DirectionAndRoadName {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsDirectionAndRoadName<'a>> {
        use crate::types::generated::data_generated::DirectionAndRoadNameBuilder as FbsDirectionAndRoadNameBuilder;

        let direction_offset = builder.create_string(&self.direction);
        let road_name_offset = builder.create_string(&self.road_name);

        let mut bldr = FbsDirectionAndRoadNameBuilder::new(builder);
        bldr.add_direction(direction_offset);
        bldr.add_road_name(road_name_offset);
        bldr.finish()
    }
}

impl From<FbsDirectionAndRoadName<'_>> for DirectionAndRoadName {
    fn from(fbs: FbsDirectionAndRoadName<'_>) -> Self {
        let direction = fbs.direction().to_owned();
        let road_name = fbs.road_name().to_owned();
        Self {
            direction,
            road_name,
        }
    }
}

impl DirectionAndRoadName {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs =
            flatbuffers::size_prefixed_root_with_opts::<FbsDirectionAndRoadName>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct DirectionAndRoadNames {
    pub direction_and_road_names: Option<Vec<DirectionAndRoadName>>,
}

impl DirectionAndRoadNames {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsDirectionAndRoadNames<'a>> {
        use crate::types::generated::data_generated::DirectionAndRoadNamesBuilder as FbsDirectionAndRoadNamesBuilder;

        let direction_and_road_names_offset = self.direction_and_road_names.as_ref().map(|v| {
            let mut direction_and_road_names_offsets = Vec::with_capacity(v.len());
            for val in v.iter() {
                let offset = val.serialize_to(builder);
                direction_and_road_names_offsets.push(offset);
            }
            let direction_and_road_names_offset =
                builder.create_vector(&direction_and_road_names_offsets);
            direction_and_road_names_offset
        });

        let mut bldr = FbsDirectionAndRoadNamesBuilder::new(builder);
        if let Some(offset) = direction_and_road_names_offset {
            bldr.add_direction_and_road_names(offset);
        }
        bldr.finish()
    }
}

impl From<FbsDirectionAndRoadNames<'_>> for DirectionAndRoadNames {
    fn from(fbs: FbsDirectionAndRoadNames<'_>) -> Self {
        let direction_and_road_names = if let Some(val) = fbs.direction_and_road_names() {
            let mut direction_and_road_names = Vec::new();
            for elem in val {
                direction_and_road_names.push(elem.into());
            }

            Some(direction_and_road_names)
        } else {
            None
        };

        Self {
            direction_and_road_names,
        }
    }
}

impl DirectionAndRoadNames {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs =
            flatbuffers::size_prefixed_root_with_opts::<FbsDirectionAndRoadNames>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct NamedParameter {
    pub description: Option<String>,
    pub flags: u32,
    pub name: String,
    pub schema: Option<Schema>,
}

impl NamedParameter {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsNamedParameter<'a>> {
        use crate::types::generated::data_generated::NamedParameterBuilder as FbsNamedParameterBuilder;

        let description_offset = self.description.as_ref().map(|s| builder.create_string(s));
        let name_offset = builder.create_string(&self.name);
        let schema_offset = self.schema.as_ref().map(|o| o.serialize_to(builder));

        let mut bldr = FbsNamedParameterBuilder::new(builder);
        if let Some(offset) = description_offset {
            bldr.add_description(offset);
        }
        bldr.add_flags(self.flags);
        bldr.add_name(name_offset);
        if let Some(offset) = schema_offset {
            bldr.add_schema(offset);
        }
        bldr.finish()
    }
}

impl From<FbsNamedParameter<'_>> for NamedParameter {
    fn from(fbs: FbsNamedParameter<'_>) -> Self {
        let description = fbs.description().map(ToOwned::to_owned);
        let flags = fbs.flags();
        let name = fbs.name().to_owned();
        let schema = fbs.schema().map(Schema::from);
        Self {
            description,
            flags,
            name,
            schema,
        }
    }
}

impl NamedParameter {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsNamedParameter>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct Source {
    pub metadata: Option<ObjectId>,
    pub metadata_revision: Option<ContentId>,
    pub name: String,
    pub named_parameters: Option<Vec<NamedParameter>>,
    pub options: Option<Vec<u8>>,
    pub schemas: Option<Vec<Schema>>,
    pub url: String,
}

impl Source {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsSource<'a>> {
        use crate::types::generated::data_generated::SourceBuilder as FbsSourceBuilder;

        let metadata_offset = self.metadata.as_ref().map(|o| o.serialize_to(builder));
        let metadata_revision_offset = self
            .metadata_revision
            .as_ref()
            .map(|o| o.serialize_to(builder));
        let name_offset = builder.create_string(&self.name);
        let named_parameters_offset = self.named_parameters.as_ref().map(|v| {
            let mut named_parameters_offsets = Vec::with_capacity(v.len());
            for val in v.iter() {
                let offset = val.serialize_to(builder);
                named_parameters_offsets.push(offset);
            }
            let named_parameters_offset = builder.create_vector(&named_parameters_offsets);
            named_parameters_offset
        });
        let options_offset = self.options.as_ref().map(|v| {
            let options_offset = builder.create_vector(&v);
            options_offset
        });
        let schemas_offset = self.schemas.as_ref().map(|v| {
            let mut schemas_offsets = Vec::with_capacity(v.len());
            for val in v.iter() {
                let offset = val.serialize_to(builder);
                schemas_offsets.push(offset);
            }
            let schemas_offset = builder.create_vector(&schemas_offsets);
            schemas_offset
        });
        let url_offset = builder.create_string(&self.url);

        let mut bldr = FbsSourceBuilder::new(builder);
        if let Some(offset) = metadata_offset {
            bldr.add_metadata(offset);
        }
        if let Some(offset) = metadata_revision_offset {
            bldr.add_metadata_revision(offset);
        }
        bldr.add_name(name_offset);
        if let Some(offset) = named_parameters_offset {
            bldr.add_named_parameters(offset);
        }
        if let Some(offset) = options_offset {
            bldr.add_options(offset);
        }
        if let Some(offset) = schemas_offset {
            bldr.add_schemas(offset);
        }
        bldr.add_url(url_offset);
        bldr.finish()
    }
}

impl From<FbsSource<'_>> for Source {
    fn from(fbs: FbsSource<'_>) -> Self {
        let metadata = fbs.metadata().map(ObjectId::from);
        let metadata_revision = fbs.metadata_revision().map(ContentId::from);
        let name = fbs.name().to_owned();
        let named_parameters = if let Some(val) = fbs.named_parameters() {
            let mut named_parameters = Vec::new();
            for elem in val {
                named_parameters.push(elem.into());
            }

            Some(named_parameters)
        } else {
            None
        };

        let options = if let Some(val) = fbs.options() {
            let mut options = Vec::new();
            for elem in val {
                options.push(elem.into());
            }

            Some(options)
        } else {
            None
        };

        let schemas = if let Some(val) = fbs.schemas() {
            let mut schemas = Vec::new();
            for elem in val {
                schemas.push(elem.into());
            }

            Some(schemas)
        } else {
            None
        };

        let url = fbs.url().to_owned();
        Self {
            metadata,
            metadata_revision,
            name,
            named_parameters,
            options,
            schemas,
            url,
        }
    }
}

impl Source {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsSource>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_attribute_pair() {
        let t0 = AttributePair::default();
        let buf = t0.to_fbs_bytes();
        let t1 = AttributePair::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_direction_and_road_name() {
        let t0 = DirectionAndRoadName::default();
        let buf = t0.to_fbs_bytes();
        let t1 = DirectionAndRoadName::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_direction_and_road_names() {
        let t0 = DirectionAndRoadNames::default();
        let buf = t0.to_fbs_bytes();
        let t1 = DirectionAndRoadNames::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_named_parameter() {
        let t0 = NamedParameter::default();
        let buf = t0.to_fbs_bytes();
        let t1 = NamedParameter::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_source() {
        let t0 = Source::default();
        let buf = t0.to_fbs_bytes();
        let t1 = Source::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }
}
