// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]
#![allow(mismatched_lifetime_syntaxes)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::useless_conversion)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::enum_clike_unportable_variant)]

use bitflags::bitflags;
use core::ops::Deref;
use flatbuffers::{UnionWIPOffset, WIPOffset};
use ordered_float::OrderedFloat;
use strum_macros::FromRepr;

use crate::types::Schema::{
    Binary, BinaryView, Bool, Buffer, Date, DateUnit, Decimal, DictionaryEncoding, DictionaryKind,
    Duration, Endianness, Feature, Field, FixedSizeBinary, FixedSizeList, FloatingPoint, Int,
    Interval, IntervalUnit, KeyValue, LargeBinary, LargeList, LargeListView, LargeUtf8, List,
    ListView, Map, MetadataVersion, Null, Precision, RunEndEncoded, Schema, Struct_, Time,
    TimeUnit, Timestamp, Type, Union, UnionMode, Utf8, Utf8View,
};
use crate::types::attr::Attr;
use crate::types::data::{
    AttributePair, BinaryYesNo, DayOfWeek, DirectionAndRoadName, DirectionAndRoadNames,
    DirectionTy, NamedParameter, NamedParameterFlags, RoadUserTy, Source, StatisticTy,
    TimeGranularity, TurnTy,
};
use crate::types::generated::Schema_generated::{
    Binary as FbsBinary, BinaryView as FbsBinaryView, Bool as FbsBool, Buffer as FbsBuffer,
    Date as FbsDate, DateUnit as FbsDateUnit, Decimal as FbsDecimal,
    DictionaryEncoding as FbsDictionaryEncoding, DictionaryKind as FbsDictionaryKind,
    Duration as FbsDuration, Endianness as FbsEndianness, Feature as FbsFeature, Field as FbsField,
    FixedSizeBinary as FbsFixedSizeBinary, FixedSizeList as FbsFixedSizeList,
    FloatingPoint as FbsFloatingPoint, Int as FbsInt, Interval as FbsInterval,
    IntervalUnit as FbsIntervalUnit, KeyValue as FbsKeyValue, LargeBinary as FbsLargeBinary,
    LargeList as FbsLargeList, LargeListView as FbsLargeListView, LargeUtf8 as FbsLargeUtf8,
    List as FbsList, ListView as FbsListView, Map as FbsMap, MetadataVersion as FbsMetadataVersion,
    Null as FbsNull, Precision as FbsPrecision, RunEndEncoded as FbsRunEndEncoded,
    Schema as FbsSchema, Struct_ as FbsStruct_, Time as FbsTime, TimeUnit as FbsTimeUnit,
    Timestamp as FbsTimestamp, Type as FbsType, Union as FbsUnion, UnionMode as FbsUnionMode,
    Utf8 as FbsUtf8, Utf8View as FbsUtf8View,
};
use crate::types::generated::attr_generated::Attr as FbsAttr;
use crate::types::generated::data_generated::{
    AttributePair as FbsAttributePair, BinaryYesNo as FbsBinaryYesNo, DayOfWeek as FbsDayOfWeek,
    DirectionAndRoadName as FbsDirectionAndRoadName,
    DirectionAndRoadNames as FbsDirectionAndRoadNames, DirectionTy as FbsDirectionTy,
    NamedParameter as FbsNamedParameter, NamedParameterFlags as FbsNamedParameterFlags,
    RoadUserTy as FbsRoadUserTy, Source as FbsSource, StatisticTy as FbsStatisticTy,
    TimeGranularity as FbsTimeGranularity, TurnTy as FbsTurnTy,
};
use crate::types::generated::id_generated::{
    B2cId as FbsB2cId, ColumnGroupId as FbsColumnGroupId, ContentId as FbsContentId,
    DataStateId as FbsDataStateId, GenericId as FbsGenericId, GraphNodeId as FbsGraphNodeId,
    ObjectId as FbsObjectId, ObjectNamespace as FbsObjectNamespace, StreamId as FbsStreamId,
};
use crate::types::generated::job_generated::{
    DeprecatedRunSpec as FbsDeprecatedRunSpec,
    DeprecatedTaskParameter as FbsDeprecatedTaskParameter, Edge as FbsEdge,
    EmbeddedTable as FbsEmbeddedTable, Job as FbsJob, Node as FbsNode,
    ParamIndices as FbsParamIndices, RunSpec as FbsRunSpec, Schematic as FbsSchematic,
    Status as FbsStatus, Task as FbsTask, TaskErrorTy as FbsTaskErrorTy, TaskList as FbsTaskList,
    TaskParameter as FbsTaskParameter, TaskParameterValue as FbsTaskParameterValue,
    TaskPriority as FbsTaskPriority, TaskRunFlags as FbsTaskRunFlags,
};
use crate::types::generated::value_generated::{
    Point2D as FbsPoint2D, Tri2D as FbsTri2D, VArray as FbsVArray, VBool as FbsVBool,
    VBytes as FbsVBytes, VChar as FbsVChar, VF32 as FbsVF32, VF64 as FbsVF64,
    VFixedSizeBytes as FbsVFixedSizeBytes, VI8 as FbsVI8, VI16 as FbsVI16, VI32 as FbsVI32,
    VI64 as FbsVI64, VIsize as FbsVIsize, VNull as FbsVNull, VPlaceholder as FbsVPlaceholder,
    VStr as FbsVStr, VTimestampMs as FbsVTimestampMs, VTimestampMsUtc as FbsVTimestampMsUtc,
    VTimestampNs as FbsVTimestampNs, VTimestampNsUtc as FbsVTimestampNsUtc, VTri2D as FbsVTri2D,
    VU8 as FbsVU8, VU16 as FbsVU16, VU32 as FbsVU32, VU64 as FbsVU64, VUnit as FbsVUnit,
    VUsize as FbsVUsize, Value as FbsValue, ValueInstance as FbsValueInstance,
    ValueTy as FbsValueTy,
};
use crate::types::generated::worklog_generated::{
    AggregationTy as FbsAggregationTy, ByteArray as FbsByteArray, ChartTypeTy as FbsChartTypeTy,
    Layout as FbsLayout, ParameterFlags as FbsParameterFlags, ParameterValue as FbsParameterValue,
    TileData as FbsTileData, TileSettings as FbsTileSettings, UserSettings as FbsUserSettings,
    ValuesFormatTy as FbsValuesFormatTy, WorkLog as FbsWorkLog,
    WorklogParameter as FbsWorklogParameter,
};
use crate::types::id::{
    B2cId, ColumnGroupId, ContentId, DataStateId, GenericId, GraphNodeId, ObjectId,
    ObjectNamespace, StreamId,
};
use crate::types::job::{
    DeprecatedRunSpec, DeprecatedTaskParameter, Edge, EmbeddedTable, Job, Node, ParamIndices,
    RunSpec, Schematic, Status, Task, TaskErrorTy, TaskList, TaskParameter, TaskParameterValue,
    TaskPriority, TaskRunFlags,
};
use crate::types::value::{
    Point2D, Tri2D, VArray, VBool, VBytes, VChar, VF32, VF64, VFixedSizeBytes, VI8, VI16, VI32,
    VI64, VIsize, VNull, VPlaceholder, VStr, VTimestampMs, VTimestampMsUtc, VTimestampNs,
    VTimestampNsUtc, VTri2D, VU8, VU16, VU32, VU64, VUnit, VUsize, Value, ValueInstance, ValueTy,
};

/// In the aggregate data, there are two relevant keys relevant to the user,
/// sum and average. This stores which to show in the chart
#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(u32)]
pub enum AggregationTy {
    #[default]
    Invalid = 0,
    Sum = 1,
    Average = 2,
}

impl TryFrom<u32> for AggregationTy {
    type Error = crate::error::Error;
    fn try_from(v: u32) -> Result<Self, crate::error::Error> {
        AggregationTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl AggregationTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::Invalid => Some("Invalid"),
            Self::Sum => Some("Sum"),
            Self::Average => Some("Average"),
            _ => None,
        }
    }
}

impl From<AggregationTy> for FbsAggregationTy {
    fn from(val: AggregationTy) -> Self {
        match val {
            AggregationTy::Invalid => FbsAggregationTy::Invalid,
            AggregationTy::Sum => FbsAggregationTy::Sum,
            AggregationTy::Average => FbsAggregationTy::Average,
        }
    }
}

impl From<FbsAggregationTy> for AggregationTy {
    fn from(fbs: FbsAggregationTy) -> Self {
        match fbs.0 {
            0 => Self::Invalid,
            1 => Self::Sum,
            2 => Self::Average,
            _ => panic!("Invalid value {} when constructing AggregationTy", fbs.0),
        }
    }
}

/// The type of chart to use to display the data
#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(u32)]
pub enum ChartTypeTy {
    #[default]
    Invalid = 0,
    Bar = 1,
    HorizontalBar = 2,
    Doughnut = 3,
    Line = 4,
    SimpleTable = 5,
    SingleNumber = 6,
    Text = 7,
    DashboardTable = 8,
}

impl TryFrom<u32> for ChartTypeTy {
    type Error = crate::error::Error;
    fn try_from(v: u32) -> Result<Self, crate::error::Error> {
        ChartTypeTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl ChartTypeTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::Invalid => Some("Invalid"),
            Self::Bar => Some("Bar"),
            Self::HorizontalBar => Some("HorizontalBar"),
            Self::Doughnut => Some("Doughnut"),
            Self::Line => Some("Line"),
            Self::SimpleTable => Some("SimpleTable"),
            Self::SingleNumber => Some("SingleNumber"),
            Self::Text => Some("Text"),
            Self::DashboardTable => Some("DashboardTable"),
            _ => None,
        }
    }
}

impl From<ChartTypeTy> for FbsChartTypeTy {
    fn from(val: ChartTypeTy) -> Self {
        match val {
            ChartTypeTy::Invalid => FbsChartTypeTy::Invalid,
            ChartTypeTy::Bar => FbsChartTypeTy::Bar,
            ChartTypeTy::HorizontalBar => FbsChartTypeTy::HorizontalBar,
            ChartTypeTy::Doughnut => FbsChartTypeTy::Doughnut,
            ChartTypeTy::Line => FbsChartTypeTy::Line,
            ChartTypeTy::SimpleTable => FbsChartTypeTy::SimpleTable,
            ChartTypeTy::SingleNumber => FbsChartTypeTy::SingleNumber,
            ChartTypeTy::Text => FbsChartTypeTy::Text,
            ChartTypeTy::DashboardTable => FbsChartTypeTy::DashboardTable,
        }
    }
}

impl From<FbsChartTypeTy> for ChartTypeTy {
    fn from(fbs: FbsChartTypeTy) -> Self {
        match fbs.0 {
            0 => Self::Invalid,
            1 => Self::Bar,
            2 => Self::HorizontalBar,
            3 => Self::Doughnut,
            4 => Self::Line,
            5 => Self::SimpleTable,
            6 => Self::SingleNumber,
            7 => Self::Text,
            8 => Self::DashboardTable,
            _ => panic!("Invalid value {} when constructing ChartTypeTy", fbs.0),
        }
    }
}

/// Whether do display raw numbers or percentages
#[derive(Debug, Clone, Copy, Default, PartialEq, Hash, Eq, FromRepr)]
#[repr(u32)]
pub enum ValuesFormatTy {
    #[default]
    Invalid = 0,
    RawNumber = 1,
    Percentage = 2,
}

impl TryFrom<u32> for ValuesFormatTy {
    type Error = crate::error::Error;
    fn try_from(v: u32) -> Result<Self, crate::error::Error> {
        ValuesFormatTy::from_repr(v).ok_or(crate::error::Error::InvalidEnumValue(v as i64))
    }
}

impl ValuesFormatTy {
    pub fn variant_name(&self) -> Option<&'static str> {
        match self {
            Self::Invalid => Some("Invalid"),
            Self::RawNumber => Some("RawNumber"),
            Self::Percentage => Some("Percentage"),
            _ => None,
        }
    }
}

impl From<ValuesFormatTy> for FbsValuesFormatTy {
    fn from(val: ValuesFormatTy) -> Self {
        match val {
            ValuesFormatTy::Invalid => FbsValuesFormatTy::Invalid,
            ValuesFormatTy::RawNumber => FbsValuesFormatTy::RawNumber,
            ValuesFormatTy::Percentage => FbsValuesFormatTy::Percentage,
        }
    }
}

impl From<FbsValuesFormatTy> for ValuesFormatTy {
    fn from(fbs: FbsValuesFormatTy) -> Self {
        match fbs.0 {
            0 => Self::Invalid,
            1 => Self::RawNumber,
            2 => Self::Percentage,
            _ => panic!("Invalid value {} when constructing ValuesFormatTy", fbs.0),
        }
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct ByteArray {
    pub b: Option<Vec<u8>>,
}

impl ByteArray {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsByteArray<'a>> {
        use crate::types::generated::worklog_generated::ByteArrayBuilder as FbsByteArrayBuilder;

        let b_offset = self.b.as_ref().map(|v| {
            let b_offset = builder.create_vector(&v);
            b_offset
        });

        let mut bldr = FbsByteArrayBuilder::new(builder);
        if let Some(offset) = b_offset {
            bldr.add_b(offset);
        }
        bldr.finish()
    }
}

impl From<FbsByteArray<'_>> for ByteArray {
    fn from(fbs: FbsByteArray<'_>) -> Self {
        let b = if let Some(val) = fbs.b() {
            let mut b = Vec::new();
            for elem in val {
                b.push(elem.into());
            }

            Some(b)
        } else {
            None
        };

        Self { b }
    }
}

impl ByteArray {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsByteArray>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct ParameterFlags {
    pub flags: i64,
}

impl ParameterFlags {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsParameterFlags<'a>> {
        use crate::types::generated::worklog_generated::ParameterFlagsBuilder as FbsParameterFlagsBuilder;

        let mut bldr = FbsParameterFlagsBuilder::new(builder);
        bldr.add_flags(self.flags);
        bldr.finish()
    }
}

impl From<FbsParameterFlags<'_>> for ParameterFlags {
    fn from(fbs: FbsParameterFlags<'_>) -> Self {
        let flags = fbs.flags();
        Self { flags }
    }
}

impl ParameterFlags {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsParameterFlags>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Clone, Debug, PartialEq, Hash, Eq)]
pub enum ParameterValue {
    ByteArray(ByteArray),
    ObjectId(ObjectId),
    ParameterFlags(ParameterFlags),
    ValueInstance(ValueInstance),
}

impl Default for ParameterValue {
    fn default() -> Self {
        Self::ByteArray(ByteArray::default())
    }
}

impl ParameterValue {
    pub fn serialize_to(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder,
    ) -> (WIPOffset<UnionWIPOffset>, FbsParameterValue) {
        match self {
            Self::ByteArray(val) => {
                let offset = val.serialize_to(builder).as_union_value();
                let ty = FbsParameterValue::ByteArray;
                (offset, ty)
            }
            Self::ObjectId(val) => {
                let offset = val.serialize_to(builder).as_union_value();
                let ty = FbsParameterValue::ObjectId;
                (offset, ty)
            }
            Self::ParameterFlags(val) => {
                let offset = val.serialize_to(builder).as_union_value();
                let ty = FbsParameterValue::ParameterFlags;
                (offset, ty)
            }
            Self::ValueInstance(val) => {
                let offset = val.serialize_to(builder).as_union_value();
                let ty = FbsParameterValue::ValueInstance;
                (offset, ty)
            }
        }
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct Layout {
    /// The height of the chart tile in react-grid-layout grid units
    pub height: u32,
    /// The width in react-grid-layout grid units
    pub width: u32,
    /// The x position in react-grid-layout grid units
    pub x: u32,
    /// The y position in react-grid-layout grid units
    pub y: u32,
}

impl Layout {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsLayout<'a>> {
        use crate::types::generated::worklog_generated::LayoutBuilder as FbsLayoutBuilder;

        let mut bldr = FbsLayoutBuilder::new(builder);
        bldr.add_height(self.height);
        bldr.add_width(self.width);
        bldr.add_x(self.x);
        bldr.add_y(self.y);
        bldr.finish()
    }
}

impl From<FbsLayout<'_>> for Layout {
    fn from(fbs: FbsLayout<'_>) -> Self {
        let height = fbs.height();
        let width = fbs.width();
        let x = fbs.x();
        let y = fbs.y();
        Self {
            height,
            width,
            x,
            y,
        }
    }
}

impl Layout {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsLayout>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct TileSettings {
    /// The column of tbe aggregation dataset to use
    pub aggregation: AggregationTy,
    /// The category
    pub category: u32,
    /// What chart type to display the data as
    pub chart_type: ChartTypeTy,
    /// The field name from the metadata and dataset. Note that if it is a
    /// relationshipField, it will use the displayName instead
    pub field_name: String,
    /// Whether to group the other fields under "Other" if not showing all columns
    pub group_others: bool,
    /// Record-count tiles report on the total number of graph nodes for the stream in the area, rather than
    /// on any specific field in that stream.
    pub is_record_count_tile: bool,
    /// Whether it is a relationship field (or a non-associated field)
    pub is_relationship_field: bool,
    /// The metadata id for the field shown
    pub metadata_id: ObjectId,
    /// Which output stream the report belongs to
    pub output_stream_index: u32,
    pub record_count_stream_id: Option<ObjectId>,
    /// Which columns the user has selected to show. If this is a relationship field, the user
    /// can select which of the relationship fields to show. If it is nonassociated field, it's
    /// possible that they only want to show certain ranges, which would be stored here, but
    /// that isn't currently supported
    pub selected_columns: Vec<String>,
    /// Font size for text tiles
    pub text_tile_font_size: u32,
    /// The title of the tile
    pub title: String,
    /// Percentage or RawNumber
    pub values_format: ValuesFormatTy,
}

impl TileSettings {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsTileSettings<'a>> {
        use crate::types::generated::worklog_generated::TileSettingsBuilder as FbsTileSettingsBuilder;

        let field_name_offset = builder.create_string(&self.field_name);
        let metadata_id_offset = self.metadata_id.serialize_to(builder);
        let record_count_stream_id_offset = self
            .record_count_stream_id
            .as_ref()
            .map(|o| o.serialize_to(builder));
        let mut selected_columns_offsets = Vec::with_capacity(self.selected_columns.len());
        for val in self.selected_columns.iter() {
            let offset = builder.create_string(val);
            selected_columns_offsets.push(offset);
        }
        let selected_columns_offset = builder.create_vector(&selected_columns_offsets);
        let title_offset = builder.create_string(&self.title);

        let mut bldr = FbsTileSettingsBuilder::new(builder);
        bldr.add_aggregation(FbsAggregationTy::from(self.aggregation));
        bldr.add_category(self.category);
        bldr.add_chart_type(FbsChartTypeTy::from(self.chart_type));
        bldr.add_field_name(field_name_offset);
        bldr.add_group_others(self.group_others);
        bldr.add_is_record_count_tile(self.is_record_count_tile);
        bldr.add_is_relationship_field(self.is_relationship_field);
        bldr.add_metadata_id(metadata_id_offset);
        bldr.add_output_stream_index(self.output_stream_index);
        if let Some(offset) = record_count_stream_id_offset {
            bldr.add_record_count_stream_id(offset);
        }
        bldr.add_selected_columns(selected_columns_offset);
        bldr.add_text_tile_font_size(self.text_tile_font_size);
        bldr.add_title(title_offset);
        bldr.add_values_format(FbsValuesFormatTy::from(self.values_format));
        bldr.finish()
    }
}

impl From<FbsTileSettings<'_>> for TileSettings {
    fn from(fbs: FbsTileSettings<'_>) -> Self {
        let aggregation = AggregationTy::from(fbs.aggregation());
        let category = fbs.category();
        let chart_type = ChartTypeTy::from(fbs.chart_type());
        let field_name = fbs.field_name().to_owned();
        let group_others = fbs.group_others();
        let is_record_count_tile = fbs.is_record_count_tile();
        let is_relationship_field = fbs.is_relationship_field();
        let metadata_id = ObjectId::from(fbs.metadata_id());
        let output_stream_index = fbs.output_stream_index();
        let record_count_stream_id = fbs.record_count_stream_id().map(ObjectId::from);
        let mut selected_columns = Vec::new();
        for elem in fbs.selected_columns() {
            selected_columns.push(elem.into());
        }

        let text_tile_font_size = fbs.text_tile_font_size();
        let title = fbs.title().to_owned();
        let values_format = ValuesFormatTy::from(fbs.values_format());
        Self {
            aggregation,
            category,
            chart_type,
            field_name,
            group_others,
            is_record_count_tile,
            is_relationship_field,
            metadata_id,
            output_stream_index,
            record_count_stream_id,
            selected_columns,
            text_tile_font_size,
            title,
            values_format,
        }
    }
}

impl TileSettings {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsTileSettings>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct TileData {
    pub layout: Layout,
    pub tile_settings: TileSettings,
}

impl TileData {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsTileData<'a>> {
        use crate::types::generated::worklog_generated::TileDataBuilder as FbsTileDataBuilder;

        let layout_offset = self.layout.serialize_to(builder);
        let tile_settings_offset = self.tile_settings.serialize_to(builder);

        let mut bldr = FbsTileDataBuilder::new(builder);
        bldr.add_layout(layout_offset);
        bldr.add_tile_settings(tile_settings_offset);
        bldr.finish()
    }
}

impl From<FbsTileData<'_>> for TileData {
    fn from(fbs: FbsTileData<'_>) -> Self {
        let layout = Layout::from(fbs.layout());
        let tile_settings = TileSettings::from(fbs.tile_settings());
        Self {
            layout,
            tile_settings,
        }
    }
}

impl TileData {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsTileData>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct UserSettings {
    pub is_template: bool,
    pub tile_data: Vec<TileData>,
}

impl UserSettings {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsUserSettings<'a>> {
        use crate::types::generated::worklog_generated::UserSettingsBuilder as FbsUserSettingsBuilder;

        let mut tile_data_offsets = Vec::with_capacity(self.tile_data.len());
        for val in self.tile_data.iter() {
            let offset = val.serialize_to(builder);
            tile_data_offsets.push(offset);
        }
        let tile_data_offset = builder.create_vector(&tile_data_offsets);

        let mut bldr = FbsUserSettingsBuilder::new(builder);
        bldr.add_is_template(self.is_template);
        bldr.add_tile_data(tile_data_offset);
        bldr.finish()
    }
}

impl From<FbsUserSettings<'_>> for UserSettings {
    fn from(fbs: FbsUserSettings<'_>) -> Self {
        let is_template = fbs.is_template();
        let mut tile_data = Vec::new();
        for elem in fbs.tile_data() {
            tile_data.push(elem.into());
        }

        Self {
            is_template,
            tile_data,
        }
    }
}

impl UserSettings {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsUserSettings>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct WorkLog {
    /// Input streams and/or worklogs. These may be either work logs or streams.
    pub input_streams: Option<Vec<ObjectId>>,
    pub job_id: Option<ObjectId>,
    /// A human-readable tag.
    pub name: Option<String>,
    /// The output_streams contain a list of Parquet documents that consist of
    /// the results. These documents may expire (ie: if this is a temporary
    /// step) so there should be enough information in the worklog necessary
    /// to reconstruct these output streams.
    pub output_streams: Vec<ObjectId>,
    /// These are the serialized parameters passed into the task which created
    /// this worklog.
    pub params: Vec<WorklogParameter>,
    /// Worklogs can contain multiple "levels". Consider the case where the user
    /// submits a request for multiple ADT reports. We will create separate ADT
    /// reports as required but also one that ties them all together. There are a
    /// couple reasons for this; the primary is that the output of a schematic
    /// node is allocated before the job is run and before it knows how many
    /// worklogs will be generated. Another is that it makes it it easy (or
    /// easier) to organize because we can sort based on "stuff the user requested",
    /// instead of just "stuff the system generated".
    pub parent: Option<ObjectId>,
    /// The schematic used behind creating the worklog. This may be empty/null
    /// if we are just layering data, for example.
    pub schematic: ObjectId,
    pub user_settings: Option<UserSettings>,
}

impl WorkLog {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsWorkLog<'a>> {
        use crate::types::generated::worklog_generated::WorkLogBuilder as FbsWorkLogBuilder;

        let input_streams_offset = self.input_streams.as_ref().map(|v| {
            let mut input_streams_offsets = Vec::with_capacity(v.len());
            for val in v.iter() {
                let offset = val.serialize_to(builder);
                input_streams_offsets.push(offset);
            }
            let input_streams_offset = builder.create_vector(&input_streams_offsets);
            input_streams_offset
        });
        let job_id_offset = self.job_id.as_ref().map(|o| o.serialize_to(builder));
        let name_offset = self.name.as_ref().map(|s| builder.create_string(s));
        let mut output_streams_offsets = Vec::with_capacity(self.output_streams.len());
        for val in self.output_streams.iter() {
            let offset = val.serialize_to(builder);
            output_streams_offsets.push(offset);
        }
        let output_streams_offset = builder.create_vector(&output_streams_offsets);
        let mut params_offsets = Vec::with_capacity(self.params.len());
        for val in self.params.iter() {
            let offset = val.serialize_to(builder);
            params_offsets.push(offset);
        }
        let params_offset = builder.create_vector(&params_offsets);
        let parent_offset = self.parent.as_ref().map(|o| o.serialize_to(builder));
        let schematic_offset = self.schematic.serialize_to(builder);
        let user_settings_offset = self.user_settings.as_ref().map(|o| o.serialize_to(builder));

        let mut bldr = FbsWorkLogBuilder::new(builder);
        if let Some(offset) = input_streams_offset {
            bldr.add_input_streams(offset);
        }
        if let Some(offset) = job_id_offset {
            bldr.add_job_id(offset);
        }
        if let Some(offset) = name_offset {
            bldr.add_name(offset);
        }
        bldr.add_output_streams(output_streams_offset);
        bldr.add_params(params_offset);
        if let Some(offset) = parent_offset {
            bldr.add_parent(offset);
        }
        bldr.add_schematic(schematic_offset);
        if let Some(offset) = user_settings_offset {
            bldr.add_user_settings(offset);
        }
        bldr.finish()
    }
}

impl From<FbsWorkLog<'_>> for WorkLog {
    fn from(fbs: FbsWorkLog<'_>) -> Self {
        let input_streams = if let Some(val) = fbs.input_streams() {
            let mut input_streams = Vec::new();
            for elem in val {
                input_streams.push(elem.into());
            }

            Some(input_streams)
        } else {
            None
        };

        let job_id = fbs.job_id().map(ObjectId::from);
        let name = fbs.name().map(ToOwned::to_owned);
        let mut output_streams = Vec::new();
        for elem in fbs.output_streams() {
            output_streams.push(elem.into());
        }

        let mut params = Vec::new();
        for elem in fbs.params() {
            params.push(elem.into());
        }

        let parent = fbs.parent().map(ObjectId::from);
        let schematic = ObjectId::from(fbs.schematic());
        let user_settings = fbs.user_settings().map(UserSettings::from);
        Self {
            input_streams,
            job_id,
            name,
            output_streams,
            params,
            parent,
            schematic,
            user_settings,
        }
    }
}

impl WorkLog {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsWorkLog>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[derive(Default, PartialEq, Debug, Clone, Hash, Eq)]
pub struct WorklogParameter {
    pub key: String,
    pub value: Option<ParameterValue>,
}

impl WorklogParameter {
    pub fn serialize_to<'a>(
        &self,
        builder: &mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> flatbuffers::WIPOffset<FbsWorklogParameter<'a>> {
        use crate::types::generated::worklog_generated::WorklogParameterBuilder as FbsWorklogParameterBuilder;

        let key_offset = builder.create_string(&self.key);
        let value_offset = self.value.as_ref().map(|u| u.serialize_to(builder));

        let mut bldr = FbsWorklogParameterBuilder::new(builder);
        bldr.add_key(key_offset);
        if let Some((offset, ty)) = value_offset {
            bldr.add_value(offset);
            bldr.add_value_type(ty);
        }
        bldr.finish()
    }
}

impl From<FbsWorklogParameter<'_>> for WorklogParameter {
    fn from(fbs: FbsWorklogParameter<'_>) -> Self {
        let key = fbs.key().to_owned();
        let value = if let Some(val) = fbs.value() {
            let value = match fbs.value_type() {
                FbsParameterValue::ByteArray => {
                    ParameterValue::ByteArray(ByteArray::from(fbs.value_as_byte_array().unwrap()))
                }
                FbsParameterValue::ObjectId => {
                    ParameterValue::ObjectId(ObjectId::from(fbs.value_as_object_id().unwrap()))
                }
                FbsParameterValue::ParameterFlags => ParameterValue::ParameterFlags(
                    ParameterFlags::from(fbs.value_as_parameter_flags().unwrap()),
                ),
                FbsParameterValue::ValueInstance => ParameterValue::ValueInstance(
                    ValueInstance::from(fbs.value_as_value_instance().unwrap()),
                ),
                _ => unreachable!(),
            };

            Some(value)
        } else {
            None
        };

        Self { key, value }
    }
}

impl WorklogParameter {
    pub fn to_fbs_bytes(&self) -> Vec<u8> {
        let mut bldr = flatbuffers::FlatBufferBuilder::new();
        let offset = self.serialize_to(&mut bldr);
        bldr.finish_size_prefixed(offset, None);
        bldr.finished_data().to_vec()
    }

    pub fn from_fbs_bytes(bytes: &[u8]) -> Result<Self, flatbuffers::InvalidFlatbuffer> {
        let opts = flatbuffers::VerifierOptions {
            max_tables: 100_000_000,
            ..Default::default()
        };
        let fbs = flatbuffers::size_prefixed_root_with_opts::<FbsWorklogParameter>(&opts, bytes)?;
        Ok(Self::from(fbs))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_byte_array() {
        let t0 = ByteArray::default();
        let buf = t0.to_fbs_bytes();
        let t1 = ByteArray::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_layout() {
        let t0 = Layout::default();
        let buf = t0.to_fbs_bytes();
        let t1 = Layout::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_parameter_flags() {
        let t0 = ParameterFlags::default();
        let buf = t0.to_fbs_bytes();
        let t1 = ParameterFlags::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_tile_data() {
        let t0 = TileData::default();
        let buf = t0.to_fbs_bytes();
        let t1 = TileData::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_tile_settings() {
        let t0 = TileSettings::default();
        let buf = t0.to_fbs_bytes();
        let t1 = TileSettings::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_user_settings() {
        let t0 = UserSettings::default();
        let buf = t0.to_fbs_bytes();
        let t1 = UserSettings::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_work_log() {
        let t0 = WorkLog::default();
        let buf = t0.to_fbs_bytes();
        let t1 = WorkLog::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }

    #[test]
    fn test_worklog_parameter() {
        let t0 = WorklogParameter::default();
        let buf = t0.to_fbs_bytes();
        let t1 = WorklogParameter::from_fbs_bytes(buf.as_slice()).unwrap();
        assert_eq!(t0, t1);
    }
}
