// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

import { Footer } from '../File';

describe('Footer', () => {
  it('should default-construct', () => {
    const instance = new Footer();
    expect(instance).toBeDefined();
  });

  it('should serialize and deserialize', () => {
    const instance = new Footer();
    const bytes = instance.toBytes();
    const reconstituted = new Footer(bytes);
    expect(reconstituted).toBeDefined();
  });
});
