// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package source_note

import "testing"

func TestDefaultSourceNote(t *testing.T) {
	o := &SourceNote{}
	if o == nil {
		t.Fatal("expected non-nil")
	}
}

