// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package source_note

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/urbanlogiq/ulsdk/types/generated"
	"github.com/urbanlogiq/ulsdk/types/id"
)

var _ flatbuffers.UOffsetT

// SourceNote -
//  A source note, as cortext's source-note registry stores it: one governed
//  object per declared source, homed in the `.models` system directory beside
//  `ModelManifest`, `OntologyDeclaration` and `Mission` (the same
//  governed-object recipe), with an ACL the owner controls and the platform's
//  own revision history.
//
//  The object is a *reference*, like the other three: the note is a Drive
//  file named here by id, content revision and sha256, and the fields a reader
//  lists on (the source it annotates, its title, who published it and when)
//  are projected once per source revision into the `source_notes` registry
//  (registry.fbs), so nothing on a read path opens the document. The document
//  is markdown, an authored file — the registry reads it as text, not as a
//  structured source.
type SourceNote struct {
	AuthoredBy *string
	DocumentCid *id.ContentId
	DocumentId id.ObjectId
	DocumentSha256 string
	PublishedAt int64
	SourceId string
	Title *string
}

func SourceNoteFromFbs(fbs *generated.SourceNote) *SourceNote {
	o := &SourceNote{}
	if s := fbs.AuthoredBy(); s != nil {
		str := string(s)
		o.AuthoredBy = &str
	}
	if fbsVal := fbs.DocumentCid(nil); fbsVal != nil {
		o.DocumentCid = id.ContentIdFromFbs(fbsVal)
	}
	if fbsVal := fbs.DocumentId(nil); fbsVal != nil {
		o.DocumentId = *id.ObjectIdFromFbs(fbsVal)
	}
	o.DocumentSha256 = string(fbs.DocumentSha256())
	o.PublishedAt = fbs.PublishedAt()
	o.SourceId = string(fbs.SourceId())
	if s := fbs.Title(); s != nil {
		str := string(s)
		o.Title = &str
	}
	return o
}

// SourceNoteFromBytes deserializes a SourceNote from size-prefixed FlatBuffer bytes.
func SourceNoteFromBytes(data []byte) (*SourceNote, error) {
	fbs := generated.GetSizePrefixedRootAsSourceNote(data, 0)
	return SourceNoteFromFbs(fbs), nil
}

// ToBytes serializes the SourceNote to size-prefixed FlatBuffer bytes.
func (o *SourceNote) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the SourceNote into a FlatBuffer builder and returns the offset.
func (o *SourceNote) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var authoredByOffset flatbuffers.UOffsetT
	if o.AuthoredBy != nil {
		authoredByOffset = builder.CreateString(*o.AuthoredBy)
	}
	var documentCidOffset flatbuffers.UOffsetT
	if o.DocumentCid != nil {
		documentCidOffset = o.DocumentCid.SerializeTo(builder)
	}
	documentIdOffset := o.DocumentId.SerializeTo(builder)
	documentSha256Offset := builder.CreateString(o.DocumentSha256)
	sourceIdOffset := builder.CreateString(o.SourceId)
	var titleOffset flatbuffers.UOffsetT
	if o.Title != nil {
		titleOffset = builder.CreateString(*o.Title)
	}
	generated.SourceNoteStart(builder)
	generated.SourceNoteAddAuthoredBy(builder, authoredByOffset)
	generated.SourceNoteAddDocumentCid(builder, documentCidOffset)
	generated.SourceNoteAddDocumentId(builder, documentIdOffset)
	generated.SourceNoteAddDocumentSha256(builder, documentSha256Offset)
	generated.SourceNoteAddPublishedAt(builder, o.PublishedAt)
	generated.SourceNoteAddSourceId(builder, sourceIdOffset)
	generated.SourceNoteAddTitle(builder, titleOffset)
	return generated.SourceNoteEnd(builder)
}
