// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

import * as flatbuffers from 'flatbuffers/js/flatbuffers';
import { RequestContext } from '../../request_context';
import { Inbox as FbsInbox, InboxT as Inbox } from '../../types/generated/inbox';
import { ObjectId as FbsObjectId, ObjectIdT as ObjectId } from '../../types/generated/object-id';

/**
 * Fetch the contents of the specified inbox folder
 *
 * @param ctx - A request context object
 * @param folder - The name of the folder to fetch
 * @returns The contents of the inbox folder
 */
export async function fetch(
  ctx: RequestContext,
  folder: string
): Promise<Inbox> {
  let path = '/v1/api/ulv2/inbox/:folder';
  path = path.replace(':folder', folder.toString());

  const params: [string, string][] = [];
  const headers: Record<string, string> = {};

  const res = await ctx.get(path, params, headers);
  const buf = new flatbuffers.ByteBuffer(res);
  buf.setPosition(buf.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  const fbs = FbsInbox.getRootAsInbox(buf);
  return fbs.unpack();
}

/**
 * Clear the status of all notifications in the specified folder
 *
 * @param ctx - A request context object
 * @param folder - The name of the folder to clear
 */
export async function clearAllStatus(
  ctx: RequestContext,
  folder: string
): Promise<void> {
  let path = '/v1/api/ulv2/inbox/:folder';
  path = path.replace(':folder', folder.toString());

  const params: [string, string][] = [];
  const headers: Record<string, string> = {};

  await ctx.delete(path, params, headers);
}

/**
 * Set the status of a notification in the specified folder
 *
 * @param ctx - A request context object
 * @param folder - The name of the folder to set the status in
 * @param id - The ID of the notification to set the status for
 * @param status - The status to set for the notification
 */
export async function setStatus(
  ctx: RequestContext,
  folder: string,
  id: ObjectId,
  status: number
): Promise<void> {
  let path = '/v1/api/ulv2/inbox/:folder/:id/status/:status';
  path = path.replace(':folder', folder.toString());
  path = path.replace(':id', id.toString());
  path = path.replace(':status', status.toString());

  const params: [string, string][] = [];
  const headers: Record<string, string> = {};

  let body: Uint8Array | null = null;
  body = null;
  await ctx.post(path, body, 'text/plain', params, headers);
}

/**
 * Clear the status of a notification in the specified folder
 *
 * @param ctx - A request context object
 * @param folder - The name of the folder to clear the status in
 * @param id - The ID of the notification to clear the status for
 */
export async function clearStatus(
  ctx: RequestContext,
  folder: string,
  id: ObjectId
): Promise<void> {
  let path = '/v1/api/ulv2/inbox/:folder/:id';
  path = path.replace(':folder', folder.toString());
  path = path.replace(':id', id.toString());

  const params: [string, string][] = [];
  const headers: Record<string, string> = {};

  await ctx.delete(path, params, headers);
}
