[package]
name = "ulsdk"
version = "0.5.0"
edition = "2021"
license = "LicenseRef-Proprietary"

[dependencies]
base64 = { workspace = true }
bitflags = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
flatbuffers = { workspace = true }
geo-types = { workspace = true }
hex = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_ini = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features=["js"] }
strum = { workspace = true }
strum_macros = { workspace = true }

[target.'cfg(not(target_arch ="wasm32"))'.dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
dirs = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
ed25519-dalek = { workspace = true }

