# Copyright (c), CommunityLogiq Software
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT

from dataclasses import dataclass
from enum import Enum
from flatbuffers.table import Table
from flatbuffers.builder import Builder
from flatbuffers.util import RemoveSizePrefix
from typing import Union, List, Optional, Tuple
import sys
if sys.version_info.minor < 11:
    from typing_extensions import Self
else:
    from typing import Self
import uuid
from .id import (
    B2cId,
    ColumnGroupId,
    ContentId,
    DataStateId,
    GenericId,
    GraphNodeId,
    ObjectId,
    ObjectNamespace,
    PinnedObjectId,
    StreamId,
)
from .generated.B2cId import B2cId as FbsB2cId
from .generated.ColumnGroupId import ColumnGroupId as FbsColumnGroupId
from .generated.ContentId import ContentId as FbsContentId
from .generated.DataStateId import DataStateId as FbsDataStateId
from .generated.DocumentField import DocumentField as FbsDocumentField
from .generated.GenericId import GenericId as FbsGenericId
from .generated.GovernedDocument import GovernedDocument as FbsGovernedDocument
from .generated.GraphNodeId import GraphNodeId as FbsGraphNodeId
from .generated.ObjectId import ObjectId as FbsObjectId
from .generated.PinnedObjectId import PinnedObjectId as FbsPinnedObjectId
from .generated.StreamId import StreamId as FbsStreamId


@dataclass
class DocumentField:
    """ One name and value a document kind lists or filters on. A name may repeat
     (a source declaration carries one `class` per class it satisfies); values
     are text, since nothing sorts or compares them in a registry query.
    """

    name: "str"

    value: Optional["str"]

    @classmethod
    def from_fbs(cls, o: FbsDocumentField) -> Self:
        name_str = o.Name()
        assert name_str is not None
        name = name_str.decode('utf-8')
        value = None
        value_str = o.Value()
        if value_str is not None:
            value = value_str.decode('utf-8')
        return cls(name, value)

    @classmethod
    def from_bytes(cls, data: bytes) -> Self:
        deprefixed = RemoveSizePrefix(data, 0)
        o = FbsDocumentField.GetRootAs(deprefixed[0], deprefixed[1])
        return cls.from_fbs(o)

    def serialize_to(self, builder: Builder) -> int:
        from .generated.DocumentField import (
            Start,
            AddName,
            AddValue,
            End,
        )
        name_offset = builder.CreateString(self.name)
        value_offset = None
        if self.value is not None:
            value_offset = builder.CreateString(self.value)

        Start(builder)
        AddName(builder, name_offset)
        if value_offset is not None:
            AddValue(builder, value_offset)
        return End(builder)

    def to_bytes(self) -> bytes:
        builder = Builder(0)
        offset = self.serialize_to(builder)
        builder.FinishSizePrefixed(offset)
        return builder.Output()

    @classmethod
    def make_default(cls) -> Self:
        name = ""
        value = ""
        return cls(name, value)

    def __eq__(self, other) -> bool:
        eq = True
        eq = eq and self.name == other.name
        eq = eq and self.value == other.value

        return eq

@dataclass
class GovernedDocument:
    """ A governed document of any kind cortext keeps: a skill, a source note, an
     exploration's program, a KPI spec, a source declaration. One platform type
     for all of them, so a new kind is a cortext declaration rather than a
     schema, a registry spec and a rebuild (libs/uldatacatalog/src/registry/
     documents.design.md).

     The object is a reference, like every governed kind: the document is a
     Drive file named here by id, content revision and sha256, and the fields a
     reader lists on are projected once per revision into the `documents`
     registry (registry.fbs), so nothing on a read path opens the document.
    """

    # The principal whose write this revision is (oid).
    authored_by: Optional["str"]

    # That file's content revision at this write.
    document_cid: Optional["ContentId"]

    # The Drive file object holding the document.
    document_id: "ObjectId"

    # sha256 (hex) of the document bytes; the projector verifies it.
    document_sha256: "str"

    # What the kind lists and filters on, written by its door from the
    # document.
    fields: Optional["List[DocumentField]"]

    # Unique within the kind, qualified when the kind is namespaced; the
    # object id derives from the kind and the key.
    key: "str"

    # What kind of document this is ("skill", "kpi-spec", ...).
    kind: "str"

    # The key's namespace ("ul" when the key has no prefix), empty for a
    # kind that is not namespaced.
    namespace: Optional["str"]

    # When this revision was published, ms since the epoch (UTC).
    published_at: "int"

    # The one line a listing shows, when the kind has one.
    title: Optional["str"]

    @classmethod
    def from_fbs(cls, o: FbsGovernedDocument) -> Self:
        authored_by = None
        authored_by_str = o.AuthoredBy()
        if authored_by_str is not None:
            authored_by = authored_by_str.decode('utf-8')
        document_cid = None
        document_cid_obj = o.DocumentCid()
        if document_cid_obj is not None:
            document_cid = ContentId.from_fbs(document_cid_obj)
        document_id_obj = o.DocumentId()
        if document_id_obj is not None:
            document_id = ObjectId.from_fbs(document_id_obj)
        else:
            raise ValueError("DocumentId is required")
        document_sha256_str = o.DocumentSha256()
        assert document_sha256_str is not None
        document_sha256 = document_sha256_str.decode('utf-8')
        fields = list()
        if not o.FieldsIsNone():
            for i in range(o.FieldsLength()):
                fields_val = None
                fields_obj = o.Fields(i)
                if fields_obj is not None:
                    fields_val = DocumentField.from_fbs(fields_obj)
                fields.append(fields_val)
        key_str = o.Key()
        assert key_str is not None
        key = key_str.decode('utf-8')
        kind_str = o.Kind()
        assert kind_str is not None
        kind = kind_str.decode('utf-8')
        namespace = None
        namespace_str = o.Namespace()
        if namespace_str is not None:
            namespace = namespace_str.decode('utf-8')
        published_at = o.PublishedAt()
        title = None
        title_str = o.Title()
        if title_str is not None:
            title = title_str.decode('utf-8')
        return cls(authored_by, document_cid, document_id, document_sha256, fields, key, kind, namespace, published_at, title)

    @classmethod
    def from_bytes(cls, data: bytes) -> Self:
        deprefixed = RemoveSizePrefix(data, 0)
        o = FbsGovernedDocument.GetRootAs(deprefixed[0], deprefixed[1])
        return cls.from_fbs(o)

    def serialize_to(self, builder: Builder) -> int:
        from .generated.GovernedDocument import (
            Start,
            AddAuthoredBy,
            AddDocumentCid,
            AddDocumentId,
            AddDocumentSha256,
            AddFields,
            StartFieldsVector,
            AddKey,
            AddKind,
            AddNamespace,
            AddPublishedAt,
            AddTitle,
            End,
        )
        authored_by_offset = None
        if self.authored_by is not None:
            authored_by_offset = builder.CreateString(self.authored_by)
        document_cid_offset = None
        if self.document_cid is not None:
            document_cid_offset = self.document_cid.serialize_to(builder)
        document_id_offset = self.document_id.serialize_to(builder)
        document_sha256_offset = builder.CreateString(self.document_sha256)
        fields_offset = None
        if self.fields is not None:
            fields_offsets = list()
            for value in self.fields:
                fields_offsets.append(value.serialize_to(builder))
            StartFieldsVector(builder, len(self.fields))
            for i in reversed(range(len(self.fields))):
                builder.PrependUOffsetTRelative(fields_offsets[i])
            fields_offset = builder.EndVector()
        key_offset = builder.CreateString(self.key)
        kind_offset = builder.CreateString(self.kind)
        namespace_offset = None
        if self.namespace is not None:
            namespace_offset = builder.CreateString(self.namespace)
        title_offset = None
        if self.title is not None:
            title_offset = builder.CreateString(self.title)

        Start(builder)
        if authored_by_offset is not None:
            AddAuthoredBy(builder, authored_by_offset)
        if document_cid_offset is not None:
            AddDocumentCid(builder, document_cid_offset)
        AddDocumentId(builder, document_id_offset)
        AddDocumentSha256(builder, document_sha256_offset)
        if fields_offset is not None:
            AddFields(builder, fields_offset)
        AddKey(builder, key_offset)
        AddKind(builder, kind_offset)
        if namespace_offset is not None:
            AddNamespace(builder, namespace_offset)
        AddPublishedAt(builder, self.published_at)
        if title_offset is not None:
            AddTitle(builder, title_offset)
        return End(builder)

    def to_bytes(self) -> bytes:
        builder = Builder(0)
        offset = self.serialize_to(builder)
        builder.FinishSizePrefixed(offset)
        return builder.Output()

    @classmethod
    def make_default(cls) -> Self:
        authored_by = ""
        document_cid = ContentId.make_default()
        document_id = ObjectId.make_default()
        document_sha256 = ""
        fields = []
        key = ""
        kind = ""
        namespace = ""
        published_at = 0
        title = ""
        return cls(authored_by, document_cid, document_id, document_sha256, fields, key, kind, namespace, published_at, title)

    def __eq__(self, other) -> bool:
        eq = True
        eq = eq and self.authored_by == other.authored_by
        eq = eq and self.document_cid == other.document_cid
        eq = eq and self.document_id == other.document_id
        eq = eq and self.document_sha256 == other.document_sha256
        self_fields = self.fields
        other_fields = other.fields
        if self_fields is not None and other_fields is not None:
            if len(self_fields) != len(other_fields):
                return False
            for i in range(len(self_fields)):
                eq = eq and self_fields[i] == other_fields[i]
        elif self_fields is not None and other_fields is None:
            return False
        elif self_fields is None and other_fields is not None:
            return False
        eq = eq and self.key == other.key
        eq = eq and self.kind == other.kind
        eq = eq and self.namespace == other.namespace
        eq = eq and self.published_at == other.published_at
        eq = eq and self.title == other.title

        return eq
