# Copyright (c), CommunityLogiq Software
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT

from dataclasses import dataclass
from enum import Enum
from flatbuffers.table import Table
from flatbuffers.builder import Builder
from flatbuffers.util import RemoveSizePrefix
from typing import Union, List, Optional, Tuple
import sys
if sys.version_info.minor < 11:
    from typing_extensions import Self
else:
    from typing import Self
import uuid
from .id import (
    B2cId,
    ColumnGroupId,
    ContentId,
    DataStateId,
    GenericId,
    GraphNodeId,
    ObjectId,
    ObjectNamespace,
    PinnedObjectId,
    StreamId,
)
from .generated.B2cId import B2cId as FbsB2cId
from .generated.ColumnGroupId import ColumnGroupId as FbsColumnGroupId
from .generated.ContentId import ContentId as FbsContentId
from .generated.DataStateId import DataStateId as FbsDataStateId
from .generated.GenericId import GenericId as FbsGenericId
from .generated.GraphNodeId import GraphNodeId as FbsGraphNodeId
from .generated.ModelManifest import ModelManifest as FbsModelManifest
from .generated.ObjectId import ObjectId as FbsObjectId
from .generated.PinnedObjectId import PinnedObjectId as FbsPinnedObjectId
from .generated.StreamId import StreamId as FbsStreamId

class ModelTier(Enum):
    Bronze = 0
    Silver = 1
    Gold = 2


@dataclass
class ModelManifest:
    """ A registered model, as the cortext model registry (n5) stores it: one
     governed object per model, homed in the `.models` system directory, with
     an ACL the owner controls and the platform's own revision history.

     The object is a *reference*: the authored manifest.yaml lives in Drive as
     its own file and is named here by id, content revision and sha256. The
     fields a reader queries on (inputs, outputs, KPIs, ...) are projected once
     per source revision into the `models` registry (registry.fbs), so nothing
     on a read path opens the YAML. `silver` and `sources` are JSON documents
     the registry records and round-trips whole (never authored by the caller).
     The runnable-bundle pin is duplicated out of `silver` into the typed
     `bundle` / `bundle_cid` fields so the runner resolves it without parsing.

     Schema baseline. This reference shape replaced the embedded-YAML
     `ModelManifest` without a compatible evolution (the `manifest` field
     changed type and `tier` took a field id ahead of `bundle`). Objects
     written in the old shape are not readable and are re-ingested, not
     migrated; a spec version bump on the `models` registry accompanies any
     further change to the projected fields.
    """

    # The registering principal (oid).
    authored_by: Optional["str"]

    # The silver archive's Drive file object, the runnable bundle.
    bundle: Optional["ObjectId"]

    # That archive's content revision at registration.
    bundle_cid: Optional["ContentId"]

    # The Drive file object holding manifest.yaml as authored.
    manifest: "ObjectId"

    # That file's content revision at registration.
    manifest_cid: Optional["ContentId"]

    # sha256 (hex) of the manifest bytes; the projector verifies it.
    manifest_sha256: "str"

    # The model's stable identity (manifest `id`); the object id is derived
    # deterministically from it, so a re-drop revises the same object.
    model_id: "str"

    # JSON SilverRecord; recorded by model ingest, refused if authored.
    silver: Optional["str"]

    # JSON [SourceSpec] from the bundle's datacatalog.yaml.
    sources: Optional["str"]

    # The lifecycle tier; set by the registry, never authored.
    tier: "ModelTier"

    @classmethod
    def from_fbs(cls, o: FbsModelManifest) -> Self:
        authored_by = None
        authored_by_str = o.AuthoredBy()
        if authored_by_str is not None:
            authored_by = authored_by_str.decode('utf-8')
        bundle = None
        bundle_obj = o.Bundle()
        if bundle_obj is not None:
            bundle = ObjectId.from_fbs(bundle_obj)
        bundle_cid = None
        bundle_cid_obj = o.BundleCid()
        if bundle_cid_obj is not None:
            bundle_cid = ContentId.from_fbs(bundle_cid_obj)
        manifest_obj = o.Manifest()
        if manifest_obj is not None:
            manifest = ObjectId.from_fbs(manifest_obj)
        else:
            raise ValueError("Manifest is required")
        manifest_cid = None
        manifest_cid_obj = o.ManifestCid()
        if manifest_cid_obj is not None:
            manifest_cid = ContentId.from_fbs(manifest_cid_obj)
        manifest_sha256_str = o.ManifestSha256()
        assert manifest_sha256_str is not None
        manifest_sha256 = manifest_sha256_str.decode('utf-8')
        model_id_str = o.ModelId()
        assert model_id_str is not None
        model_id = model_id_str.decode('utf-8')
        silver = None
        silver_str = o.Silver()
        if silver_str is not None:
            silver = silver_str.decode('utf-8')
        sources = None
        sources_str = o.Sources()
        if sources_str is not None:
            sources = sources_str.decode('utf-8')
        tier = ModelTier(o.Tier())
        return cls(authored_by, bundle, bundle_cid, manifest, manifest_cid, manifest_sha256, model_id, silver, sources, tier)

    @classmethod
    def from_bytes(cls, data: bytes) -> Self:
        deprefixed = RemoveSizePrefix(data, 0)
        o = FbsModelManifest.GetRootAs(deprefixed[0], deprefixed[1])
        return cls.from_fbs(o)

    def serialize_to(self, builder: Builder) -> int:
        from .generated.ModelManifest import (
            Start,
            AddAuthoredBy,
            AddBundle,
            AddBundleCid,
            AddManifest,
            AddManifestCid,
            AddManifestSha256,
            AddModelId,
            AddSilver,
            AddSources,
            AddTier,
            End,
        )
        authored_by_offset = None
        if self.authored_by is not None:
            authored_by_offset = builder.CreateString(self.authored_by)
        bundle_offset = None
        if self.bundle is not None:
            bundle_offset = self.bundle.serialize_to(builder)
        bundle_cid_offset = None
        if self.bundle_cid is not None:
            bundle_cid_offset = self.bundle_cid.serialize_to(builder)
        manifest_offset = self.manifest.serialize_to(builder)
        manifest_cid_offset = None
        if self.manifest_cid is not None:
            manifest_cid_offset = self.manifest_cid.serialize_to(builder)
        manifest_sha256_offset = builder.CreateString(self.manifest_sha256)
        model_id_offset = builder.CreateString(self.model_id)
        silver_offset = None
        if self.silver is not None:
            silver_offset = builder.CreateString(self.silver)
        sources_offset = None
        if self.sources is not None:
            sources_offset = builder.CreateString(self.sources)

        Start(builder)
        if authored_by_offset is not None:
            AddAuthoredBy(builder, authored_by_offset)
        if bundle_offset is not None:
            AddBundle(builder, bundle_offset)
        if bundle_cid_offset is not None:
            AddBundleCid(builder, bundle_cid_offset)
        AddManifest(builder, manifest_offset)
        if manifest_cid_offset is not None:
            AddManifestCid(builder, manifest_cid_offset)
        AddManifestSha256(builder, manifest_sha256_offset)
        AddModelId(builder, model_id_offset)
        if silver_offset is not None:
            AddSilver(builder, silver_offset)
        if sources_offset is not None:
            AddSources(builder, sources_offset)
        AddTier(builder, self.tier.value)
        return End(builder)

    def to_bytes(self) -> bytes:
        builder = Builder(0)
        offset = self.serialize_to(builder)
        builder.FinishSizePrefixed(offset)
        return builder.Output()

    @classmethod
    def make_default(cls) -> Self:
        authored_by = ""
        bundle = ObjectId.make_default()
        bundle_cid = ContentId.make_default()
        manifest = ObjectId.make_default()
        manifest_cid = ContentId.make_default()
        manifest_sha256 = ""
        model_id = ""
        silver = ""
        sources = ""
        tier = ModelTier(0)
        return cls(authored_by, bundle, bundle_cid, manifest, manifest_cid, manifest_sha256, model_id, silver, sources, tier)

    def __eq__(self, other) -> bool:
        eq = True
        eq = eq and self.authored_by == other.authored_by
        eq = eq and self.bundle == other.bundle
        eq = eq and self.bundle_cid == other.bundle_cid
        eq = eq and self.manifest == other.manifest
        eq = eq and self.manifest_cid == other.manifest_cid
        eq = eq and self.manifest_sha256 == other.manifest_sha256
        eq = eq and self.model_id == other.model_id
        eq = eq and self.silver == other.silver
        eq = eq and self.sources == other.sources
        eq = eq and self.tier == other.tier

        return eq
