// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class ChangeSet {
    com.urbanlogiq.ulsdk.types.Attr[] _attributes;
    public com.urbanlogiq.ulsdk.types.Attr[] getAttributes() {
        return this._attributes;
    }
    public void setAttributes(com.urbanlogiq.ulsdk.types.Attr[] value) {
        this._attributes = value;
    }

    com.urbanlogiq.ulsdk.types.ChangeOpEntry[] _ops;
    public com.urbanlogiq.ulsdk.types.ChangeOpEntry[] getOps() {
        return this._ops;
    }
    public void setOps(com.urbanlogiq.ulsdk.types.ChangeOpEntry[] value) {
        this._ops = value;
    }

    com.urbanlogiq.ulsdk.types.ContentId _revision;
    public com.urbanlogiq.ulsdk.types.ContentId getRevision() {
        return this._revision;
    }
    public void setRevision(com.urbanlogiq.ulsdk.types.ContentId value) {
        this._revision = value;
    }

    long _when;
    public long getWhen() {
        return this._when;
    }
    public void setWhen(long value) {
        this._when = value;
    }

    com.urbanlogiq.ulsdk.types.B2cId _who;
    public com.urbanlogiq.ulsdk.types.B2cId getWho() {
        return this._who;
    }
    public void setWho(com.urbanlogiq.ulsdk.types.B2cId value) {
        this._who = value;
    }

    public ChangeSet(com.urbanlogiq.ulsdk.types.generated.ChangeSet o) {
        if (o.attributesVector() != null) {
            com.urbanlogiq.ulsdk.types.Attr[] attributes = new com.urbanlogiq.ulsdk.types.Attr[o.attributesLength()];
            for (int i = 0; i < o.attributesLength(); i++) {
                com.urbanlogiq.ulsdk.types.Attr attributesValue = null;
                if (o.attributes(i) != null) {
                    attributesValue = new com.urbanlogiq.ulsdk.types.Attr(o.attributes(i));
                }
                attributes[i] = attributesValue;
            }
            this._attributes = attributes;
        }
        com.urbanlogiq.ulsdk.types.ChangeOpEntry[] ops = new com.urbanlogiq.ulsdk.types.ChangeOpEntry[o.opsLength()];
        for (int i = 0; i < o.opsLength(); i++) {
            com.urbanlogiq.ulsdk.types.ChangeOpEntry opsValue = null;
            if (o.ops(i) != null) {
                opsValue = new com.urbanlogiq.ulsdk.types.ChangeOpEntry(o.ops(i));
            }
            ops[i] = opsValue;
        }
        this._ops = ops;
        this._revision = new com.urbanlogiq.ulsdk.types.ContentId(o.revision());
        this._when = o.when();
        this._who = new com.urbanlogiq.ulsdk.types.B2cId(o.who());
    }

    public ChangeSet(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.ChangeSet.getRootAsChangeSet(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        Integer attributesOffset = null;
        if (this._attributes != null) {
            int[] attributesOffsets = new int[this._attributes.length];;
            for (int i = 0; i < this._attributes.length; i++) {
                attributesOffsets[i] = this._attributes[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.ChangeSet.startAttributesVector(builder, this._attributes.length);
            for (int i = attributesOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(attributesOffsets[i]);
            }
            attributesOffset = builder.endVector();
        }
        int[] opsOffsets = new int[this._ops.length];;
        for (int i = 0; i < this._ops.length; i++) {
            opsOffsets[i] = this._ops[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.startOpsVector(builder, this._ops.length);
        for (int i = opsOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(opsOffsets[i]);
        }
        int opsOffset = builder.endVector();
        int revisionOffset = this._revision.serializeTo(builder);
        int whoOffset = this._who.serializeTo(builder);
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.startChangeSet(builder);
        if (attributesOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.ChangeSet.addAttributes(builder, attributesOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.addOps(builder, opsOffset);
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.addRevision(builder, revisionOffset);
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.addWhen(builder, this._when);
        com.urbanlogiq.ulsdk.types.generated.ChangeSet.addWho(builder, whoOffset);
        return com.urbanlogiq.ulsdk.types.generated.ChangeSet.endChangeSet(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public ChangeSet() {
        this._attributes = new com.urbanlogiq.ulsdk.types.Attr[0];
        this._ops = new com.urbanlogiq.ulsdk.types.ChangeOpEntry[0];
        this._revision = new com.urbanlogiq.ulsdk.types.ContentId();
        this._who = new com.urbanlogiq.ulsdk.types.B2cId();
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}