// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class ConflictAction {
    Object _value;

    public ConflictAction(Object value) {
        if (!(value instanceof com.urbanlogiq.ulsdk.types.InsertConflicting)
            && !(value instanceof com.urbanlogiq.ulsdk.types.DoNothing)
            && !(value instanceof com.urbanlogiq.ulsdk.types.DoUpdate)) {
            throw new com.urbanlogiq.ulsdk.InvalidVariantException("ConflictAction", value);
        }

        this._value = value;
    }

    public com.urbanlogiq.ulsdk.Pair<Integer, Byte> serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        if (this._value instanceof com.urbanlogiq.ulsdk.types.InsertConflicting) {
            com.urbanlogiq.ulsdk.types.InsertConflicting o = (com.urbanlogiq.ulsdk.types.InsertConflicting)this._value;
            int offset = o.serializeTo(builder);
            byte ty = com.urbanlogiq.ulsdk.types.generated.ConflictAction.InsertConflicting;
            return new com.urbanlogiq.ulsdk.Pair<Integer, Byte>(offset, ty);
        } else if (this._value instanceof com.urbanlogiq.ulsdk.types.DoNothing) {
            com.urbanlogiq.ulsdk.types.DoNothing o = (com.urbanlogiq.ulsdk.types.DoNothing)this._value;
            int offset = o.serializeTo(builder);
            byte ty = com.urbanlogiq.ulsdk.types.generated.ConflictAction.DoNothing;
            return new com.urbanlogiq.ulsdk.Pair<Integer, Byte>(offset, ty);
        } else if (this._value instanceof com.urbanlogiq.ulsdk.types.DoUpdate) {
            com.urbanlogiq.ulsdk.types.DoUpdate o = (com.urbanlogiq.ulsdk.types.DoUpdate)this._value;
            int offset = o.serializeTo(builder);
            byte ty = com.urbanlogiq.ulsdk.types.generated.ConflictAction.DoUpdate;
            return new com.urbanlogiq.ulsdk.Pair<Integer, Byte>(offset, ty);
        } else {
            throw new RuntimeException("unreachable variant");
        }
    }

    public ConflictAction(com.google.flatbuffers.Table o, byte ty) {
        if (o == null) {
            throw new NullPointerException();
        }

        if (ty == com.urbanlogiq.ulsdk.types.generated.ConflictAction.InsertConflicting) {
            this._value = new com.urbanlogiq.ulsdk.types.InsertConflicting((com.urbanlogiq.ulsdk.types.generated.InsertConflicting)o);
        } else if (ty == com.urbanlogiq.ulsdk.types.generated.ConflictAction.DoNothing) {
            this._value = new com.urbanlogiq.ulsdk.types.DoNothing((com.urbanlogiq.ulsdk.types.generated.DoNothing)o);
        } else if (ty == com.urbanlogiq.ulsdk.types.generated.ConflictAction.DoUpdate) {
            this._value = new com.urbanlogiq.ulsdk.types.DoUpdate((com.urbanlogiq.ulsdk.types.generated.DoUpdate)o);
        }
    }

    public ConflictAction() {
        this(new com.urbanlogiq.ulsdk.types.InsertConflicting());
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}