// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

/**
 *  This variant indicates that if there is a conflict, the action is to "do
 *  nothing", or to skip the conflicting rows.
 */
public final class DoNothing {
    public DoNothing(com.urbanlogiq.ulsdk.types.generated.DoNothing o) {
    }

    public DoNothing(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.DoNothing.getRootAsDoNothing(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        com.urbanlogiq.ulsdk.types.generated.DoNothing.startDoNothing(builder);
        return com.urbanlogiq.ulsdk.types.generated.DoNothing.endDoNothing(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public DoNothing() {
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}