// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class FixedSizeList {
    /**
     *  Number of list items per value
     */
    int _listSize;
    public int getListSize() {
        return this._listSize;
    }
    public void setListSize(int value) {
        this._listSize = value;
    }

    public FixedSizeList(com.urbanlogiq.ulsdk.types.generated.FixedSizeList o) {
        this._listSize = o.listSize();
    }

    public FixedSizeList(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.FixedSizeList.getRootAsFixedSizeList(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        com.urbanlogiq.ulsdk.types.generated.FixedSizeList.startFixedSizeList(builder);
        com.urbanlogiq.ulsdk.types.generated.FixedSizeList.addListSize(builder, this._listSize);
        return com.urbanlogiq.ulsdk.types.generated.FixedSizeList.endFixedSizeList(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public FixedSizeList() {
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}