// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class Job {
    com.urbanlogiq.ulsdk.types.Attr[] _attributes;
    public com.urbanlogiq.ulsdk.types.Attr[] getAttributes() {
        return this._attributes;
    }
    public void setAttributes(com.urbanlogiq.ulsdk.types.Attr[] value) {
        this._attributes = value;
    }

    int[] _errorTys;
    public int[] getErrorTys() {
        return this._errorTys;
    }
    public void setErrorTys(int[] value) {
        this._errorTys = value;
    }

    /**
     *  Parameters verbatim from the RunSpec
     */
    com.urbanlogiq.ulsdk.types.TaskParameter[] _params;
    public com.urbanlogiq.ulsdk.types.TaskParameter[] getParams() {
        return this._params;
    }
    public void setParams(com.urbanlogiq.ulsdk.types.TaskParameter[] value) {
        this._params = value;
    }

    /**
     *  Is the job complete?
     */
    byte _status;
    public byte getStatus() {
        return this._status;
    }
    public void setStatus(byte value) {
        this._status = value;
    }

    /**
     *  A list of all the tasks that constitute this job.
     */
    com.urbanlogiq.ulsdk.types.Task[] _tasks;
    public com.urbanlogiq.ulsdk.types.Task[] getTasks() {
        return this._tasks;
    }
    public void setTasks(com.urbanlogiq.ulsdk.types.Task[] value) {
        this._tasks = value;
    }

    /**
     *  User ID who created this job.
     */
    com.urbanlogiq.ulsdk.types.ObjectId _userId;
    public com.urbanlogiq.ulsdk.types.ObjectId getUserId() {
        return this._userId;
    }
    public void setUserId(com.urbanlogiq.ulsdk.types.ObjectId value) {
        this._userId = value;
    }

    public Job(com.urbanlogiq.ulsdk.types.generated.Job o) {
        if (o.attributesVector() != null) {
            com.urbanlogiq.ulsdk.types.Attr[] attributes = new com.urbanlogiq.ulsdk.types.Attr[o.attributesLength()];
            for (int i = 0; i < o.attributesLength(); i++) {
                com.urbanlogiq.ulsdk.types.Attr attributesValue = null;
                if (o.attributes(i) != null) {
                    attributesValue = new com.urbanlogiq.ulsdk.types.Attr(o.attributes(i));
                }
                attributes[i] = attributesValue;
            }
            this._attributes = attributes;
        }
        if (o.errorTysVector() != null) {
            int[] errorTys = new int[o.errorTysLength()];
            for (int i = 0; i < o.errorTysLength(); i++) {
                errorTys[i] = (int)o.errorTys(i);
            }
            this._errorTys = errorTys;
        }
        com.urbanlogiq.ulsdk.types.TaskParameter[] params = new com.urbanlogiq.ulsdk.types.TaskParameter[o.paramsLength()];
        for (int i = 0; i < o.paramsLength(); i++) {
            com.urbanlogiq.ulsdk.types.TaskParameter paramsValue = null;
            if (o.params(i) != null) {
                paramsValue = new com.urbanlogiq.ulsdk.types.TaskParameter(o.params(i));
            }
            params[i] = paramsValue;
        }
        this._params = params;
        this._status = o.status();
        com.urbanlogiq.ulsdk.types.Task[] tasks = new com.urbanlogiq.ulsdk.types.Task[o.tasksLength()];
        for (int i = 0; i < o.tasksLength(); i++) {
            com.urbanlogiq.ulsdk.types.Task tasksValue = null;
            if (o.tasks(i) != null) {
                tasksValue = new com.urbanlogiq.ulsdk.types.Task(o.tasks(i));
            }
            tasks[i] = tasksValue;
        }
        this._tasks = tasks;
        this._userId = new com.urbanlogiq.ulsdk.types.ObjectId(o.userId());
    }

    public Job(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.Job.getRootAsJob(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        Integer attributesOffset = null;
        if (this._attributes != null) {
            int[] attributesOffsets = new int[this._attributes.length];;
            for (int i = 0; i < this._attributes.length; i++) {
                attributesOffsets[i] = this._attributes[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.Job.startAttributesVector(builder, this._attributes.length);
            for (int i = attributesOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(attributesOffsets[i]);
            }
            attributesOffset = builder.endVector();
        }
        Integer errorTysOffset = null;
        if (this._errorTys != null) {
            com.urbanlogiq.ulsdk.types.generated.Job.startErrorTysVector(builder, this._errorTys.length);
            for (int i = this._errorTys.length - 1; i >= 0; i--) {
                builder.addInt(this._errorTys[i]);
            }
            errorTysOffset = builder.endVector();
        }
        int[] paramsOffsets = new int[this._params.length];;
        for (int i = 0; i < this._params.length; i++) {
            paramsOffsets[i] = this._params[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.Job.startParamsVector(builder, this._params.length);
        for (int i = paramsOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(paramsOffsets[i]);
        }
        int paramsOffset = builder.endVector();
        int[] tasksOffsets = new int[this._tasks.length];;
        for (int i = 0; i < this._tasks.length; i++) {
            tasksOffsets[i] = this._tasks[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.Job.startTasksVector(builder, this._tasks.length);
        for (int i = tasksOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(tasksOffsets[i]);
        }
        int tasksOffset = builder.endVector();
        int userIdOffset = this._userId.serializeTo(builder);
        com.urbanlogiq.ulsdk.types.generated.Job.startJob(builder);
        if (attributesOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Job.addAttributes(builder, attributesOffset);
        }
        if (errorTysOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Job.addErrorTys(builder, errorTysOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.Job.addParams(builder, paramsOffset);
        com.urbanlogiq.ulsdk.types.generated.Job.addStatus(builder, this._status);
        com.urbanlogiq.ulsdk.types.generated.Job.addTasks(builder, tasksOffset);
        com.urbanlogiq.ulsdk.types.generated.Job.addUserId(builder, userIdOffset);
        return com.urbanlogiq.ulsdk.types.generated.Job.endJob(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public Job() {
        this._attributes = new com.urbanlogiq.ulsdk.types.Attr[0];
        this._errorTys = new int[0];
        this._params = new com.urbanlogiq.ulsdk.types.TaskParameter[0];
        this._tasks = new com.urbanlogiq.ulsdk.types.Task[0];
        this._userId = new com.urbanlogiq.ulsdk.types.ObjectId();
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}