// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class ListFile {
    String _mime;
    public String getMime() {
        return this._mime;
    }
    public void setMime(String value) {
        this._mime = value;
    }

    long _size;
    public long getSize() {
        return this._size;
    }
    public void setSize(long value) {
        this._size = value;
    }

    String _virus;
    public String getVirus() {
        return this._virus;
    }
    public void setVirus(String value) {
        this._virus = value;
    }

    public ListFile(com.urbanlogiq.ulsdk.types.generated.ListFile o) {
        this._mime = o.mime();
        this._size = o.size();
        if (o.virus() != null) {
            this._virus = o.virus();
        }
    }

    public ListFile(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.ListFile.getRootAsListFile(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        int mimeOffset = builder.createString(this._mime);
        Integer virusOffset = null;
        if (this._virus != null) {
            virusOffset = builder.createString(this._virus);
        }
        com.urbanlogiq.ulsdk.types.generated.ListFile.startListFile(builder);
        com.urbanlogiq.ulsdk.types.generated.ListFile.addMime(builder, mimeOffset);
        com.urbanlogiq.ulsdk.types.generated.ListFile.addSize(builder, this._size);
        if (virusOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.ListFile.addVirus(builder, virusOffset);
        }
        return com.urbanlogiq.ulsdk.types.generated.ListFile.endListFile(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public ListFile() {
        this._mime = new String();
        this._virus = new String();
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}