// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class Metadata {
    /**
     *  is to be included in the boundary selection modal
     */
    boolean _areaSelection;
    public boolean getAreaSelection() {
        return this._areaSelection;
    }
    public void setAreaSelection(boolean value) {
        this._areaSelection = value;
    }

    /**
     *  Organizational category for frontend. Defaults to DC_HIDDEN.
     */
    long _datasetCategory;
    public long getDatasetCategory() {
        return this._datasetCategory;
    }
    public void setDatasetCategory(long value) {
        this._datasetCategory = value;
    }

    String _description;
    public String getDescription() {
        return this._description;
    }
    public void setDescription(String value) {
        this._description = value;
    }

    /**
     *  Sections of fields shown in a feature's selected-state details panel, in
     *  display order, where `summary` is the hover-popup list. When absent, the
     *  details panel falls back to the summary fields.
     */
    com.urbanlogiq.ulsdk.types.DetailSection[] _detailSections;
    public com.urbanlogiq.ulsdk.types.DetailSection[] getDetailSections() {
        return this._detailSections;
    }
    public void setDetailSections(com.urbanlogiq.ulsdk.types.DetailSection[] value) {
        this._detailSections = value;
    }

    String _displayName;
    public String getDisplayName() {
        return this._displayName;
    }
    public void setDisplayName(String value) {
        this._displayName = value;
    }

    /**
     *  do not use user's viewport bounding box when fetching this stream's geometry from worldgraph
     */
    boolean _doNotFilterGeometryByViewport;
    public boolean getDoNotFilterGeometryByViewport() {
        return this._doNotFilterGeometryByViewport;
    }
    public void setDoNotFilterGeometryByViewport(boolean value) {
        this._doNotFilterGeometryByViewport = value;
    }

    int _entityTy;
    public int getEntityTy() {
        return this._entityTy;
    }
    public void setEntityTy(int value) {
        this._entityTy = value;
    }

    /**
     *  Field groupings e.g. age ranges, ethnicities or hierarchical codes like zoning and NAICS
     */
    com.urbanlogiq.ulsdk.types.UlFieldRelationship[] _fieldRelationships;
    public com.urbanlogiq.ulsdk.types.UlFieldRelationship[] getFieldRelationships() {
        return this._fieldRelationships;
    }
    public void setFieldRelationships(com.urbanlogiq.ulsdk.types.UlFieldRelationship[] value) {
        this._fieldRelationships = value;
    }

    com.urbanlogiq.ulsdk.types.UlField[] _fields;
    public com.urbanlogiq.ulsdk.types.UlField[] getFields() {
        return this._fields;
    }
    public void setFields(com.urbanlogiq.ulsdk.types.UlField[] value) {
        this._fields = value;
    }

    com.urbanlogiq.ulsdk.types.GeometrySource _geometrySource;
    public com.urbanlogiq.ulsdk.types.GeometrySource getGeometrySource() {
        return this._geometrySource;
    }
    public void setGeometrySource(com.urbanlogiq.ulsdk.types.GeometrySource value) {
        this._geometrySource = value;
    }

    /**
     *  Many geospatial datasets whose rows correspond to map locations have a
     *  column that should be used as the human-friendly display name of the location.
     *  For example, for a stream containing stores, this field might be "store_name".
     *  If the stream contains multiple rows with the same ul_node_id, then those rows
     *  should have the same value for the location_description_field.
     *  This attribute holds the index of the field in the dataset that should be
     *  used as the location description.
     */
    int _locationDescriptionField;
    public int getLocationDescriptionField() {
        return this._locationDescriptionField;
    }
    public void setLocationDescriptionField(int value) {
        this._locationDescriptionField = value;
    }

    /**
     *  Indices of fields that are "promoted to metrics"
     */
    int[] _promotedMetrics;
    public int[] getPromotedMetrics() {
        return this._promotedMetrics;
    }
    public void setPromotedMetrics(int[] value) {
        this._promotedMetrics = value;
    }

    /**
     *  An optional field that is meant to provide information to the user on
     *  where the data has come from
     */
    com.urbanlogiq.ulsdk.types.DatasetSource _source;
    public com.urbanlogiq.ulsdk.types.DatasetSource getSource() {
        return this._source;
    }
    public void setSource(com.urbanlogiq.ulsdk.types.DatasetSource value) {
        this._source = value;
    }

    int[] _summary;
    public int[] getSummary() {
        return this._summary;
    }
    public void setSummary(int[] value) {
        this._summary = value;
    }

    /**
     *  Which of the dataset's columns carries the time its rows are observed;
     *  see TimeSource. Unset on metadata written before this field existed, in
     *  which case a consumer falls back to recognising the conventional column
     *  names.
     */
    com.urbanlogiq.ulsdk.types.TimeSource _timeSource;
    public com.urbanlogiq.ulsdk.types.TimeSource getTimeSource() {
        return this._timeSource;
    }
    public void setTimeSource(com.urbanlogiq.ulsdk.types.TimeSource value) {
        this._timeSource = value;
    }

    long _updateCadence;
    public long getUpdateCadence() {
        return this._updateCadence;
    }
    public void setUpdateCadence(long value) {
        this._updateCadence = value;
    }

    /**
     *  Indices of non-numeric fields that are "visualized in Explore" — they
     *  appear as a categorical color visualization on Generic layers but, unlike
     *  promoted_metrics, do NOT create an entry in the metric catalog.
     */
    int[] _visualizeInExploreFields;
    public int[] getVisualizeInExploreFields() {
        return this._visualizeInExploreFields;
    }
    public void setVisualizeInExploreFields(int[] value) {
        this._visualizeInExploreFields = value;
    }

    public Metadata(com.urbanlogiq.ulsdk.types.generated.Metadata o) {
        this._areaSelection = o.areaSelection();
        this._datasetCategory = o.datasetCategory();
        if (o.description() != null) {
            this._description = o.description();
        }
        if (o.detailSectionsVector() != null) {
            com.urbanlogiq.ulsdk.types.DetailSection[] detailSections = new com.urbanlogiq.ulsdk.types.DetailSection[o.detailSectionsLength()];
            for (int i = 0; i < o.detailSectionsLength(); i++) {
                com.urbanlogiq.ulsdk.types.DetailSection detailSectionsValue = null;
                if (o.detailSections(i) != null) {
                    detailSectionsValue = new com.urbanlogiq.ulsdk.types.DetailSection(o.detailSections(i));
                }
                detailSections[i] = detailSectionsValue;
            }
            this._detailSections = detailSections;
        }
        if (o.displayName() != null) {
            this._displayName = o.displayName();
        }
        this._doNotFilterGeometryByViewport = o.doNotFilterGeometryByViewport();
        this._entityTy = o.entityTy();
        if (o.fieldRelationshipsVector() != null) {
            com.urbanlogiq.ulsdk.types.UlFieldRelationship[] fieldRelationships = new com.urbanlogiq.ulsdk.types.UlFieldRelationship[o.fieldRelationshipsLength()];
            for (int i = 0; i < o.fieldRelationshipsLength(); i++) {
                com.urbanlogiq.ulsdk.types.UlFieldRelationship fieldRelationshipsValue = null;
                if (o.fieldRelationships(i) != null) {
                    fieldRelationshipsValue = new com.urbanlogiq.ulsdk.types.UlFieldRelationship(o.fieldRelationships(i));
                }
                fieldRelationships[i] = fieldRelationshipsValue;
            }
            this._fieldRelationships = fieldRelationships;
        }
        if (o.fieldsVector() != null) {
            com.urbanlogiq.ulsdk.types.UlField[] fields = new com.urbanlogiq.ulsdk.types.UlField[o.fieldsLength()];
            for (int i = 0; i < o.fieldsLength(); i++) {
                com.urbanlogiq.ulsdk.types.UlField fieldsValue = null;
                if (o.fields(i) != null) {
                    fieldsValue = new com.urbanlogiq.ulsdk.types.UlField(o.fields(i));
                }
                fields[i] = fieldsValue;
            }
            this._fields = fields;
        }
        Object geometrySourceValue = null;
        var geometrySourceTy = o.geometrySourceType();
        if (geometrySourceTy == com.urbanlogiq.ulsdk.types.generated.GeometrySource.NoGeometry) {
            com.google.flatbuffers.Table geometrySourceFbsTable = o.geometrySource(new com.urbanlogiq.ulsdk.types.generated.NoGeometry());
            com.urbanlogiq.ulsdk.types.generated.NoGeometry geometrySourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.NoGeometry)geometrySourceFbsTable;
            geometrySourceValue = new com.urbanlogiq.ulsdk.types.NoGeometry(geometrySourceFbsValue);
        } else if (geometrySourceTy == com.urbanlogiq.ulsdk.types.generated.GeometrySource.DatacatalogGeometry) {
            com.google.flatbuffers.Table geometrySourceFbsTable = o.geometrySource(new com.urbanlogiq.ulsdk.types.generated.DatacatalogGeometry());
            com.urbanlogiq.ulsdk.types.generated.DatacatalogGeometry geometrySourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.DatacatalogGeometry)geometrySourceFbsTable;
            geometrySourceValue = new com.urbanlogiq.ulsdk.types.DatacatalogGeometry(geometrySourceFbsValue);
        } else if (geometrySourceTy == com.urbanlogiq.ulsdk.types.generated.GeometrySource.WorldGraphGeometry) {
            com.google.flatbuffers.Table geometrySourceFbsTable = o.geometrySource(new com.urbanlogiq.ulsdk.types.generated.WorldGraphGeometry());
            com.urbanlogiq.ulsdk.types.generated.WorldGraphGeometry geometrySourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.WorldGraphGeometry)geometrySourceFbsTable;
            geometrySourceValue = new com.urbanlogiq.ulsdk.types.WorldGraphGeometry(geometrySourceFbsValue);
        } else if (geometrySourceTy == com.urbanlogiq.ulsdk.types.generated.GeometrySource.DatacatalogLatLngGeometry) {
            com.google.flatbuffers.Table geometrySourceFbsTable = o.geometrySource(new com.urbanlogiq.ulsdk.types.generated.DatacatalogLatLngGeometry());
            com.urbanlogiq.ulsdk.types.generated.DatacatalogLatLngGeometry geometrySourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.DatacatalogLatLngGeometry)geometrySourceFbsTable;
            geometrySourceValue = new com.urbanlogiq.ulsdk.types.DatacatalogLatLngGeometry(geometrySourceFbsValue);
        }
        if (geometrySourceValue != null) {
            this._geometrySource = new com.urbanlogiq.ulsdk.types.GeometrySource(geometrySourceValue);
        }
        this._locationDescriptionField = o.locationDescriptionField();
        if (o.promotedMetricsVector() != null) {
            int[] promotedMetrics = new int[o.promotedMetricsLength()];
            for (int i = 0; i < o.promotedMetricsLength(); i++) {
                promotedMetrics[i] = (int)o.promotedMetrics(i);
            }
            this._promotedMetrics = promotedMetrics;
        }
        if (o.source() != null) {
            this._source = new com.urbanlogiq.ulsdk.types.DatasetSource(o.source());
        }
        if (o.summaryVector() != null) {
            int[] summary = new int[o.summaryLength()];
            for (int i = 0; i < o.summaryLength(); i++) {
                summary[i] = (int)o.summary(i);
            }
            this._summary = summary;
        }
        Object timeSourceValue = null;
        var timeSourceTy = o.timeSourceType();
        if (timeSourceTy == com.urbanlogiq.ulsdk.types.generated.TimeSource.NoTime) {
            com.google.flatbuffers.Table timeSourceFbsTable = o.timeSource(new com.urbanlogiq.ulsdk.types.generated.NoTime());
            com.urbanlogiq.ulsdk.types.generated.NoTime timeSourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.NoTime)timeSourceFbsTable;
            timeSourceValue = new com.urbanlogiq.ulsdk.types.NoTime(timeSourceFbsValue);
        } else if (timeSourceTy == com.urbanlogiq.ulsdk.types.generated.TimeSource.ColumnTime) {
            com.google.flatbuffers.Table timeSourceFbsTable = o.timeSource(new com.urbanlogiq.ulsdk.types.generated.ColumnTime());
            com.urbanlogiq.ulsdk.types.generated.ColumnTime timeSourceFbsValue = (com.urbanlogiq.ulsdk.types.generated.ColumnTime)timeSourceFbsTable;
            timeSourceValue = new com.urbanlogiq.ulsdk.types.ColumnTime(timeSourceFbsValue);
        }
        if (timeSourceValue != null) {
            this._timeSource = new com.urbanlogiq.ulsdk.types.TimeSource(timeSourceValue);
        }
        this._updateCadence = o.updateCadence();
        if (o.visualizeInExploreFieldsVector() != null) {
            int[] visualizeInExploreFields = new int[o.visualizeInExploreFieldsLength()];
            for (int i = 0; i < o.visualizeInExploreFieldsLength(); i++) {
                visualizeInExploreFields[i] = (int)o.visualizeInExploreFields(i);
            }
            this._visualizeInExploreFields = visualizeInExploreFields;
        }
    }

    public Metadata(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.Metadata.getRootAsMetadata(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        Integer descriptionOffset = null;
        if (this._description != null) {
            descriptionOffset = builder.createString(this._description);
        }
        Integer detailSectionsOffset = null;
        if (this._detailSections != null) {
            int[] detailSectionsOffsets = new int[this._detailSections.length];;
            for (int i = 0; i < this._detailSections.length; i++) {
                detailSectionsOffsets[i] = this._detailSections[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.Metadata.startDetailSectionsVector(builder, this._detailSections.length);
            for (int i = detailSectionsOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(detailSectionsOffsets[i]);
            }
            detailSectionsOffset = builder.endVector();
        }
        Integer displayNameOffset = null;
        if (this._displayName != null) {
            displayNameOffset = builder.createString(this._displayName);
        }
        Integer fieldRelationshipsOffset = null;
        if (this._fieldRelationships != null) {
            int[] fieldRelationshipsOffsets = new int[this._fieldRelationships.length];;
            for (int i = 0; i < this._fieldRelationships.length; i++) {
                fieldRelationshipsOffsets[i] = this._fieldRelationships[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.Metadata.startFieldRelationshipsVector(builder, this._fieldRelationships.length);
            for (int i = fieldRelationshipsOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(fieldRelationshipsOffsets[i]);
            }
            fieldRelationshipsOffset = builder.endVector();
        }
        Integer fieldsOffset = null;
        if (this._fields != null) {
            int[] fieldsOffsets = new int[this._fields.length];;
            for (int i = 0; i < this._fields.length; i++) {
                fieldsOffsets[i] = this._fields[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.Metadata.startFieldsVector(builder, this._fields.length);
            for (int i = fieldsOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(fieldsOffsets[i]);
            }
            fieldsOffset = builder.endVector();
        }
        com.urbanlogiq.ulsdk.Pair<Integer, Byte> geometrySourcePair = null;
        if (this._geometrySource != null) {
            geometrySourcePair = this._geometrySource.serializeTo(builder);
        }
        Integer promotedMetricsOffset = null;
        if (this._promotedMetrics != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.startPromotedMetricsVector(builder, this._promotedMetrics.length);
            for (int i = this._promotedMetrics.length - 1; i >= 0; i--) {
                builder.addInt(this._promotedMetrics[i]);
            }
            promotedMetricsOffset = builder.endVector();
        }
        Integer sourceOffset = null;
        if (this._source != null) {
            sourceOffset = this._source.serializeTo(builder);
        }
        Integer summaryOffset = null;
        if (this._summary != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.startSummaryVector(builder, this._summary.length);
            for (int i = this._summary.length - 1; i >= 0; i--) {
                builder.addInt(this._summary[i]);
            }
            summaryOffset = builder.endVector();
        }
        com.urbanlogiq.ulsdk.Pair<Integer, Byte> timeSourcePair = null;
        if (this._timeSource != null) {
            timeSourcePair = this._timeSource.serializeTo(builder);
        }
        Integer visualizeInExploreFieldsOffset = null;
        if (this._visualizeInExploreFields != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.startVisualizeInExploreFieldsVector(builder, this._visualizeInExploreFields.length);
            for (int i = this._visualizeInExploreFields.length - 1; i >= 0; i--) {
                builder.addInt(this._visualizeInExploreFields[i]);
            }
            visualizeInExploreFieldsOffset = builder.endVector();
        }
        com.urbanlogiq.ulsdk.types.generated.Metadata.startMetadata(builder);
        com.urbanlogiq.ulsdk.types.generated.Metadata.addAreaSelection(builder, this._areaSelection);
        com.urbanlogiq.ulsdk.types.generated.Metadata.addDatasetCategory(builder, this._datasetCategory);
        if (descriptionOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addDescription(builder, descriptionOffset);
        }
        if (detailSectionsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addDetailSections(builder, detailSectionsOffset);
        }
        if (displayNameOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addDisplayName(builder, displayNameOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.Metadata.addDoNotFilterGeometryByViewport(builder, this._doNotFilterGeometryByViewport);
        com.urbanlogiq.ulsdk.types.generated.Metadata.addEntityTy(builder, this._entityTy);
        if (fieldRelationshipsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addFieldRelationships(builder, fieldRelationshipsOffset);
        }
        if (fieldsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addFields(builder, fieldsOffset);
        }
        if (geometrySourcePair != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addGeometrySource(builder, geometrySourcePair.first());
            com.urbanlogiq.ulsdk.types.generated.Metadata.addGeometrySourceType(builder, geometrySourcePair.second());
        }
        com.urbanlogiq.ulsdk.types.generated.Metadata.addLocationDescriptionField(builder, this._locationDescriptionField);
        if (promotedMetricsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addPromotedMetrics(builder, promotedMetricsOffset);
        }
        if (sourceOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addSource(builder, sourceOffset);
        }
        if (summaryOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addSummary(builder, summaryOffset);
        }
        if (timeSourcePair != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addTimeSource(builder, timeSourcePair.first());
            com.urbanlogiq.ulsdk.types.generated.Metadata.addTimeSourceType(builder, timeSourcePair.second());
        }
        com.urbanlogiq.ulsdk.types.generated.Metadata.addUpdateCadence(builder, this._updateCadence);
        if (visualizeInExploreFieldsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Metadata.addVisualizeInExploreFields(builder, visualizeInExploreFieldsOffset);
        }
        return com.urbanlogiq.ulsdk.types.generated.Metadata.endMetadata(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public Metadata() {
        this._description = new String();
        this._detailSections = new com.urbanlogiq.ulsdk.types.DetailSection[0];
        this._displayName = new String();
        this._fieldRelationships = new com.urbanlogiq.ulsdk.types.UlFieldRelationship[0];
        this._fields = new com.urbanlogiq.ulsdk.types.UlField[0];
        this._geometrySource = new com.urbanlogiq.ulsdk.types.GeometrySource();
        this._promotedMetrics = new int[0];
        this._source = new com.urbanlogiq.ulsdk.types.DatasetSource();
        this._summary = new int[0];
        this._timeSource = new com.urbanlogiq.ulsdk.types.TimeSource();
        this._visualizeInExploreFields = new int[0];
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}