// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

/**
 *  These are stored in the flatbuffer in the Type union below
 */
public final class Null {
    public Null(com.urbanlogiq.ulsdk.types.generated.Null o) {
    }

    public Null(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.Null.getRootAsNull(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        com.urbanlogiq.ulsdk.types.generated.Null.startNull(builder);
        return com.urbanlogiq.ulsdk.types.generated.Null.endNull(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public Null() {
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}