// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class Schematic {
    com.urbanlogiq.ulsdk.types.AttributePair[] _attributes;
    public com.urbanlogiq.ulsdk.types.AttributePair[] getAttributes() {
        return this._attributes;
    }
    public void setAttributes(com.urbanlogiq.ulsdk.types.AttributePair[] value) {
        this._attributes = value;
    }

    com.urbanlogiq.ulsdk.types.Edge[] _edges;
    public com.urbanlogiq.ulsdk.types.Edge[] getEdges() {
        return this._edges;
    }
    public void setEdges(com.urbanlogiq.ulsdk.types.Edge[] value) {
        this._edges = value;
    }

    String _name;
    public String getName() {
        return this._name;
    }
    public void setName(String value) {
        this._name = value;
    }

    com.urbanlogiq.ulsdk.types.Node[] _nodes;
    public com.urbanlogiq.ulsdk.types.Node[] getNodes() {
        return this._nodes;
    }
    public void setNodes(com.urbanlogiq.ulsdk.types.Node[] value) {
        this._nodes = value;
    }

    public Schematic(com.urbanlogiq.ulsdk.types.generated.Schematic o) {
        com.urbanlogiq.ulsdk.types.AttributePair[] attributes = new com.urbanlogiq.ulsdk.types.AttributePair[o.attributesLength()];
        for (int i = 0; i < o.attributesLength(); i++) {
            com.urbanlogiq.ulsdk.types.AttributePair attributesValue = null;
            if (o.attributes(i) != null) {
                attributesValue = new com.urbanlogiq.ulsdk.types.AttributePair(o.attributes(i));
            }
            attributes[i] = attributesValue;
        }
        this._attributes = attributes;
        com.urbanlogiq.ulsdk.types.Edge[] edges = new com.urbanlogiq.ulsdk.types.Edge[o.edgesLength()];
        for (int i = 0; i < o.edgesLength(); i++) {
            com.urbanlogiq.ulsdk.types.Edge edgesValue = null;
            if (o.edges(i) != null) {
                edgesValue = new com.urbanlogiq.ulsdk.types.Edge(o.edges(i));
            }
            edges[i] = edgesValue;
        }
        this._edges = edges;
        if (o.name() != null) {
            this._name = o.name();
        }
        com.urbanlogiq.ulsdk.types.Node[] nodes = new com.urbanlogiq.ulsdk.types.Node[o.nodesLength()];
        for (int i = 0; i < o.nodesLength(); i++) {
            com.urbanlogiq.ulsdk.types.Node nodesValue = null;
            if (o.nodes(i) != null) {
                nodesValue = new com.urbanlogiq.ulsdk.types.Node(o.nodes(i));
            }
            nodes[i] = nodesValue;
        }
        this._nodes = nodes;
    }

    public Schematic(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.Schematic.getRootAsSchematic(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        int[] attributesOffsets = new int[this._attributes.length];;
        for (int i = 0; i < this._attributes.length; i++) {
            attributesOffsets[i] = this._attributes[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.Schematic.startAttributesVector(builder, this._attributes.length);
        for (int i = attributesOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(attributesOffsets[i]);
        }
        int attributesOffset = builder.endVector();
        int[] edgesOffsets = new int[this._edges.length];;
        for (int i = 0; i < this._edges.length; i++) {
            edgesOffsets[i] = this._edges[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.Schematic.startEdgesVector(builder, this._edges.length);
        for (int i = edgesOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(edgesOffsets[i]);
        }
        int edgesOffset = builder.endVector();
        Integer nameOffset = null;
        if (this._name != null) {
            nameOffset = builder.createString(this._name);
        }
        int[] nodesOffsets = new int[this._nodes.length];;
        for (int i = 0; i < this._nodes.length; i++) {
            nodesOffsets[i] = this._nodes[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.Schematic.startNodesVector(builder, this._nodes.length);
        for (int i = nodesOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(nodesOffsets[i]);
        }
        int nodesOffset = builder.endVector();
        com.urbanlogiq.ulsdk.types.generated.Schematic.startSchematic(builder);
        com.urbanlogiq.ulsdk.types.generated.Schematic.addAttributes(builder, attributesOffset);
        com.urbanlogiq.ulsdk.types.generated.Schematic.addEdges(builder, edgesOffset);
        if (nameOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.Schematic.addName(builder, nameOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.Schematic.addNodes(builder, nodesOffset);
        return com.urbanlogiq.ulsdk.types.generated.Schematic.endSchematic(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public Schematic() {
        this._attributes = new com.urbanlogiq.ulsdk.types.AttributePair[0];
        this._edges = new com.urbanlogiq.ulsdk.types.Edge[0];
        this._name = new String();
        this._nodes = new com.urbanlogiq.ulsdk.types.Node[0];
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}