// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

/**
 *  SetExprs represent the expressions used as part of an UPDATE-type operation
 */
public final class SetExpr {
    /**
     *  The target column name. Since SET targets always refer to the target table,
     *  we only need to name the column as a string.
     */
    String _col;
    public String getCol() {
        return this._col;
    }
    public void setCol(String value) {
        this._col = value;
    }

    /**
     *  This is the expression that is evaluted to produce the value that is
     *  assigned to the column named in the `col` field.
     */
    com.urbanlogiq.ulsdk.types.Expr _expr;
    public com.urbanlogiq.ulsdk.types.Expr getExpr() {
        return this._expr;
    }
    public void setExpr(com.urbanlogiq.ulsdk.types.Expr value) {
        this._expr = value;
    }

    public SetExpr(com.urbanlogiq.ulsdk.types.generated.SetExpr o) {
        this._col = o.col();
        this._expr = new com.urbanlogiq.ulsdk.types.Expr(o.expr());
    }

    public SetExpr(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.SetExpr.getRootAsSetExpr(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        int colOffset = builder.createString(this._col);
        int exprOffset = this._expr.serializeTo(builder);
        com.urbanlogiq.ulsdk.types.generated.SetExpr.startSetExpr(builder);
        com.urbanlogiq.ulsdk.types.generated.SetExpr.addCol(builder, colOffset);
        com.urbanlogiq.ulsdk.types.generated.SetExpr.addExpr(builder, exprOffset);
        return com.urbanlogiq.ulsdk.types.generated.SetExpr.endSetExpr(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public SetExpr() {
        this._col = new String();
        this._expr = new com.urbanlogiq.ulsdk.types.Expr();
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}