// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

/**
 *  Compressed Sparse Fiber (CSF) sparse tensor index.
 */
public final class SparseTensorIndexCSF {
    /**
     *  axisOrder stores the sequence in which dimensions were traversed to
     *  produce the prefix tree.
     *  For example, the axisOrder for the above X is:
     *  ```text
     *    axisOrder(X) = [0, 1, 2, 3].
     *  ```
     */
    int[] _axisOrder;
    public int[] getAxisOrder() {
        return this._axisOrder;
    }
    public void setAxisOrder(int[] value) {
        this._axisOrder = value;
    }

    /**
     *  indicesBuffers stores values of nodes.
     *  Each tensor dimension corresponds to a buffer in indicesBuffers.
     *  For example, the indicesBuffers for the above X is:
     *  ```text
     *    indicesBuffer(X) = [
     *                         [0, 1],
     *                         [0, 1, 1],
     *                         [0, 0, 1, 1],
     *                         [1, 2, 0, 2, 0, 0, 1, 2]
     *                       ].
     *  ```
     */
    com.urbanlogiq.ulsdk.types.Buffer[] _indicesBuffers;
    public com.urbanlogiq.ulsdk.types.Buffer[] getIndicesBuffers() {
        return this._indicesBuffers;
    }
    public void setIndicesBuffers(com.urbanlogiq.ulsdk.types.Buffer[] value) {
        this._indicesBuffers = value;
    }

    /**
     *  The type of values in indicesBuffers
     */
    com.urbanlogiq.ulsdk.types.Int _indicesType;
    public com.urbanlogiq.ulsdk.types.Int getIndicesType() {
        return this._indicesType;
    }
    public void setIndicesType(com.urbanlogiq.ulsdk.types.Int value) {
        this._indicesType = value;
    }

    /**
     *  indptrBuffers stores the sparsity structure.
     *  Each two consecutive dimensions in a tensor correspond to a buffer in
     *  indptrBuffers. A pair of consecutive values at `indptrBuffers[dim][i]`
     *  and `indptrBuffers[dim][i + 1]` signify a range of nodes in
     *  `indicesBuffers[dim + 1]` who are children of `indicesBuffers[dim][i]` node.
     * 
     *  For example, the indptrBuffers for the above X is:
     *  ```text
     *    indptrBuffer(X) = [
     *                        [0, 2, 3],
     *                        [0, 1, 3, 4],
     *                        [0, 2, 4, 5, 8]
     *                      ].
     *  ```
     */
    com.urbanlogiq.ulsdk.types.Buffer[] _indptrBuffers;
    public com.urbanlogiq.ulsdk.types.Buffer[] getIndptrBuffers() {
        return this._indptrBuffers;
    }
    public void setIndptrBuffers(com.urbanlogiq.ulsdk.types.Buffer[] value) {
        this._indptrBuffers = value;
    }

    /**
     *  CSF is a generalization of compressed sparse row (CSR) index.
     *  See [smith2017knl](http://shaden.io/pub-files/smith2017knl.pdf)
     * 
     *  CSF index recursively compresses each dimension of a tensor into a set
     *  of prefix trees. Each path from a root to leaf forms one tensor
     *  non-zero index. CSF is implemented with two arrays of buffers and one
     *  arrays of integers.
     * 
     *  For example, let X be a 2x3x4x5 tensor and let it have the following
     *  8 non-zero values:
     *  ```text
     *    X[0, 0, 0, 1] := 1
     *    X[0, 0, 0, 2] := 2
     *    X[0, 1, 0, 0] := 3
     *    X[0, 1, 0, 2] := 4
     *    X[0, 1, 1, 0] := 5
     *    X[1, 1, 1, 0] := 6
     *    X[1, 1, 1, 1] := 7
     *    X[1, 1, 1, 2] := 8
     *  ```
     *  As a prefix tree this would be represented as:
     *  ```text
     *          0          1
     *         / \         |
     *        0   1        1
     *       /   / \       |
     *      0   0   1      1
     *     /|  /|   |    /| |
     *    1 2 0 2   0   0 1 2
     *  ```
     *  The type of values in indptrBuffers
     */
    com.urbanlogiq.ulsdk.types.Int _indptrType;
    public com.urbanlogiq.ulsdk.types.Int getIndptrType() {
        return this._indptrType;
    }
    public void setIndptrType(com.urbanlogiq.ulsdk.types.Int value) {
        this._indptrType = value;
    }

    public SparseTensorIndexCSF(com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF o) {
        int[] axisOrder = new int[o.axisOrderLength()];
        for (int i = 0; i < o.axisOrderLength(); i++) {
            axisOrder[i] = (int)o.axisOrder(i);
        }
        this._axisOrder = axisOrder;
        com.urbanlogiq.ulsdk.types.Buffer[] indicesBuffers = new com.urbanlogiq.ulsdk.types.Buffer[o.indicesBuffersLength()];
        for (int i = 0; i < o.indicesBuffersLength(); i++) {
            com.urbanlogiq.ulsdk.types.Buffer indicesBuffersValue = null;
            if (o.indicesBuffers(i) != null) {
                indicesBuffersValue = new com.urbanlogiq.ulsdk.types.Buffer(o.indicesBuffers(i));
            }
            indicesBuffers[i] = indicesBuffersValue;
        }
        this._indicesBuffers = indicesBuffers;
        this._indicesType = new com.urbanlogiq.ulsdk.types.Int(o.indicesType());
        com.urbanlogiq.ulsdk.types.Buffer[] indptrBuffers = new com.urbanlogiq.ulsdk.types.Buffer[o.indptrBuffersLength()];
        for (int i = 0; i < o.indptrBuffersLength(); i++) {
            com.urbanlogiq.ulsdk.types.Buffer indptrBuffersValue = null;
            if (o.indptrBuffers(i) != null) {
                indptrBuffersValue = new com.urbanlogiq.ulsdk.types.Buffer(o.indptrBuffers(i));
            }
            indptrBuffers[i] = indptrBuffersValue;
        }
        this._indptrBuffers = indptrBuffers;
        this._indptrType = new com.urbanlogiq.ulsdk.types.Int(o.indptrType());
    }

    public SparseTensorIndexCSF(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.getRootAsSparseTensorIndexCSF(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.startAxisOrderVector(builder, this._axisOrder.length);
        for (int i = this._axisOrder.length - 1; i >= 0; i--) {
            builder.addInt(this._axisOrder[i]);
        }
        int axisOrderOffset = builder.endVector();
        int[] indicesBuffersOffsets = new int[this._indicesBuffers.length];;
        for (int i = 0; i < this._indicesBuffers.length; i++) {
            indicesBuffersOffsets[i] = this._indicesBuffers[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.startIndicesBuffersVector(builder, this._indicesBuffers.length);
        for (int i = indicesBuffersOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(indicesBuffersOffsets[i]);
        }
        int indicesBuffersOffset = builder.endVector();
        int indicesTypeOffset = this._indicesType.serializeTo(builder);
        int[] indptrBuffersOffsets = new int[this._indptrBuffers.length];;
        for (int i = 0; i < this._indptrBuffers.length; i++) {
            indptrBuffersOffsets[i] = this._indptrBuffers[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.startIndptrBuffersVector(builder, this._indptrBuffers.length);
        for (int i = indptrBuffersOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(indptrBuffersOffsets[i]);
        }
        int indptrBuffersOffset = builder.endVector();
        int indptrTypeOffset = this._indptrType.serializeTo(builder);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.startSparseTensorIndexCSF(builder);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.addAxisOrder(builder, axisOrderOffset);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.addIndicesBuffers(builder, indicesBuffersOffset);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.addIndicesType(builder, indicesTypeOffset);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.addIndptrBuffers(builder, indptrBuffersOffset);
        com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.addIndptrType(builder, indptrTypeOffset);
        return com.urbanlogiq.ulsdk.types.generated.SparseTensorIndexCSF.endSparseTensorIndexCSF(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public SparseTensorIndexCSF() {
        this._axisOrder = new int[0];
        this._indicesBuffers = new com.urbanlogiq.ulsdk.types.Buffer[0];
        this._indicesType = new com.urbanlogiq.ulsdk.types.Int();
        this._indptrBuffers = new com.urbanlogiq.ulsdk.types.Buffer[0];
        this._indptrType = new com.urbanlogiq.ulsdk.types.Int();
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}