// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

public final class UnaryQueryElement {
    com.urbanlogiq.ulsdk.types.Distinct _distinct;
    public com.urbanlogiq.ulsdk.types.Distinct getDistinct() {
        return this._distinct;
    }
    public void setDistinct(com.urbanlogiq.ulsdk.types.Distinct value) {
        this._distinct = value;
    }

    com.urbanlogiq.ulsdk.types.Expr[] _fields;
    public com.urbanlogiq.ulsdk.types.Expr[] getFields() {
        return this._fields;
    }
    public void setFields(com.urbanlogiq.ulsdk.types.Expr[] value) {
        this._fields = value;
    }

    com.urbanlogiq.ulsdk.types.Function _filter;
    public com.urbanlogiq.ulsdk.types.Function getFilter() {
        return this._filter;
    }
    public void setFilter(com.urbanlogiq.ulsdk.types.Function value) {
        this._filter = value;
    }

    com.urbanlogiq.ulsdk.types.Expr[] _groupBy;
    public com.urbanlogiq.ulsdk.types.Expr[] getGroupBy() {
        return this._groupBy;
    }
    public void setGroupBy(com.urbanlogiq.ulsdk.types.Expr[] value) {
        this._groupBy = value;
    }

    com.urbanlogiq.ulsdk.types.Function _having;
    public com.urbanlogiq.ulsdk.types.Function getHaving() {
        return this._having;
    }
    public void setHaving(com.urbanlogiq.ulsdk.types.Function value) {
        this._having = value;
    }

    com.urbanlogiq.ulsdk.types.Join[] _joins;
    public com.urbanlogiq.ulsdk.types.Join[] getJoins() {
        return this._joins;
    }
    public void setJoins(com.urbanlogiq.ulsdk.types.Join[] value) {
        this._joins = value;
    }

    long _limit;
    public long getLimit() {
        return this._limit;
    }
    public void setLimit(long value) {
        this._limit = value;
    }

    com.urbanlogiq.ulsdk.types.TableOrderBy[] _orderBy;
    public com.urbanlogiq.ulsdk.types.TableOrderBy[] getOrderBy() {
        return this._orderBy;
    }
    public void setOrderBy(com.urbanlogiq.ulsdk.types.TableOrderBy[] value) {
        this._orderBy = value;
    }

    com.urbanlogiq.ulsdk.types.TableSource[] _sources;
    public com.urbanlogiq.ulsdk.types.TableSource[] getSources() {
        return this._sources;
    }
    public void setSources(com.urbanlogiq.ulsdk.types.TableSource[] value) {
        this._sources = value;
    }

    public UnaryQueryElement(com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement o) {
        if (o.distinct() != null) {
            this._distinct = new com.urbanlogiq.ulsdk.types.Distinct(o.distinct());
        }
        if (o.fieldsVector() != null) {
            com.urbanlogiq.ulsdk.types.Expr[] fields = new com.urbanlogiq.ulsdk.types.Expr[o.fieldsLength()];
            for (int i = 0; i < o.fieldsLength(); i++) {
                com.urbanlogiq.ulsdk.types.Expr fieldsValue = null;
                if (o.fields(i) != null) {
                    fieldsValue = new com.urbanlogiq.ulsdk.types.Expr(o.fields(i));
                }
                fields[i] = fieldsValue;
            }
            this._fields = fields;
        }
        if (o.filter() != null) {
            this._filter = new com.urbanlogiq.ulsdk.types.Function(o.filter());
        }
        if (o.groupByVector() != null) {
            com.urbanlogiq.ulsdk.types.Expr[] groupBy = new com.urbanlogiq.ulsdk.types.Expr[o.groupByLength()];
            for (int i = 0; i < o.groupByLength(); i++) {
                com.urbanlogiq.ulsdk.types.Expr groupByValue = null;
                if (o.groupBy(i) != null) {
                    groupByValue = new com.urbanlogiq.ulsdk.types.Expr(o.groupBy(i));
                }
                groupBy[i] = groupByValue;
            }
            this._groupBy = groupBy;
        }
        if (o.having() != null) {
            this._having = new com.urbanlogiq.ulsdk.types.Function(o.having());
        }
        if (o.joinsVector() != null) {
            com.urbanlogiq.ulsdk.types.Join[] joins = new com.urbanlogiq.ulsdk.types.Join[o.joinsLength()];
            for (int i = 0; i < o.joinsLength(); i++) {
                com.urbanlogiq.ulsdk.types.Join joinsValue = null;
                if (o.joins(i) != null) {
                    joinsValue = new com.urbanlogiq.ulsdk.types.Join(o.joins(i));
                }
                joins[i] = joinsValue;
            }
            this._joins = joins;
        }
        this._limit = o.limit();
        if (o.orderByVector() != null) {
            com.urbanlogiq.ulsdk.types.TableOrderBy[] orderBy = new com.urbanlogiq.ulsdk.types.TableOrderBy[o.orderByLength()];
            for (int i = 0; i < o.orderByLength(); i++) {
                com.urbanlogiq.ulsdk.types.TableOrderBy orderByValue = null;
                if (o.orderBy(i) != null) {
                    orderByValue = new com.urbanlogiq.ulsdk.types.TableOrderBy(o.orderBy(i));
                }
                orderBy[i] = orderByValue;
            }
            this._orderBy = orderBy;
        }
        com.urbanlogiq.ulsdk.types.TableSource[] sources = new com.urbanlogiq.ulsdk.types.TableSource[o.sourcesLength()];
        for (int i = 0; i < o.sourcesLength(); i++) {
            com.urbanlogiq.ulsdk.types.TableSource sourcesValue = null;
            if (o.sources(i) != null) {
                sourcesValue = new com.urbanlogiq.ulsdk.types.TableSource(o.sources(i));
            }
            sources[i] = sourcesValue;
        }
        this._sources = sources;
    }

    public UnaryQueryElement(byte[] data) {
        this(com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.getRootAsUnaryQueryElement(com.google.flatbuffers.ByteBufferUtil.removeSizePrefix(java.nio.ByteBuffer.wrap(data))));
    }

    public int serializeTo(com.google.flatbuffers.FlatBufferBuilder builder) {
        Integer distinctOffset = null;
        if (this._distinct != null) {
            distinctOffset = this._distinct.serializeTo(builder);
        }
        Integer fieldsOffset = null;
        if (this._fields != null) {
            int[] fieldsOffsets = new int[this._fields.length];;
            for (int i = 0; i < this._fields.length; i++) {
                fieldsOffsets[i] = this._fields[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startFieldsVector(builder, this._fields.length);
            for (int i = fieldsOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(fieldsOffsets[i]);
            }
            fieldsOffset = builder.endVector();
        }
        Integer filterOffset = null;
        if (this._filter != null) {
            filterOffset = this._filter.serializeTo(builder);
        }
        Integer groupByOffset = null;
        if (this._groupBy != null) {
            int[] groupByOffsets = new int[this._groupBy.length];;
            for (int i = 0; i < this._groupBy.length; i++) {
                groupByOffsets[i] = this._groupBy[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startGroupByVector(builder, this._groupBy.length);
            for (int i = groupByOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(groupByOffsets[i]);
            }
            groupByOffset = builder.endVector();
        }
        Integer havingOffset = null;
        if (this._having != null) {
            havingOffset = this._having.serializeTo(builder);
        }
        Integer joinsOffset = null;
        if (this._joins != null) {
            int[] joinsOffsets = new int[this._joins.length];;
            for (int i = 0; i < this._joins.length; i++) {
                joinsOffsets[i] = this._joins[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startJoinsVector(builder, this._joins.length);
            for (int i = joinsOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(joinsOffsets[i]);
            }
            joinsOffset = builder.endVector();
        }
        Integer orderByOffset = null;
        if (this._orderBy != null) {
            int[] orderByOffsets = new int[this._orderBy.length];;
            for (int i = 0; i < this._orderBy.length; i++) {
                orderByOffsets[i] = this._orderBy[i].serializeTo(builder);
            }
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startOrderByVector(builder, this._orderBy.length);
            for (int i = orderByOffsets.length - 1; i >= 0; i--) {
                builder.addOffset(orderByOffsets[i]);
            }
            orderByOffset = builder.endVector();
        }
        int[] sourcesOffsets = new int[this._sources.length];;
        for (int i = 0; i < this._sources.length; i++) {
            sourcesOffsets[i] = this._sources[i].serializeTo(builder);
        }
        com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startSourcesVector(builder, this._sources.length);
        for (int i = sourcesOffsets.length - 1; i >= 0; i--) {
            builder.addOffset(sourcesOffsets[i]);
        }
        int sourcesOffset = builder.endVector();
        com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.startUnaryQueryElement(builder);
        if (distinctOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addDistinct(builder, distinctOffset);
        }
        if (fieldsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addFields(builder, fieldsOffset);
        }
        if (filterOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addFilter(builder, filterOffset);
        }
        if (groupByOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addGroupBy(builder, groupByOffset);
        }
        if (havingOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addHaving(builder, havingOffset);
        }
        if (joinsOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addJoins(builder, joinsOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addLimit(builder, this._limit);
        if (orderByOffset != null) {
            com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addOrderBy(builder, orderByOffset);
        }
        com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.addSources(builder, sourcesOffset);
        return com.urbanlogiq.ulsdk.types.generated.UnaryQueryElement.endUnaryQueryElement(builder);
    }

    public byte[] toBytes() {
        com.google.flatbuffers.FlatBufferBuilder builder = new com.google.flatbuffers.FlatBufferBuilder();
        int offset = this.serializeTo(builder);
        builder.finishSizePrefixed(offset);
        return builder.sizedByteArray();
    }

    public UnaryQueryElement() {
        this._distinct = new com.urbanlogiq.ulsdk.types.Distinct();
        this._fields = new com.urbanlogiq.ulsdk.types.Expr[0];
        this._filter = new com.urbanlogiq.ulsdk.types.Function();
        this._groupBy = new com.urbanlogiq.ulsdk.types.Expr[0];
        this._having = new com.urbanlogiq.ulsdk.types.Function();
        this._joins = new com.urbanlogiq.ulsdk.types.Join[0];
        this._orderBy = new com.urbanlogiq.ulsdk.types.TableOrderBy[0];
        this._sources = new com.urbanlogiq.ulsdk.types.TableSource[0];
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, o, false, null, true);
    }
}