// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.types;

/**
 *  The update cadence of the dataset. This looks at the maximum timestamp/observation date in the data,
 *  and not when the pipeline ran because we can run a pipeline today that only ingests data from 2020.
 */
public final class UpdateCadence {
    public static final long UC_UNSET = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_UNSET;
    public static final long UC_IRREGULAR = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_IRREGULAR;
    public static final long UC_DAILY = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_DAILY;
    public static final long UC_WEEKLY = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_WEEKLY;
    public static final long UC_BI_WEEKLY = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_BI_WEEKLY;
    public static final long UC_MONTHLY = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_MONTHLY;
    public static final long UC_YEARLY = com.urbanlogiq.ulsdk.types.generated.UpdateCadence.UC_YEARLY;
}