// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package permissions

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/urbanlogiq/ulsdk/types/generated"
	"github.com/urbanlogiq/ulsdk/types/id"
)

var _ flatbuffers.UOffsetT

type PermissionTy uint32

const (
	PermissionTyPERM_BROWSE PermissionTy = 1
	PermissionTyPERM_READ PermissionTy = 2
	PermissionTyPERM_APPEND PermissionTy = 4
	PermissionTyPERM_MODIFY PermissionTy = 8
)

type AccessControlList struct {
	Extends *id.ObjectId
	Roles []Role
}

func AccessControlListFromFbs(fbs *generated.AccessControlList) *AccessControlList {
	o := &AccessControlList{}
	if fbsVal := fbs.Extends(nil); fbsVal != nil {
		o.Extends = id.ObjectIdFromFbs(fbsVal)
	}
	for i := 0; i < fbs.RolesLength(); i++ {
		var item generated.Role
		if fbs.Roles(&item, i) {
			o.Roles = append(o.Roles, *RoleFromFbs(&item))
		}
	}
	return o
}

// AccessControlListFromBytes deserializes a AccessControlList from size-prefixed FlatBuffer bytes.
func AccessControlListFromBytes(data []byte) (*AccessControlList, error) {
	fbs := generated.GetSizePrefixedRootAsAccessControlList(data, 0)
	return AccessControlListFromFbs(fbs), nil
}

// ToBytes serializes the AccessControlList to size-prefixed FlatBuffer bytes.
func (o *AccessControlList) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the AccessControlList into a FlatBuffer builder and returns the offset.
func (o *AccessControlList) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var extendsOffset flatbuffers.UOffsetT
	if o.Extends != nil {
		extendsOffset = o.Extends.SerializeTo(builder)
	}
	rolesOffsets := make([]flatbuffers.UOffsetT, len(o.Roles))
	for i := range o.Roles {
		rolesOffsets[i] = o.Roles[i].SerializeTo(builder)
	}
	generated.AccessControlListStartRolesVector(builder, len(o.Roles))
	for i := len(rolesOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(rolesOffsets[i])
	}
	rolesVecOffset := builder.EndVector(len(o.Roles))
	generated.AccessControlListStart(builder)
	generated.AccessControlListAddExtends(builder, extendsOffset)
	generated.AccessControlListAddRoles(builder, rolesVecOffset)
	return generated.AccessControlListEnd(builder)
}

type Role struct {
	Permission uint32
	Principal id.B2cid
}

func RoleFromFbs(fbs *generated.Role) *Role {
	o := &Role{}
	o.Permission = fbs.Permission()
	if fbsVal := fbs.Principal(nil); fbsVal != nil {
		o.Principal = *id.B2cidFromFbs(fbsVal)
	}
	return o
}

// RoleFromBytes deserializes a Role from size-prefixed FlatBuffer bytes.
func RoleFromBytes(data []byte) (*Role, error) {
	fbs := generated.GetSizePrefixedRootAsRole(data, 0)
	return RoleFromFbs(fbs), nil
}

// ToBytes serializes the Role to size-prefixed FlatBuffer bytes.
func (o *Role) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the Role into a FlatBuffer builder and returns the offset.
func (o *Role) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	principalOffset := o.Principal.SerializeTo(builder)
	generated.RoleStart(builder)
	generated.RoleAddPermission(builder, o.Permission)
	generated.RoleAddPrincipal(builder, principalOffset)
	return generated.RoleEnd(builder)
}
