// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.api.directory;

public final class Namespace {
    String _holderId;
    public String getHolderId() {
        return this._holderId;
    }
    public void setHolderId(String value) {
        this._holderId = value;
    }

    String _holderKind;
    public String getHolderKind() {
        return this._holderKind;
    }
    public void setHolderKind(String value) {
        this._holderKind = value;
    }

    String _preferred;
    public String getPreferred() {
        return this._preferred;
    }
    public void setPreferred(String value) {
        this._preferred = value;
    }

    String _status;
    public String getStatus() {
        return this._status;
    }
    public void setStatus(String value) {
        this._status = value;
    }

    String _label;
    public String getLabel() {
        return this._label;
    }
    public void setLabel(String value) {
        this._label = value;
    }

    public java.util.Map<String, Object> toMap() {
        java.util.Map<String, Object> o = new java.util.HashMap();
        Object holderIdSerialized = null;
        holderIdSerialized = this._holderId;
        o.put("holderId", holderIdSerialized);

        Object holderKindSerialized = null;
        holderKindSerialized = this._holderKind;
        o.put("holderKind", holderKindSerialized);

        Object preferredSerialized = null;
        preferredSerialized = this._preferred;
        o.put("preferred", preferredSerialized);

        Object statusSerialized = null;
        statusSerialized = this._status;
        o.put("status", statusSerialized);

        Object labelSerialized = null;
        if (this._label != null) {
            labelSerialized = this._label;
        }
        o.put("label", labelSerialized);

        return o;
    }

    public Namespace(org.json.JSONObject o) {
        Object holderIdValue = o.get("holderId");
        this._holderId = (String)holderIdValue;
        Object holderKindValue = o.get("holderKind");
        this._holderKind = (String)holderKindValue;
        Object preferredValue = o.get("preferred");
        this._preferred = (String)preferredValue;
        Object statusValue = o.get("status");
        this._status = (String)statusValue;
        Object labelValue = null;
        if (o.has("label") && !o.isNull("label")) {
            labelValue = o.get("label");
        }
        if (labelValue != null) {
            this._label = (String)labelValue;
        }
    }

    public Namespace() {
        this._holderId = "";
        this._holderKind = "";
        this._preferred = "";
        this._status = "";
        this._label = null;
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(
            this,
            o,
            false,
            null,
            true
        );
    }
}