// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package com.urbanlogiq.ulsdk.api.gate;

public final class AdGroup {
    String _id;
    public String getId() {
        return this._id;
    }
    public void setId(String value) {
        this._id = value;
    }

    String _displayName;
    public String getDisplayName() {
        return this._displayName;
    }
    public void setDisplayName(String value) {
        this._displayName = value;
    }

    String _description;
    public String getDescription() {
        return this._description;
    }
    public void setDescription(String value) {
        this._description = value;
    }

    public java.util.Map<String, Object> toMap() {
        java.util.Map<String, Object> o = new java.util.HashMap();
        Object idSerialized = null;
        idSerialized = this._id;
        o.put("id", idSerialized);

        Object displayNameSerialized = null;
        displayNameSerialized = this._displayName;
        o.put("displayName", displayNameSerialized);

        Object descriptionSerialized = null;
        if (this._description != null) {
            descriptionSerialized = this._description;
        }
        o.put("description", descriptionSerialized);

        return o;
    }

    public AdGroup(org.json.JSONObject o) {
        Object idValue = o.get("id");
        this._id = (String)idValue;
        Object displayNameValue = o.get("displayName");
        this._displayName = (String)displayNameValue;
        Object descriptionValue = null;
        if (o.has("description") && !o.isNull("description")) {
            descriptionValue = o.get("description");
        }
        if (descriptionValue != null) {
            this._description = (String)descriptionValue;
        }
    }

    public AdGroup() {
        this._id = "";
        this._displayName = "";
        this._description = null;
    }

    @Override
    public boolean equals(Object o) {
        return org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(
            this,
            o,
            false,
            null,
            true
        );
    }
}