// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package registry

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/urbanlogiq/ulsdk/types/generated"
	"github.com/urbanlogiq/ulsdk/types/id"
)

var _ flatbuffers.UOffsetT

// RegistryFieldSource -
//  Where a field's value is read from.
type RegistryFieldSource byte

const (
	RegistryFieldSourceSource RegistryFieldSource = 0
	RegistryFieldSourceObject RegistryFieldSource = 1
)

// RegistryFieldTy -
//  Object registries (docs/architecture/briefs/object-registries-brief.md):
//  a registry is a declared projection of one governed object type into
//  table streams, projected once per source revision and queried as the
//  caller, whose rows are filtered by the objects' own ACLs.
//  The column type a projected field lands as.
type RegistryFieldTy byte

const (
	RegistryFieldTyString RegistryFieldTy = 0
	RegistryFieldTyInt RegistryFieldTy = 1
	RegistryFieldTyFloat RegistryFieldTy = 2
	RegistryFieldTyBool RegistryFieldTy = 3
	RegistryFieldTyTimestamp RegistryFieldTy = 4
	RegistryFieldTyObjectId RegistryFieldTy = 5
	RegistryFieldTyContentId RegistryFieldTy = 6
)

// ProjectResult -
//  The outcome of projecting one object.
type ProjectResult struct {
	ObjectId id.ObjectId
	Revision uint64
	Rows uint32
	SourceHash string
}

func ProjectResultFromFbs(fbs *generated.ProjectResult) *ProjectResult {
	o := &ProjectResult{}
	if fbsVal := fbs.ObjectId(nil); fbsVal != nil {
		o.ObjectId = *id.ObjectIdFromFbs(fbsVal)
	}
	o.Revision = fbs.Revision()
	o.Rows = fbs.Rows()
	o.SourceHash = string(fbs.SourceHash())
	return o
}

// ProjectResultFromBytes deserializes a ProjectResult from size-prefixed FlatBuffer bytes.
func ProjectResultFromBytes(data []byte) (*ProjectResult, error) {
	fbs := generated.GetSizePrefixedRootAsProjectResult(data, 0)
	return ProjectResultFromFbs(fbs), nil
}

// ToBytes serializes the ProjectResult to size-prefixed FlatBuffer bytes.
func (o *ProjectResult) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the ProjectResult into a FlatBuffer builder and returns the offset.
func (o *ProjectResult) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	objectIdOffset := o.ObjectId.SerializeTo(builder)
	sourceHashOffset := builder.CreateString(o.SourceHash)
	generated.ProjectResultStart(builder)
	generated.ProjectResultAddObjectId(builder, objectIdOffset)
	generated.ProjectResultAddRevision(builder, o.Revision)
	generated.ProjectResultAddRows(builder, o.Rows)
	generated.ProjectResultAddSourceHash(builder, sourceHashOffset)
	return generated.ProjectResultEnd(builder)
}

// RegistryField -
//  One projected column: name, type, and the pointer that fills it.
type RegistryField struct {
	Name string
	Pointer string
	Source byte
	Transform *string
	Ty byte
}

func RegistryFieldFromFbs(fbs *generated.RegistryField) *RegistryField {
	o := &RegistryField{}
	o.Name = string(fbs.Name())
	o.Pointer = string(fbs.Pointer())
	o.Source = byte(fbs.Source())
	if s := fbs.Transform(); s != nil {
		str := string(s)
		o.Transform = &str
	}
	o.Ty = byte(fbs.Ty())
	return o
}

// RegistryFieldFromBytes deserializes a RegistryField from size-prefixed FlatBuffer bytes.
func RegistryFieldFromBytes(data []byte) (*RegistryField, error) {
	fbs := generated.GetSizePrefixedRootAsRegistryField(data, 0)
	return RegistryFieldFromFbs(fbs), nil
}

// ToBytes serializes the RegistryField to size-prefixed FlatBuffer bytes.
func (o *RegistryField) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RegistryField into a FlatBuffer builder and returns the offset.
func (o *RegistryField) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString(o.Name)
	pointerOffset := builder.CreateString(o.Pointer)
	var transformOffset flatbuffers.UOffsetT
	if o.Transform != nil {
		transformOffset = builder.CreateString(*o.Transform)
	}
	generated.RegistryFieldStart(builder)
	generated.RegistryFieldAddName(builder, nameOffset)
	generated.RegistryFieldAddPointer(builder, pointerOffset)
	generated.RegistryFieldAddSource(builder, generated.RegistryFieldSource(o.Source))
	generated.RegistryFieldAddTransform(builder, transformOffset)
	generated.RegistryFieldAddTy(builder, generated.RegistryFieldTy(o.Ty))
	return generated.RegistryFieldEnd(builder)
}

// RegistryRelation -
//  A multi-valued part of the source projected as its own table: one row per
//  element of the array (or map entry) the pointer names. `columns` are read
//  relative to each element; an element that is a scalar fills the single
//  column named `value`.
type RegistryRelation struct {
	Columns []RegistryField
	Name string
	Pointer string
	Source byte
	Transform *string
}

func RegistryRelationFromFbs(fbs *generated.RegistryRelation) *RegistryRelation {
	o := &RegistryRelation{}
	for i := 0; i < fbs.ColumnsLength(); i++ {
		var item generated.RegistryField
		if fbs.Columns(&item, i) {
			o.Columns = append(o.Columns, *RegistryFieldFromFbs(&item))
		}
	}
	o.Name = string(fbs.Name())
	o.Pointer = string(fbs.Pointer())
	o.Source = byte(fbs.Source())
	if s := fbs.Transform(); s != nil {
		str := string(s)
		o.Transform = &str
	}
	return o
}

// RegistryRelationFromBytes deserializes a RegistryRelation from size-prefixed FlatBuffer bytes.
func RegistryRelationFromBytes(data []byte) (*RegistryRelation, error) {
	fbs := generated.GetSizePrefixedRootAsRegistryRelation(data, 0)
	return RegistryRelationFromFbs(fbs), nil
}

// ToBytes serializes the RegistryRelation to size-prefixed FlatBuffer bytes.
func (o *RegistryRelation) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RegistryRelation into a FlatBuffer builder and returns the offset.
func (o *RegistryRelation) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	columnsOffsets := make([]flatbuffers.UOffsetT, len(o.Columns))
	for i := range o.Columns {
		columnsOffsets[i] = o.Columns[i].SerializeTo(builder)
	}
	generated.RegistryRelationStartColumnsVector(builder, len(o.Columns))
	for i := len(columnsOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(columnsOffsets[i])
	}
	columnsVecOffset := builder.EndVector(len(o.Columns))
	nameOffset := builder.CreateString(o.Name)
	pointerOffset := builder.CreateString(o.Pointer)
	var transformOffset flatbuffers.UOffsetT
	if o.Transform != nil {
		transformOffset = builder.CreateString(*o.Transform)
	}
	generated.RegistryRelationStart(builder)
	generated.RegistryRelationAddColumns(builder, columnsVecOffset)
	generated.RegistryRelationAddName(builder, nameOffset)
	generated.RegistryRelationAddPointer(builder, pointerOffset)
	generated.RegistryRelationAddSource(builder, generated.RegistryFieldSource(o.Source))
	generated.RegistryRelationAddTransform(builder, transformOffset)
	return generated.RegistryRelationEnd(builder)
}

// RegistrySpec -
//  The declaration of a registry.
type RegistrySpec struct {
	Fields []RegistryField
	Key string
	Name string
	ObjectTy int16
	Relations []RegistryRelation
	SourceField string
	SourceFormat string
	SourceHashField string
	Version uint32
}

func RegistrySpecFromFbs(fbs *generated.RegistrySpec) *RegistrySpec {
	o := &RegistrySpec{}
	for i := 0; i < fbs.FieldsLength(); i++ {
		var item generated.RegistryField
		if fbs.Fields(&item, i) {
			o.Fields = append(o.Fields, *RegistryFieldFromFbs(&item))
		}
	}
	o.Key = string(fbs.Key())
	o.Name = string(fbs.Name())
	o.ObjectTy = int16(fbs.ObjectTy())
	for i := 0; i < fbs.RelationsLength(); i++ {
		var item generated.RegistryRelation
		if fbs.Relations(&item, i) {
			o.Relations = append(o.Relations, *RegistryRelationFromFbs(&item))
		}
	}
	o.SourceField = string(fbs.SourceField())
	o.SourceFormat = string(fbs.SourceFormat())
	o.SourceHashField = string(fbs.SourceHashField())
	o.Version = fbs.Version()
	return o
}

// RegistrySpecFromBytes deserializes a RegistrySpec from size-prefixed FlatBuffer bytes.
func RegistrySpecFromBytes(data []byte) (*RegistrySpec, error) {
	fbs := generated.GetSizePrefixedRootAsRegistrySpec(data, 0)
	return RegistrySpecFromFbs(fbs), nil
}

// ToBytes serializes the RegistrySpec to size-prefixed FlatBuffer bytes.
func (o *RegistrySpec) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RegistrySpec into a FlatBuffer builder and returns the offset.
func (o *RegistrySpec) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	fieldsOffsets := make([]flatbuffers.UOffsetT, len(o.Fields))
	for i := range o.Fields {
		fieldsOffsets[i] = o.Fields[i].SerializeTo(builder)
	}
	generated.RegistrySpecStartFieldsVector(builder, len(o.Fields))
	for i := len(fieldsOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(fieldsOffsets[i])
	}
	fieldsVecOffset := builder.EndVector(len(o.Fields))
	keyOffset := builder.CreateString(o.Key)
	nameOffset := builder.CreateString(o.Name)
	relationsOffsets := make([]flatbuffers.UOffsetT, len(o.Relations))
	for i := range o.Relations {
		relationsOffsets[i] = o.Relations[i].SerializeTo(builder)
	}
	generated.RegistrySpecStartRelationsVector(builder, len(o.Relations))
	for i := len(relationsOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(relationsOffsets[i])
	}
	relationsVecOffset := builder.EndVector(len(o.Relations))
	sourceFieldOffset := builder.CreateString(o.SourceField)
	sourceFormatOffset := builder.CreateString(o.SourceFormat)
	sourceHashFieldOffset := builder.CreateString(o.SourceHashField)
	generated.RegistrySpecStart(builder)
	generated.RegistrySpecAddFields(builder, fieldsVecOffset)
	generated.RegistrySpecAddKey(builder, keyOffset)
	generated.RegistrySpecAddName(builder, nameOffset)
	generated.RegistrySpecAddObjectTy(builder, generated.DataCatalogObjectTy(o.ObjectTy))
	generated.RegistrySpecAddRelations(builder, relationsVecOffset)
	generated.RegistrySpecAddSourceField(builder, sourceFieldOffset)
	generated.RegistrySpecAddSourceFormat(builder, sourceFormatOffset)
	generated.RegistrySpecAddSourceHashField(builder, sourceHashFieldOffset)
	generated.RegistrySpecAddVersion(builder, o.Version)
	return generated.RegistrySpecEnd(builder)
}

// RegistryTable -
//  A projected table and the stream that holds it.
type RegistryTable struct {
	Name string
	Stream id.ObjectId
}

func RegistryTableFromFbs(fbs *generated.RegistryTable) *RegistryTable {
	o := &RegistryTable{}
	o.Name = string(fbs.Name())
	if fbsVal := fbs.Stream(nil); fbsVal != nil {
		o.Stream = *id.ObjectIdFromFbs(fbsVal)
	}
	return o
}

// RegistryTableFromBytes deserializes a RegistryTable from size-prefixed FlatBuffer bytes.
func RegistryTableFromBytes(data []byte) (*RegistryTable, error) {
	fbs := generated.GetSizePrefixedRootAsRegistryTable(data, 0)
	return RegistryTableFromFbs(fbs), nil
}

// ToBytes serializes the RegistryTable to size-prefixed FlatBuffer bytes.
func (o *RegistryTable) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RegistryTable into a FlatBuffer builder and returns the offset.
func (o *RegistryTable) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString(o.Name)
	streamOffset := o.Stream.SerializeTo(builder)
	generated.RegistryTableStart(builder)
	generated.RegistryTableAddName(builder, nameOffset)
	generated.RegistryTableAddStream(builder, streamOffset)
	return generated.RegistryTableEnd(builder)
}

// RegistryTables -
//  What a query needs to bind: the registry's streams by table name.
type RegistryTables struct {
	Spec string
	Tables []RegistryTable
	Version uint32
}

func RegistryTablesFromFbs(fbs *generated.RegistryTables) *RegistryTables {
	o := &RegistryTables{}
	o.Spec = string(fbs.Spec())
	for i := 0; i < fbs.TablesLength(); i++ {
		var item generated.RegistryTable
		if fbs.Tables(&item, i) {
			o.Tables = append(o.Tables, *RegistryTableFromFbs(&item))
		}
	}
	o.Version = fbs.Version()
	return o
}

// RegistryTablesFromBytes deserializes a RegistryTables from size-prefixed FlatBuffer bytes.
func RegistryTablesFromBytes(data []byte) (*RegistryTables, error) {
	fbs := generated.GetSizePrefixedRootAsRegistryTables(data, 0)
	return RegistryTablesFromFbs(fbs), nil
}

// ToBytes serializes the RegistryTables to size-prefixed FlatBuffer bytes.
func (o *RegistryTables) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RegistryTables into a FlatBuffer builder and returns the offset.
func (o *RegistryTables) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	specOffset := builder.CreateString(o.Spec)
	tablesOffsets := make([]flatbuffers.UOffsetT, len(o.Tables))
	for i := range o.Tables {
		tablesOffsets[i] = o.Tables[i].SerializeTo(builder)
	}
	generated.RegistryTablesStartTablesVector(builder, len(o.Tables))
	for i := len(tablesOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(tablesOffsets[i])
	}
	tablesVecOffset := builder.EndVector(len(o.Tables))
	generated.RegistryTablesStart(builder)
	generated.RegistryTablesAddSpec(builder, specOffset)
	generated.RegistryTablesAddTables(builder, tablesVecOffset)
	generated.RegistryTablesAddVersion(builder, o.Version)
	return generated.RegistryTablesEnd(builder)
}
