// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package exploration

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/urbanlogiq/ulsdk/types/generated"
	"github.com/urbanlogiq/ulsdk/types/id"
)

var _ flatbuffers.UOffsetT

// Exploration -
//  An exploration, as cortext's exploration registry stores it: one governed
//  object per program a mission asked to run, homed in the `.models` system
//  directory beside `ModelManifest`, `OntologyDeclaration` and `Mission` (the
//  same governed-object recipe), with an ACL the owner controls and the
//  platform's own revision history.
//
//  The object is a *reference*, like the other three: the program is a Drive
//  file named here by id, content revision and sha256, and the fields a reader
//  lists on (the mission it belongs to, its status, who asked for it and when)
//  are projected once per source revision into the `explorations` registry
//  (registry.fbs), so nothing on a read path opens the program. The program is
//  an authored text file — the registry reads it as text, not as a structured
//  source. `result_digest` is the one line the run left behind; the result
//  itself is not here and does not revise the object.
type Exploration struct {
	AuthoredBy *string
	CreatedAt int64
	ExplorationId string
	MissionId *string
	ProgramCid *id.ContentId
	ProgramId id.ObjectId
	ProgramSha256 string
	RequestedBy *string
	ResultDigest *string
	Status *string
}

func ExplorationFromFbs(fbs *generated.Exploration) *Exploration {
	o := &Exploration{}
	if s := fbs.AuthoredBy(); s != nil {
		str := string(s)
		o.AuthoredBy = &str
	}
	o.CreatedAt = fbs.CreatedAt()
	o.ExplorationId = string(fbs.ExplorationId())
	if s := fbs.MissionId(); s != nil {
		str := string(s)
		o.MissionId = &str
	}
	if fbsVal := fbs.ProgramCid(nil); fbsVal != nil {
		o.ProgramCid = id.ContentIdFromFbs(fbsVal)
	}
	if fbsVal := fbs.ProgramId(nil); fbsVal != nil {
		o.ProgramId = *id.ObjectIdFromFbs(fbsVal)
	}
	o.ProgramSha256 = string(fbs.ProgramSha256())
	if s := fbs.RequestedBy(); s != nil {
		str := string(s)
		o.RequestedBy = &str
	}
	if s := fbs.ResultDigest(); s != nil {
		str := string(s)
		o.ResultDigest = &str
	}
	if s := fbs.Status(); s != nil {
		str := string(s)
		o.Status = &str
	}
	return o
}

// ExplorationFromBytes deserializes a Exploration from size-prefixed FlatBuffer bytes.
func ExplorationFromBytes(data []byte) (*Exploration, error) {
	fbs := generated.GetSizePrefixedRootAsExploration(data, 0)
	return ExplorationFromFbs(fbs), nil
}

// ToBytes serializes the Exploration to size-prefixed FlatBuffer bytes.
func (o *Exploration) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the Exploration into a FlatBuffer builder and returns the offset.
func (o *Exploration) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var authoredByOffset flatbuffers.UOffsetT
	if o.AuthoredBy != nil {
		authoredByOffset = builder.CreateString(*o.AuthoredBy)
	}
	explorationIdOffset := builder.CreateString(o.ExplorationId)
	var missionIdOffset flatbuffers.UOffsetT
	if o.MissionId != nil {
		missionIdOffset = builder.CreateString(*o.MissionId)
	}
	var programCidOffset flatbuffers.UOffsetT
	if o.ProgramCid != nil {
		programCidOffset = o.ProgramCid.SerializeTo(builder)
	}
	programIdOffset := o.ProgramId.SerializeTo(builder)
	programSha256Offset := builder.CreateString(o.ProgramSha256)
	var requestedByOffset flatbuffers.UOffsetT
	if o.RequestedBy != nil {
		requestedByOffset = builder.CreateString(*o.RequestedBy)
	}
	var resultDigestOffset flatbuffers.UOffsetT
	if o.ResultDigest != nil {
		resultDigestOffset = builder.CreateString(*o.ResultDigest)
	}
	var statusOffset flatbuffers.UOffsetT
	if o.Status != nil {
		statusOffset = builder.CreateString(*o.Status)
	}
	generated.ExplorationStart(builder)
	generated.ExplorationAddAuthoredBy(builder, authoredByOffset)
	generated.ExplorationAddCreatedAt(builder, o.CreatedAt)
	generated.ExplorationAddExplorationId(builder, explorationIdOffset)
	generated.ExplorationAddMissionId(builder, missionIdOffset)
	generated.ExplorationAddProgramCid(builder, programCidOffset)
	generated.ExplorationAddProgramId(builder, programIdOffset)
	generated.ExplorationAddProgramSha256(builder, programSha256Offset)
	generated.ExplorationAddRequestedBy(builder, requestedByOffset)
	generated.ExplorationAddResultDigest(builder, resultDigestOffset)
	generated.ExplorationAddStatus(builder, statusOffset)
	return generated.ExplorationEnd(builder)
}
