// Copyright (c), CommunityLogiq Software
//
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/urbanlogiq/ulsdk/types/generated"
	"github.com/urbanlogiq/ulsdk/types/schema"
)

var _ flatbuffers.UOffsetT

// BodyCompressionMethod -
//  Provided for forward compatibility in case we need to support different
//  strategies for compressing the IPC message body (like whole-body
//  compression rather than buffer-level) in the future
type BodyCompressionMethod int8

const (
	BodyCompressionMethodBUFFER BodyCompressionMethod = 0
)

type CompressionType int8

const (
	CompressionTypeLZ4_FRAME CompressionType = 0
	CompressionTypeZSTD CompressionType = 1
)

// BodyCompression -
//  Optional compression for the memory buffers constituting IPC message
//  bodies. Intended for use with RecordBatch but could be used for other
//  message types
type BodyCompression struct {
	Codec int8
	Method int8
}

func BodyCompressionFromFbs(fbs *generated.BodyCompression) *BodyCompression {
	o := &BodyCompression{}
	o.Codec = int8(fbs.Codec())
	o.Method = int8(fbs.Method())
	return o
}

// BodyCompressionFromBytes deserializes a BodyCompression from size-prefixed FlatBuffer bytes.
func BodyCompressionFromBytes(data []byte) (*BodyCompression, error) {
	fbs := generated.GetSizePrefixedRootAsBodyCompression(data, 0)
	return BodyCompressionFromFbs(fbs), nil
}

// ToBytes serializes the BodyCompression to size-prefixed FlatBuffer bytes.
func (o *BodyCompression) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the BodyCompression into a FlatBuffer builder and returns the offset.
func (o *BodyCompression) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	generated.BodyCompressionStart(builder)
	generated.BodyCompressionAddCodec(builder, generated.CompressionType(o.Codec))
	generated.BodyCompressionAddMethod(builder, generated.BodyCompressionMethod(o.Method))
	return generated.BodyCompressionEnd(builder)
}

// RecordBatch -
//  A data header describing the shared memory layout of a "record" or "row"
//  batch. Some systems call this a "row batch" internally and others a "record
//  batch".
type RecordBatch struct {
	Buffers []schema.Buffer
	Compression *BodyCompression
	Length int64
	Nodes []FieldNode
	VariadicBufferCounts []int64
}

func RecordBatchFromFbs(fbs *generated.RecordBatch) *RecordBatch {
	o := &RecordBatch{}
	for i := 0; i < fbs.BuffersLength(); i++ {
		var item generated.Buffer
		if fbs.Buffers(&item, i) {
			o.Buffers = append(o.Buffers, *schema.BufferFromFbs(&item))
		}
	}
	if fbsVal := fbs.Compression(nil); fbsVal != nil {
		o.Compression = BodyCompressionFromFbs(fbsVal)
	}
	o.Length = fbs.Length()
	for i := 0; i < fbs.NodesLength(); i++ {
		var item generated.FieldNode
		if fbs.Nodes(&item, i) {
			o.Nodes = append(o.Nodes, *FieldNodeFromFbs(&item))
		}
	}
	for i := 0; i < fbs.VariadicBufferCountsLength(); i++ {
		o.VariadicBufferCounts = append(o.VariadicBufferCounts, fbs.VariadicBufferCounts(i))
	}
	return o
}

// RecordBatchFromBytes deserializes a RecordBatch from size-prefixed FlatBuffer bytes.
func RecordBatchFromBytes(data []byte) (*RecordBatch, error) {
	fbs := generated.GetSizePrefixedRootAsRecordBatch(data, 0)
	return RecordBatchFromFbs(fbs), nil
}

// ToBytes serializes the RecordBatch to size-prefixed FlatBuffer bytes.
func (o *RecordBatch) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the RecordBatch into a FlatBuffer builder and returns the offset.
func (o *RecordBatch) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var buffersVecOffset flatbuffers.UOffsetT // TODO: struct vector
	var compressionOffset flatbuffers.UOffsetT
	if o.Compression != nil {
		compressionOffset = o.Compression.SerializeTo(builder)
	}
	var nodesVecOffset flatbuffers.UOffsetT // TODO: struct vector
	generated.RecordBatchStartVariadicBufferCountsVector(builder, len(o.VariadicBufferCounts))
	for i := len(o.VariadicBufferCounts) - 1; i >= 0; i-- {
		builder.PrependInt64(o.VariadicBufferCounts[i])
	}
	variadicBufferCountsVecOffset := builder.EndVector(len(o.VariadicBufferCounts))
	generated.RecordBatchStart(builder)
	generated.RecordBatchAddBuffers(builder, buffersVecOffset)
	generated.RecordBatchAddCompression(builder, compressionOffset)
	generated.RecordBatchAddLength(builder, o.Length)
	generated.RecordBatchAddNodes(builder, nodesVecOffset)
	generated.RecordBatchAddVariadicBufferCounts(builder, variadicBufferCountsVecOffset)
	return generated.RecordBatchEnd(builder)
}

// DictionaryBatch -
//  For sending dictionary encoding information. Any Field can be
//  dictionary-encoded, but in this case none of its children may be
//  dictionary-encoded.
//  There is one vector / column per dictionary, but that vector / column
//  may be spread across multiple dictionary batches by using the isDelta
//  flag
type DictionaryBatch struct {
	Data *RecordBatch
	Id int64
	IsDelta bool
}

func DictionaryBatchFromFbs(fbs *generated.DictionaryBatch) *DictionaryBatch {
	o := &DictionaryBatch{}
	if fbsVal := fbs.Data(nil); fbsVal != nil {
		o.Data = RecordBatchFromFbs(fbsVal)
	}
	o.Id = fbs.Id()
	o.IsDelta = fbs.IsDelta()
	return o
}

// DictionaryBatchFromBytes deserializes a DictionaryBatch from size-prefixed FlatBuffer bytes.
func DictionaryBatchFromBytes(data []byte) (*DictionaryBatch, error) {
	fbs := generated.GetSizePrefixedRootAsDictionaryBatch(data, 0)
	return DictionaryBatchFromFbs(fbs), nil
}

// ToBytes serializes the DictionaryBatch to size-prefixed FlatBuffer bytes.
func (o *DictionaryBatch) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the DictionaryBatch into a FlatBuffer builder and returns the offset.
func (o *DictionaryBatch) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	var dataOffset flatbuffers.UOffsetT
	if o.Data != nil {
		dataOffset = o.Data.SerializeTo(builder)
	}
	generated.DictionaryBatchStart(builder)
	generated.DictionaryBatchAddData(builder, dataOffset)
	generated.DictionaryBatchAddId(builder, o.Id)
	generated.DictionaryBatchAddIsDelta(builder, o.IsDelta)
	return generated.DictionaryBatchEnd(builder)
}

// MessageHeader -
//  ----------------------------------------------------------------------
//  The root Message type
//  This union enables us to easily send different message types without
//  redundant storage, and in the future we can easily add new message types.
//
//  Arrow implementations do not need to implement all of the message types,
//  which may include experimental metadata types. For maximum compatibility,
//  it is best to send data using RecordBatch
// MessageHeader is a union type. Possible concrete types: Schema, DictionaryBatch, RecordBatch, Tensor, SparseTensor
type MessageHeader interface {
	isMessageHeader()
}

// FieldNode -
//  ----------------------------------------------------------------------
//  Data structures for describing a table row batch (a collection of
//  equal-length Arrow arrays)
//  Metadata about a field at some level of a nested type tree (but not
//  its children).
//
//  For example, a List<Int16> with values `[[1, 2, 3], null, [4], [5, 6], null]`
//  would have {length: 5, null_count: 2} for its List node, and {length: 6,
//  null_count: 0} for its Int16 node, as separate FieldNode structs
type FieldNode struct {
	Length int64
	NullCount int64
}

func FieldNodeFromFbs(fbs *generated.FieldNode) *FieldNode {
	o := &FieldNode{}
	o.Length = fbs.Length()
	o.NullCount = fbs.NullCount()
	return o
}


type Message struct {
	BodyLength int64
	CustomMetadata []schema.KeyValue
	Header interface{}
	Version int16
}

func MessageFromFbs(fbs *generated.Message) *Message {
	o := &Message{}
	o.BodyLength = fbs.BodyLength()
	for i := 0; i < fbs.CustomMetadataLength(); i++ {
		var item generated.KeyValue
		if fbs.CustomMetadata(&item, i) {
			o.CustomMetadata = append(o.CustomMetadata, *schema.KeyValueFromFbs(&item))
		}
	}
	o.Version = int16(fbs.Version())
	return o
}

// MessageFromBytes deserializes a Message from size-prefixed FlatBuffer bytes.
func MessageFromBytes(data []byte) (*Message, error) {
	fbs := generated.GetSizePrefixedRootAsMessage(data, 0)
	return MessageFromFbs(fbs), nil
}

// ToBytes serializes the Message to size-prefixed FlatBuffer bytes.
func (o *Message) ToBytes() []byte {
	builder := flatbuffers.NewBuilder(256)
	offset := o.SerializeTo(builder)
	builder.FinishSizePrefixed(offset)
	return builder.FinishedBytes()
}

// SerializeTo writes the Message into a FlatBuffer builder and returns the offset.
func (o *Message) SerializeTo(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	customMetadataOffsets := make([]flatbuffers.UOffsetT, len(o.CustomMetadata))
	for i := range o.CustomMetadata {
		customMetadataOffsets[i] = o.CustomMetadata[i].SerializeTo(builder)
	}
	generated.MessageStartCustomMetadataVector(builder, len(o.CustomMetadata))
	for i := len(customMetadataOffsets) - 1; i >= 0; i-- {
		builder.PrependUOffsetT(customMetadataOffsets[i])
	}
	customMetadataVecOffset := builder.EndVector(len(o.CustomMetadata))
	generated.MessageStart(builder)
	generated.MessageAddBodyLength(builder, o.BodyLength)
	generated.MessageAddCustomMetadata(builder, customMetadataVecOffset)
	generated.MessageAddVersion(builder, generated.MetadataVersion(o.Version))
	return generated.MessageEnd(builder)
}
