// Copyright (c), CommunityLogiq Software
// 
// THIS FILE IS AUTOGENERATED, DO NOT EDIT

#include "ulsdk/types/usecase.h"

#include "test.h"

bool
test_use_case() {
    ::ul::types::UseCase t;
    const std::vector<uint8_t> bytes = ::ul::types::to_bytes(t);
    ::ul::types::UseCase deserialized = ::ul::types::UseCase(bytes);
    return true;
}

TypeTest test_use_case_obj(test_use_case, "UseCase");

bool
test_use_case_input_pair() {
    ::ul::types::UseCaseInputPair t;
    const std::vector<uint8_t> bytes = ::ul::types::to_bytes(t);
    ::ul::types::UseCaseInputPair deserialized = ::ul::types::UseCaseInputPair(bytes);
    return true;
}

TypeTest test_use_case_input_pair_obj(test_use_case_input_pair, "UseCaseInputPair");
